### ISSUE TITLE
Incorrect chromium wayland uv while resizing window

### ISSUE THREAD

**Issue by tomKPZ** [hyprwm/Hyprland#1462]
This issue seems to occur with Chrome windows at 2x scaling.  Issue doesn't occur on sway.  See this video for a demo:

https://user-images.githubusercontent.com/9124077/215848089-2769c549-2ee2-4464-9b1f-86e9700f02bb.mp4

**Comment by vaxerski** [comment]
not scaling per se, the uv gets fucked.

**Comment by TheSunCat** [comment]
This same issue can be reproduced with WebCord from the AUR package `webcord-git-screenshare` when running as Wayland native. I am using a scaling of 1.4x.

**Comment by vaxerski** [comment]
obviously, it uses chromium?

**Comment by TheSunCat** [comment]
It uses Electron. I haven't seen other Electron apps (vscodium, spotify, normal webcord) exhibit this issue, so I pointed it out.

**Comment by purin-aurelia** [comment]
discord and chromium experience the same issue
this is without any scaling
cant recreate outside of using mouse resizing
cant recreate on other window types (any qt, firefox, alacritty)

chrome will eventually correct itself soon after the mouse lets go when resizing
discord does not always recover and can often become blurry out of space and or entirely broken ( this is the regular discord client not some mod )

**Comment by aalhitennf** [comment]
same thing happens for me with all electron apps using wayland with --ozone-platform=wayland

**Comment by felixsanz** [comment]
@vaxerski this happens to every app, but some are more sensible to glitch at intermediate states on this gpu rendering.

on telegram-desktop it happens a lot. when you click on an image, telegram transition to the fullscreeny image viewer thing, and when clicking outside to close the image and go back to normal GUI, so many times it appears broken like if the animation didnt't reach the final state (and that's weird because I have animations disabled).

To fix it you have to make telegram-desktop fullscreen or resize it so the "animation" starts again and can reach the final state.

This happens very often to make it unusable. And doesn't happen on sway.

Here are two screenshows showing how it looks when it happens, and how it should normally look.

glitch state:
![1696942519](https://github.com/hyprwm/Hyprland/assets/6182099/3b33d61d-c806-4c38-91bb-8a41cfb5ca3d)

normal state:
![1696942478](https://github.com/hyprwm/Hyprland/assets/6182099/487da99c-da77-4fd7-b233-3ee63cd9c589)

**Comment by vaxerski** [comment]
this is a different issue

**Comment by fybx** [comment]
when will this get fixed?

**Comment by vaxerski** [comment]
in the future

**Comment by YuryenUcahh** [comment]
seems like electron apps fixed 

https://github.com/hyprwm/Hyprland/assets/51506997/0b3bf268-7844-4c88-9c18-06482b5594bc

but there is still issue in chromium

**Comment by random2907** [comment]
https://github.com/hyprwm/Hyprland/assets/81547183/2fa3e9be-9cb0-4535-b7bb-21abb9c225ab

i think it something related to hardware acceleration

**Comment by fybx** [comment]
> output.mp4 
> i think it something related to hardware acceleration . mainly in brave browser .

Which external graphics driver does Brave use? I am on an Arch machine with AMD integrated graphics (I've not installed a single graphics driver explicitly) and have had this Chromium (& electron) issue for a long time.

**Comment by random2907** [comment]
> > output.mp4
> > i think it something related to hardware acceleration . mainly in brave browser .
> 
> Which external graphics driver does Brave use? I am on an Arch machine with AMD integrated graphics (I've not installed a single graphics driver explicitly) and have had this Chromium (& electron) issue for a long time.

I don't install anything it's intel igpu 12th gen I currently noticed in intel_gpu_top that it not using gpu it causing the cpu but un gpu section it shows that hardware acceleration enabled but it's not it's broken on all chromium browser and fully disabling gpu acceleration it fix the ux and graphical glitch means hardware acceleration is partly broken there is issue report on brave github

**Comment by nooneyy** [comment]
I managed to fix this on my machine by creating ~/.config/brave-flags.conf and putting this in it:

```
--ozone-platform-hint=wayland
--use-gl=egl
```

`--use-gl=egl` being the one that fixed it.

**Comment by random2907** [comment]
> I managed to fix this on my machine by creating ~/.config/brave-flags.conf and putting this in it:
> 
> ```
> --ozone-platform-hint=wayland
> --use-gl=egl
> ```
> 
> `--use-gl=egl` being the one that fixed it.
> 
> Edit: nevermind, that disables gpu acceleration

yes the hardware acceleration is broken.

**Comment by Edgars-Cirulis** [comment]
Still an issue?

**Comment by TheSunCat** [comment]
Yup. As long as you have hw acceleration on a Chromium/Electron app and it runs as Wayland, it will stretch the wrong way on resize.

**Comment by Edgars-Cirulis** [comment]
so thats hyprland regression.

**Comment by BRS5672023** [comment]
add the flag '--disable-features=WaylandFractionalScaleV1' seems fix the issue for me...

**Comment by Edgars-Cirulis** [comment]
> add the flag `--disable-features=WaylandFractionalScaleV1` seems fix the issue for me...

Seems like bad implementation on hyprland side

**Comment by awerty-noob** [comment]
> add the flag `--disable-features=WaylandFractionalScaleV1` seems fix the issue for me...
> 
> well, I find this flag breaks chromium display contents (especially on scrolling) on my laptop for scaling is set to 2...

From my case, only scaling=1 is ok, others have display issue like only refreshing a quarter page etc.

**Comment by nonetrix** [comment]
Is there a bug report on the Chromium bug tracker to look at? They might not know about this perhaps, sorry for necro posting kinda, but was just curious to be honest. Doesn't happen on other compositors to my knowledge, so perhaps it could be bypassed with a plugin if it bothers people enough, but I assume you don't want to add a workaround for broken applications as it's a Chromium bug

**Comment by nonetrix** [comment]
Should have looked, but here it is https://issues.chromium.org/issues/40267260

**Comment by sertchan** [comment]
Created the ticket specifically about this issue: https://issues.chromium.org/issues/337905327
Y'all can click +1 etc. You know how things work with Google.

**Comment by vaxerski** [comment]
#1462 should finally fix this

**Comment by nonetrix** [comment]
So was it not Chromium?

**Comment by vaxerski** [comment]
I have no clue. I rewrote xdg_shell and I can't see the bug anymore, at least on my end.

**Comment by vaxerski** [comment]
nvm, still happens when you dont pass weird flags. Disregard me.

**Comment by danimateo** [comment]
fwiw the fix of using `--disable-features=WaylandFractionalScaleV1` doesn't work anymore since [this](https://github.com/hyprwm/Hyprland/commit/6967a31450441fc5605c05db6f65505dace4b263) commit (bisect), unfortunately it's a huge one

**Comment by nonetrix** [comment]
Interesting

**Comment by fybx** [comment]
> > Yup. As long as you have hw acceleration on a Chromium/Electron app and it runs as Wayland, it will stretch the wrong way on resize.
> 
> Not a case in wlroots or kde using wayland

+ KDE and GNOME with Wayland doesn't have this

**Comment by nonetrix** [comment]
Also on unrelated note Chromium likes to stay locked at 60 FPS despite being on my 165Hz monitor a lot, I had that issue on X too I think Chromium is just being dumb not sure if that is known issue or not

**Comment by fybx** [comment]
> ... Windows just works though and Firefox no issue whatsoever :/
> 
> Linux and especially Wayland seems like joke to Google lol

I gave up using Windows completely when it decided to nuke my ESP, and Chromium (was ungoogled-chromium ofc) because of the insufficient (and reluctant) support for Wayland.

They can both go to hell.

**Comment by sdutwsl** [comment]
same issue

**Comment by Azarattum** [comment]
Is there any change to fix this without disabling hardware acceleration in the browser? The artifacts are really annoying and ruin satisfaction from the animations. I would say, this bug is my №1 issue with Hyprland right now.

**Comment by BRS5672023** [comment]
> Is there any change to fix this without disabling hardware acceleration in the browser? The artifacts are really annoying and ruin satisfaction from the animations. I would say, this bug is my №1 issue with Hyprland right now.

I'm using the windowrule `windowrulev2=noanim,class:^(chromium)$,title:(- Chromium)$` to turn off the animation for now, while it behaves strangely when I drag a tab and detach it, which I now use the shortcut <kbd>Ctrl</kbd>+<kbd>PageUp/PageDown</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>PageUp/PageDown</kbd> to interact with tabs..

**Comment by CyanChanges** [comment]
Is there any progress here, without disabling hardware acceleration?
Anybody know whether it's a Hyprland problem or Chrome/Chromium issue?

**Comment by vaxerski** [comment]
chromium bug

**Comment by Edgars-Cirulis** [comment]
> chromium bug

Hehe, You're funny. Hyprland is only compositor with this bug meanwhile Sway works fine, also wayfire works fine.

**Comment by suderman** [comment]
Chromium/Electron is a glitchy mess on my nvidia Hyprland desktop, including this experience. Workaround is to force Xwayland in all Chromium apps. This fixes everything except now I have to deal with zooming/upscaling (else everything is tiny on my high res screen) and the loss of dragndrop. But 90% good.

**Comment by Azarattum** [comment]
This issue is also present in many electron apps. So, even if chromium fixes it, it will be a while until all the apps update. If any reasonable workaround is possible on the compositor side, that would be great.

**Comment by suderman** [comment]
I keep Wayland on my non-nvidia Intel integrated graphics laptop, because it's 99% solid. Only remaining issue is the visual glitches during Chromium window resize, but I can live with that.

**Comment by vaxerski** [comment]
> Hehe, You're funny. Hyprland is only compositor with this bug meanwhile Sway works fine, also wayfire works fine.

doesn't mean it's a hyprland bug. Chromium is the only one with this bug.

My guess is chromium shits itself if it receives multiple resize requests before it has a chance to repaint fully

**Comment by Edgars-Cirulis** [comment]
> > Hehe, You're funny. Hyprland is only compositor with this bug meanwhile Sway works fine, also wayfire works fine.
> 
> doesn't mean it's a hyprland bug. Chromium is the only one with this bug.
> 
> My guess is chromium shits itself if it receives multiple resize requests before it has a chance to repaint fully

I've looked into source code, found the issue. The current implementation handles static geometry and viewport changes, but doesnt adapt to real time size changes in calculateUVForSurface also not sure about that, maybe call calculateUVForSurface  on renderWindow  ?

**Comment by Edgars-Cirulis** [comment]
> > > > Hehe, You're funny. Hyprland is only compositor with this bug meanwhile Sway works fine, also wayfire works fine.
> > > 
> > > 
> > > doesn't mean it's a hyprland bug. Chromium is the only one with this bug.
> > > My guess is chromium shits itself if it receives multiple resize requests before it has a chance to repaint fully
> > 
> > 
> > I've looked into source code, found the issue. The current implementation handles static geometry and viewport changes, but doesnt adapt to real time size changes in calculateUVForSurface also not sure about that, maybe call calculateUVForSurface on renderWindow ? So no Vaxry its not Chromium issue.
> 
> any chance of a PR? (kindly asking)

Ehh. I could but what's the point here if Vaxry will always say it's XWayland / Electron / Chromium / Nvidis issue. If we know that it dosnt happen on any other wayland compositor...

**Comment by nonetrix** [comment]
Sounds like easy fix at least hopefully if true, I guess someone could look into it I'm too dumb unfortunately. Anymore pointers or anything perhaps though maybe? But also why is Chromium doing that in first place when no other applications seem to lol?

**Comment by vaxerski** [comment]
there is no reason for me not to accept a pr that fixes stuff. I doubt it's on hyprland's side but I'm open to be proven wrong.

**Comment by fybx** [comment]
> > > > > Hehe, You're funny. Hyprland is only compositor with this bug meanwhile Sway works fine, also wayfire works fine.
> > > > 
> > > > 
> > > > doesn't mean it's a hyprland bug. Chromium is the only one with this bug.
> > > > My guess is chromium shits itself if it receives multiple resize requests before it has a chance to repaint fully
> > > 
> > > 
> > > I've looked into source code, found the issue. The current implementation handles static geometry and viewport changes, but doesnt adapt to real time size changes in calculateUVForSurface also not sure about that, maybe call calculateUVForSurface on renderWindow ? So no Vaxry its not Chromium issue.
> > 
> > 
> > any chance of a PR? (kindly asking)
> 
> Ehh. I could but what's the point here if Vaxry will always say it's XWayland / Electron / Chromium / Nvidis issue. If we know that it dosnt happen on any other wayland compositor...

the point is the benefit of the open source community/hyprland community IMHO

**Comment by zjeffer** [comment]
Hey @Edgars-Cirulis, have you made any progress on this?

**Comment by xiaozhuo256** [comment]
Same problem.

**Comment by PaideiaDilemma** [comment]
Can someone test #7975?

**Comment by nonetrix** [comment]
If this is truly fixed can someone mention this in the Chromium issue?

**Comment by BRS5672023** [comment]
It is maybe worth mentioning that #7975 also fixes the issue that zotero used to stretch itself when its geometry is changed, while I've not seen any other gtk apps behave like this..

**Comment by PaideiaDilemma** [comment]
> Well, it is not fixed by the commit actually but I'm happy to see this issue is gone now.

Not? Please elaborate

**Comment by BRS5672023** [comment]
> > Well, it is not fixed by the commit actually but I'm happy to see this issue is gone now.
> 
> Not? Please elaborate

Sorry, I mean the issue with zotero, the chromium issue is fixed with your commit.

**Comment by nonetrix** [comment]
It's only half fixed for me just much less extreme

https://github.com/user-attachments/assets/77e07a46-6698-4269-9e5b-a40160d0c97d

**Comment by BRS5672023** [comment]
> It's only half fixed for me just much less extreme

I can also reproduce this by toggling split.

**Comment by suderman** [comment]
I just tried switching my chromium apps from x11 to wayland on my nvidia desktop, and now everything is perfect. Not sure when this got fixed, but I'm super pumped. :-)

**Comment by rushiiMachine** [comment]
I had this issue persist even after the alleged fix until I disabled `vrr` (I think?)
