### ISSUE TITLE
[XWAYLAND] Cannot drag anything in Unreal Engine

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/Hyprland#2127]
<details>
<summary>NOTE: Krita is fixed now, thanks! This still applies for Unreal Engine, so I am keeping the issue open. Expand to view the original issue including Krita</summary>

Krita does not support Wayland, and Unreal Engine does not respond to mouse input on Wayland, so I unfortunately have to run both under Xwayland. Both apps seem to exhibit the same bug, which is why I am grouping them in this issue.

In Krita, the primary way to manage layers is by dragging one up/down. When I do this in Hyprland, Krita appears to be unfocused for one frame, then focus is brought back to Krita and the drag-and-drop is instantly "dropped". If, within that frame, I was able to move my mouse to the desired destination, the layer does move, indicating that a drag and drop did indeed happen, but was ended nearly instantly.

<details>
<summary>Logs for doing this in Krita</summary>
<br>

```
[LOG] Set keyboard focus to surface 564cb5d59320, with window name:  [Not Saved]  (16.0 MiB)  * — Krita
[LOG] New XWayland Surface created (class krita).
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6bee8 -> 564cb6246e68 (owner: XWayland Window)
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6be68 -> 564cb6246f38 (owner: XWayland Window)
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6bfa8 -> 564cb62474e8 (owner: XWayland Window)
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6be78 -> 564cb6247348 (owner: XWayland Window)
[LOG] Registered signal for owner 564cb6247550: 564cb6252468 -> 564cb6247558 (owner: CWLSurface)
[LOG] CWLSurface 564cb6247550 called init()
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6bef8 -> 564cb6246ed0 (owner: CWindow)
[LOG] Searching for matching rules for krita (title: Krita)
[LOG] Window rule rounding 0 -> title:^(Krita)$ matched 564cb6246e00 [Krita]
[LOG] Window rule noblur -> title:^(Krita)$ matched 564cb6246e00 [Krita]
[LOG] Window rule opaque -> title:^(Krita)$ matched 564cb6246e00 [Krita]
[LOG] Set keyboard focus to surface 564cb6252180, with window name: Krita
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6bec8 -> 564cb6247070 (owner: XWayland Window Late)
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6bed8 -> 564cb62472e0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6bf08 -> 564cb6246fa0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6bea8 -> 564cb62471a8 (owner: Xwayland Window Late)
[ERR] Tried to connect a listener twice?!
[LOG] Registered signal for owner 564cb6246e00: 564cb5d6bfb8 -> 564cb6247008 (owner: XWayland Window Late)
[LOG] Registered signal for owner 564cb6243150: 564cb6252458 -> 564cb62431c8 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 564cb6243150: 564cb6252448 -> 564cb6243230 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 564cb6243150: 564cb6252468 -> 564cb6243298 (owner: SurfaceTreeNode)
[LOG] Creating a surfaceTree Root! (pWindow: 564cb6246e00)
[LOG] Map request dispatched, monitor eDP-2, xywh: 1579.000000 254.000000 232.000000 27.000000
[LOG] Unmanaged window 564cb6246e00 requests geometry update to 1579 250 232 27
[LOG] Unmanaged window 564cb6246e00 requests geometry update to 1580 246 232 27
[LOG] Window 564cb6246e00 unmapped (class krita)
[LOG] Unregistered late callbacks XWL
[LOG] Callback 564cb6247098 -> 564cb6247090, XWayland Window Late removed.
[LOG] Callback 564cb6247308 -> 564cb6247300, XWayland Window Late removed.
[LOG] Callback 564cb6246fc8 -> 564cb6246fc0, XWayland Window Late removed.
[LOG] Callback 564cb6247030 -> 564cb6247028, XWayland Window Late removed.
[LOG] Callback 564cb62471d0 -> 564cb62471c8, Xwayland Window Late removed.
[LOG] Framebuffer created, status 36053
[LOG] On closed window, new focused candidate is 564cb6259820
[LOG] Set keyboard focus to surface 564cb5d59320, with window name:  [Not Saved]  (16.0 MiB)  * — Krita
[LOG] Destroying the SubSurface tree of unmapped window 564cb6246e00
[LOG] Callback 564cb6243258 -> 564cb6243250, SurfaceTreeNode removed.
[LOG] Callback 564cb62432c0 -> 564cb62432b8, SurfaceTreeNode removed.
[LOG] Callback 564cb62431f0 -> 564cb62431e8, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 564cb6247580 -> 564cb6247578, CWLSurface removed.
[LOG] CWLSurface 564cb6247550 called destroy()
[LOG] Callback 564cb6246ef8 -> 564cb6246ef0, CWindow removed.
[LOG] Window 564cb6246e00 destroyed, queueing. (class )
[LOG] XWayland class raw: krita
[LOG] Callback 564cb6246e90 -> 564cb6246e88, XWayland Window removed.
[LOG] Callback 564cb6246f60 -> 564cb6246f58, XWayland Window removed.
[LOG] Callback 564cb6247370 -> 564cb6247368, XWayland Window removed.
[LOG] Callback 564cb6247510 -> 564cb6247508, XWayland Window removed.
[LOG] Cleanup: destroyed a window
```

</details>

</details>

In Unreal Engine, to interact with the "Blueprints" language, you drag links off of nodes (similar to Blender's shader editor).

Here is a video of the issue in Unreal Engine:
https://user-images.githubusercontent.com/44881120/233791623-f872688b-a7ac-4b35-b618-a0bc364a3280.mp4

[Logs from the video](https://github.com/hyprwm/Hyprland/files/11301581/unreal.log).

Additionally, focus as a whole is majorly broken on UE. If you open a right click menu and move your mouse over the options (especially to a sub-menu), the menu will close and put UE in a strange "unfocused" state, where the framerate is limited to 1fps and all menus instantly close when they are opened. Refocusing UE usually fixes this.

These two issues together make UE nearly impossible to use on Hyprland.

Hyprland version: 254c680bda9365b74472f066c1e6ee994a0d0a67dirty
Let me know if I can provide anything else!

**Comment by vaxerski** [comment]
catch the class of the window that opens and add a nofocus rule to it

**Comment by TheSunCat** [comment]
Is there an easy way to do this, especially for the Unreal Engine issue? Ideally just printing every new window that is opened, for example.

**Comment by vaxerski** [comment]
`watch -n 0.1 "cat /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log | grep "rules" | tail -n 40"`

**Comment by TheSunCat** [comment]
Thanks... it's the same properties as Krita's dialog boxes, so I don't think it can be singled out. Why could this be working in Sway and not Hyprland, without specific window rules? The same issue applies to Unreal Engine: windows that need to have focus also share class & title with these problematic ones.

**Comment by vaxerski** [comment]
it's because there is a bug somewhere in hyprland but I am not installing a 10GB pack to test

**Comment by TheSunCat** [comment]
It's reproducible with Krita, which is 160MiB according to `pacman -Qi`. I'm also happy to help with any testing required for Unreal Engine.

**Comment by vaxerski** [comment]
krita should be working with the retarded fix 97b03687657ba141f11128d25aa345d92892bd2d

> Why could this be working in Sway and not Hyprland, without specific window rules?

Because X11 is such a fucking horrible protocol it's genuinely fucking baffling people still consider it "the standard"

**Comment by vaxerski** [comment]
I also like the fact how y'all shit on xwayland handling in hyprland meanwhile the "create new" window's size on sway is completely fucking wrong but on hl it's alright

**Comment by TheSunCat** [comment]
Thanks for the Krita fix! I see it was another one of those X11 window "properties".
I don't think Hyprland's Xwayland implementation is bad (most of the issues I have complained about in the past were the hidpi patch's fault, which does indeed work better on Sway, but is too buggy to use in general). Besides that, Hyprland's implementation works well for the most part, and the fact these issues are getting fixed makes it even better.

As for Unreal: is there a way to print X11 window properties for new surfaces being created? I could then provide a log of this and maybe it can help find how Unreal is expecting Hyprland & Xwayland to filter its drag-and-drop objects.
Unfortunately I have a class which forces usage of Unreal Engine, and I am not aware of a way to run it natively in Wayland to avoid these issues (it runs with SDL_VIDEODRIVER=wayland, keyboard works, but there is no mouse input, making it sadly useless).

**Comment by vaxerski** [comment]
> As for Unreal: is there a way to print X11 window properties for new surfaces being created?

ye

[patch.txt](https://github.com/hyprwm/Hyprland/files/11302383/patch.txt)

Will print all atoms in the beginning and then window's atoms on window open

**Comment by TheSunCat** [comment]
With this patch, trying to drag a node in Unreal prints `Window [some number] has atom 282`, which is different from hover menus which have atom 284. Dragging an asset into the viewport (which is also broken) opens both a 282 and a 287 window. I guess 282 and 287 should also not have initial focus? I'm not sure how these numbers relate to the strings.

**Comment by vaxerski** [comment]
you get all the strings printed at the beginning

Search for `Atom`

One window can have multiple atoms. 
> opens both a 282 and a 287 

u sure its not one window with both?

**Comment by TheSunCat** [comment]
The 287 happens when it registers the drag-and-drop ended on the same panel, as that causes a popup menu to open there (Atom 287 is `_NET_WM_WINDOW_TYPE_POPUP_MENU`). Here for example I try to drag the ceiling light blueprint into the scene, but it instantly ends the dnd and shows this popup instead:
![image](https://user-images.githubusercontent.com/44881120/233831933-a7a675c4-0f84-4e16-b506-55497eb8dc0e.png)
The logs show a 282 (`_NET_WM_WINDOW_TYPE_NORMAL`) being created, then a 287 shortly after.

As for dragging nodes, it seems again a 282 is created, then instantly closed and the tooltip 284 (`_NET_WM_WINDOW_TYPE_TOOLTIP`) comes back:
```ini
$ tail -f /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log | grep -i -A3 -B3 Atom
[LOG] Registered signal for owner 55d383fa9110: 55d3843e5898 -> 55d383fa9118 (owner: CWLSurface)
[LOG] CWLSurface 55d383fa9110 called init()
[LOG] Registered signal for owner 55d383fa89c0: 55d384401288 -> 55d383fa8a90 (owner: CWindow)
[LOG] Window 55d383fa89c0 has atom 284
[LOG] Searching for matching rules for UnrealEditor (title: )
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 55d383fa89c0: 55d384401258 -> 55d383fa8c30 (owner: XWayland Window Late)
--
[LOG] Registered signal for owner 55d383fb63f0: 55d383faf2d8 -> 55d383fb63f8 (owner: CWLSurface)
[LOG] CWLSurface 55d383fb63f0 called init()
[LOG] Registered signal for owner 55d383fb5ca0: 55d383fa9e38 -> 55d383fb5d70 (owner: CWindow)
[LOG] Window 55d383fb5ca0 has atom 282
[LOG] Searching for matching rules for UnrealEditor (title: )
[LOG] Set keyboard focus to surface 55d383faeff0, with window name: 
[LOG] Window got assigned a surfaceTreeNode 0
--
[LOG] Registered signal for owner 55d383fb9140: 55d384408128 -> 55d383fb9148 (owner: CWLSurface)
[LOG] CWLSurface 55d383fb9140 called init()
[LOG] Registered signal for owner 55d383fb89f0: 55d384401288 -> 55d383fb8ac0 (owner: CWindow)
[LOG] Window 55d383fb89f0 has atom 284
[LOG] Searching for matching rules for UnrealEditor (title: )
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 55d383fb89f0: 55d384401258 -> 55d383fb8c60 (owner: XWayland Window Late)
```

I think Unreal is signalling that it's a drag and drop menu in an unusual way, as it never uses atom 285 (`_NET_WM_WINDOW_TYPE_DND`). Note that all the 284s it creates seem to be the tooltips that appear on hover of any element.

**Comment by BackupPlease** [comment]
Having this issue as well Unreal Engine is not usable on Hyprland at all 😢 i have to jump from hyprland to i3 when i want to work on my project

**Comment by TheSunCat** [comment]
So far I am using Unreal Engine in rootful XWayland (running i3 within it), but it is far from ideal.
I also get the huge lag spike that you get, pretty often when trying to use Unreal Engine on Hyprland. It indeed goes away after refocusing. There is also an issue with right click menus disappearing instantly, which is sometimes fixed by refocusing, but usually ends up requiring a restart. I am hoping that fixing the drag-and-drop behavior might help fix some of the other focus-related issues in Unreal Engine.

@vaxerski, is there anything we can do to help? I understand it is not possible for you to test with this program, but I am unsure what other information I can provide. The program works fine in Sway and i3, but Hyprland does not like it.

**Comment by vaxerski** [comment]
not really, it's just some quirks in hyprland's xwayland focus impl that I really can't be arsed to fix. X11 is such a terrible protocol that I don't fully even understand what the impl is meant to be like. There are 0 docs, the only reference is basically "how xorg does it" and I will not read Xorg's source and spend a full week just for this.

Feel free to monitor the behavior every month or so, maybe it improves one day. Or pester ue devs to release a working wayland version.

You can also try running ue4 in Xephyr instead of XWayland rootful, maybe that will help.

**Comment by BackupPlease** [comment]
I talked to one of the developers in Discord, and he said that the issue here is not Unreal, as it's working like it should in Sway i3 and KDE/gnome Wayland, but something in Hyprland Causes this  strange behaviors mentioned above

**Comment by TheSunCat** [comment]
Unreal Engine does not work natively on Wayland for me, on any compositor. There is no mouse input. This is the reason I have to run it in XWayland, which leads to the issues on Hyprland.
Does mouse input work for you with `SDL_VIDEODRIVER=wayland`?

**Comment by BackupPlease** [comment]
> Unreal Engine does not work natively on Wayland for me, on any compositor. There is no mouse input. This is the reason I have to run it in XWayland, which leads to the issues on Hyprland. Does mouse input work for you with `SDL_VIDEODRIVER=wayland`?

I didn't use that but i do have the mouse working like it should

**Comment by BackupPlease** [comment]
> > Unreal Engine does not work natively on Wayland for me, on any compositor. There is no mouse input. This is the reason I have to run it in XWayland, which leads to the issues on Hyprland. Does mouse input work for you with `SDL_VIDEODRIVER=wayland`?
> 
> I didn't use that but i do have the mouse working like it should

Again I don't use Xwayland I use Wayland...

**Comment by TheSunCat** [comment]
How are you launching Unreal Engine as a native Wayland app, without that env var? Are you sure it's not running in the embedded X11 server XWayland? You can check with `xeyes`, if the eyes follow the mouse while hovering over Unreal Engine.

**Comment by vaxerski** [comment]
or just `hyprctl clients` and checking the `xwayland` flag

**Comment by vaxerski** [comment]
check w/ 4ad03af544ba56399918642b609ed538764d1c0f

**Comment by TheSunCat** [comment]
Thanks for looking into this! Sadly it is still happening. When I start dragging, Unreal Engine gets unfocused for a very short moment, then refocused, and the drag gets instantly cancelled (as seen in my first post).

**Comment by deathbymanatee** [comment]
have you tried running UE5 with wine using lutris? i am having the same issues you've described and i'm thinking about just running it with those tools instead of using the native port, but i would like to know if you have any experience doing that and if it's even worth the time

**Comment by TheSunCat** [comment]
I would not expect a better experience as WINE apps have lots of issues on Hyprland (e.g Photoshop and various installers get a separate black window over them that I have to move out of the way to be able to  see and interact with the app, but snaps back to it after some time/moving the window).
I think the solution has to be either running Unreal as native Wayland, or fixing the Xwayland issue that causes this behavior in Hyprland. As Unreal does not seem to work on Wayland (no mouse input), fixing Xwayland on the Hyprland side seems to be the only option.

**Comment by deathbymanatee** [comment]
went ahead and tried it, it's surprisingly worse than running it in hyprland (as you predicted). it has its own set of issues that make it pretty much unusable

**Comment by TheSunCat** [comment]
I think this is related to focus again, as when this glitched state is entered, the viewport framerate is reduced to 1fps (which is intended to happen when Unreal is unfocused, I believe). Unfortunately some menus are inaccessible with the workaround I wrote about earlier, such as right clicking objects, because right-click-hold does not open the popup like left-click-hold does for the top menu.

**Comment by BackupPlease** [comment]
> I think this is related to focus again, as when this glitched state is entered, the viewport framerate is reduced to 1fps (which is intended to happen when Unreal is unfocused, I believe). Unfortunately some menus are inaccessible with the workaround I wrote about earlier, such as right clicking objects, because right-click-hold does not open the popup like left-click-hold does for the top menu.

About the rules you found Do they fix the FPS issues ?

**Comment by TheSunCat** [comment]
Nope, the issue where Unreal thinks it's unfocused (and thus reduces the framerate and breaks menus) is not fixed by these windowrules.

**Comment by theoparis** [comment]
I have managed to get the same issue, with prebuilt unreal engine 5.2 and Gentoo.

I tried running it by using `LD_PRELOAD=/usr/lib64/libSDL2.so ./Engine/Binaries/Linux/UnrealEditor` - but as mentioned earlier in this thread mouse input does not work and therefore I cannot create a project.

When I use tab and tab over to a dropdown and hit enter the window closes with the following in the logs:
```
xdg_wm_base@9: error 5: positioner object is not complete
```

![image](https://github.com/hyprwm/Hyprland/assets/11761863/a96b9b52-ebd1-4704-be18-cd2fe34f13de)

**Comment by BackupPlease** [comment]
Yeah this issue will never be fixed 450 opened cases what a buggy mess

**Comment by vaxerski** [comment]
sway has twice as many, gtk 4x as many. 

Besides, your comment is just bitching and adds nothing.

**Comment by TheSunCat** [comment]
Hyprland has 1,701 closed issues and the fastest developer response and fixes I've ever seen.
This issue sucks because X11 and it affects a 50GiB program that supposedly shouldn't even require X11 (it works on Wayland according to Google, but not on my machine). I don't think that makes Hyprland a buggy mess.

I do think the solution to this should be getting UE to run natively on Wayland as it claims to do, rather than fixing the legacy X11 version. I'll give it another shot later.

**Comment by BackupPlease** [comment]
> sway has twice as many, gtk 4x as many.
> 
> Besides, your comment is just bitching and adds nothing.

That's not how programming works. If a program has issues, you should learn from them and make a better product. Comparing the number of issues is pathetic and lame. And for the dude above me, the issue is with Hyprland and not with Unreal or Wayland. I tried five other managers, and none of them had this issue.


PS: Saying that a repo is a buggy mess is not bitching; it's just stating facts. This is what's wrong with programmers in this day and age: they think they can release a shit product and want people to thank them for it and be grateful.

**Comment by JustSimplyKyle** [comment]
Don't want to clutter this issue but you do realize that he's doing this all for free? You probably should be grateful for that. If he charges money then you might be able to complain stuff like this. Even if it IS a buggy mess, it's your own decision to use this compositor. I personally this blog post by the developer himself really well describes how is it like to maintain a popular FOSS project https://blog.vaxry.net/articles/2023-maintainingFoss.
And if you can provide a simple way to reproduce, vaxry would probably fix it in a matter of minutes.(which is really nice imo)
> Comparing the number of issues is pathetic and lame.

Yes so the saying "Yeah this issue will never be fixed 450 opened cases what a buggy mess" is also pointless, just saying the number issue isn't helping nor is it expressing any meaning.

**Comment by BackupPlease** [comment]
> Don't want to clutter this issue but you do realize that he's doing this all for free? You probably should be grateful for that. If he charges money then you might be able to complain stuff like this. Even if it IS a buggy mess, it's your own decision to use this compositor. I personally this blog post by the developer himself really well describes how is it like to maintain a popular FOSS project https://blog.vaxry.net/articles/2023-maintainingFoss. And if you can provide a simple way to reproduce, vaxry would probably fix it in a matter of minutes.(which is really nice imo)
> 
> > Comparing the number of issues is pathetic and lame.
> 
> Yes so the saying "Yeah this issue will never be fixed 450 opened cases what a buggy mess" is also pointless, just saying the number of issues isn't helping nor does it express any meaning.

Steps to reproduce the issue Did you even read what the issue is? All he has to do is literally download UE5 or UE4, and he will get this issue. It's a Hyprland issue, and whether it's  AMD or Nvidia hardware does not matter; it happens.

**Comment by JustSimplyKyle** [comment]
I wouldn't say downloading 50Gib program is a "simple" one. I'm not saying this isn't Hyprland issue. It mos likely is

**Comment by SchnozzleCat** [comment]
> Hyprland has 1,701 closed issues and the fastest developer response and fixes I've ever seen. This issue sucks because X11 and it affects a 50GiB program that supposedly shouldn't even require X11 (it works on Wayland according to Google, but not on my machine). I don't think that makes Hyprland a buggy mess.
> 
> I do think the solution to this should be getting UE to run natively on Wayland as it claims to do, rather than fixing the legacy X11 version. I'll give it another shot later.

I just built 5.3.1 from source with a manually compiled SDL2 that supports wayland, it still doesn't recognize mouse input. So unless someone over at Epic fixes this I don't think it is usable under wayland.

I also tested using sway and gnome-shell running under wayland, both of them have the same issue. Ideally they fix this so hyprland doesn't need to bother with a fix to how xwayland handles it.

**Comment by TheSunCat** [comment]
I can indeed reproduce the crash by forcing it to use my Wayland-enabled SDL2 system library. I think this issue is still very much relevant because at the moment it is impossible to use UE on Hyprland, while it does work on GNOME.

The issue with focus is the worst, where when opening a context menu and hovering over the options, the menu will suddenly disappear and UE will enter an "unfocused" state. The framerate then becomes ~1fps and keyboard input does not work until you manually refocus or resize it. I have to use the program every day for class and am affected by this.

**Comment by SchnozzleCat** [comment]
> I can indeed reproduce the crash by forcing it to use my Wayland-enabled SDL2 system library. I think this issue is still very much relevant because at the moment it is impossible to use UE on Hyprland, while it does work on GNOME.
> 
> The issue with focus is the worst, where when opening a context menu and hovering over the options, the menu will suddenly disappear and UE will enter an "unfocused" state. The framerate then becomes ~1fps and keyboard input does not work until you manually refocus or resize it. I have to use the program every day for class and am affected by this.

I've sent separate bug reports for both the missing Wayland support for SDL in pre-built 5.2 / 5.3 binaries and for the dropdown crash bug under sway / hyprland. I guess it's up to them to fix it now.

**Comment by blurskye** [comment]
damn, still not fixed, no workarounds or anything, xephyr doenst have gpu acceleration, so pointless, and making new window rules for unreal barely does anything

**Comment by ThatOneCalculator** [comment]
Out of sheer curiosity, have you tried [Epic Asset Manager](https://github.com/AchetaGames/Epic-Asset-Manager)? I doubt it would do much, but maybe it launches Unreal in a way that could help this.

**Comment by TheSunCat** [comment]
Yep I have, sadly no luck with it. Same issues as before, and works perfectly on GNOME like w/o EAM.

**Comment by TheSunCat** [comment]
After toying with it a lot, I seem to have a functional setup!!

Window rules:
```
windowrulev2=unset,class:^(UnrealEditor)$,title:^\w*$
windowrulev2=noinitialfocus,class:^(UnrealEditor)$,title:^\w*$
windowrulev2=suppressevent activate,class:^(UnrealEditor)$,title:^\w*$
```

In my short testing, I was able to drag nodes, open menus (WITHOUT going into the glitched focus mode), and drag and drop objects onto the scene.
Could someone else please confirm this works?

**Comment by blurskye** [comment]
@TheSunCat no that did nothing, i used this before... 
it doesnt do as much as i wanted it to,,,
just barely makes it useable, dragable, but at the end,, it is still broken
still cant use blurprints editor, cant navigate the menu as well

**Comment by aforsbom1** [comment]
Hello,

I've been trying to get UE to run natively under wayland/hyprland by building SDL2 with wayland support, while I got it to work and load as native a wayland application, there seems to be heaps of issues with the way the cursor and mouse events are being handled. Not sure if it's UE, SDL or Hyprland or all of them together being the cause of these issues, I might or might not delve deeper into that in the future, but for now I won't.

With that said, I patched some of the UE source and I think I've reached a state where it's working very well running UE under xwayland and hyprland. I can drag and drop, dropdown menus are working well and so on. (this is UE 5.4.4 btw, but might work for other versions as well)

But for others that might be intrested to try this out:

Apply the following windowrules:
```
windowrulev2 = noinitialfocus, class:(UnrealEditor)$
windowrulev2 = suppressevent activate, class:(UnrealEditor)$
```

Switch out SDL_SetWindowInputFocus to SDL_RaiseWindow in the UE source. (Specifically in LinuxWindow.cpp and LinuxApplication.cpp)

Patch here: https://gist.github.com/aforsbom1/ae810d01b69ab0b63eed42535dd03d30

**Comment by aforsbom1** [comment]
Running UE5.4.4 (xwayland) on Hyprland at commit: 1bc05b1f9fd55f2a7371082e6914622e4584ed54 with only the following windowrule seems to work fine.

```
windowrulev2 = noinitialfocus, class:(UnrealEditor)$
```

Keep in mind this is not in floating mode at all, including BP editor/other subwindows (opening all editor windows in the main window). I've seen some dropdowns behaving weird when parent windows are floating.

**Comment by jordicunillerarivera** [comment]
> After toying with it a lot, I seem to have a functional setup!!
> 
> Window rules:
> 
> ```
> windowrulev2=unset,class:^(UnrealEditor)$,title:^\w*$
> windowrulev2=noinitialfocus,class:^(UnrealEditor)$,title:^\w*$
> windowrulev2=suppressevent activate,class:^(UnrealEditor)$,title:^\w*$
> ```
> 
> In my short testing, I was able to drag nodes, open menus (WITHOUT going into the glitched focus mode), and drag and drop objects onto the scene. Could someone else please confirm this works?

This works for me, thanks a lot for your time trying to fix the dnd error, for now its the only problem i have with UE5.4.4, i didnt notice the 1 fps o flipering submenus erros(I have it in other apps, newer versions of hyprland fix it), im so glad that you post the fix, i really like Hyprland and the way you can customize it, but because of this i was thinking in try sway, they say that have better x11 apps compatibility but in comparisiong sway is ugly as hell hahaha.

PD: @vaxerski dont listen to trolls/haters, you are doing a magnificient work, keep going!!

**Comment by aforsbom1** [comment]
For what it's worth, I managed to get UE5.4.4 run in native wayland, with all dropdowns etc working fine. Things seem a bit more smooth as well.

Floating windows work fine with all dropdowns etc, but you will still need the window rule for **noinitialfocus**, so I imagine the odd issues with not being able to dnd without that rule is related to UEs integration with SDL and how it handles focus internally than anything else.

Just leaving this note here for anybody that wants to try it out as a native wayland application with dropdowns etc working properly:
- Compile SDL3
- Compile SDL2-compat

Starting UE, use the following variables (and make sure your system can find SDL3):
`SDL_DYNAMIC_API=/path/to/sdl-2-compat.so SDL_VIDEODRIVER=wayland /path/to/UnrealEditor`

**Comment by aforsbom1** [comment]
@jordicunillerarivera It looks like the SDL2-compat.so is properly loading at least. But, this makes use of SDL3, and if you check the logs here it seems that it cannot find SDL3. 

> Failed loading SDL3 library

So you're almost there. Wherever your SDL3 .so file is located, add the path to that folder in LD_LIBRARY_PATH env-var and run the command again. That should make it work.

**Comment by jordicunillerarivera** [comment]
Im blind, okay that work with that error, now im getting

wl_display#1: error 2: no memory
warning: queue 0x15f89090 destroyed while proxies still attached:
  wl_registry#52 still attached
ERROR: vkGetPhysicalDeviceSurfaceCapabilitiesKHR VK_ERROR_INITIALIZATION_FAILED

I have the last version of vulkan and a ton of memory for the wayland to work, I search info and i dont know what the heck its happening now, normally im very self resolutive, but this is killing me.
![image](https://github.com/user-attachments/assets/a2e435f8-d6c7-4700-9953-13ba1aafb7ad)

**Comment by jordicunillerarivera** [comment]
> @jordicunillerarivera It looks like the SDL2-compat.so is properly loading at least. But, this makes use of SDL3, and if you check the logs here it seems that it cannot find SDL3.
> 
> > Failed loading SDL3 library
> 
> So you're almost there. Wherever your SDL3 .so file is located, add the path to that folder in LD_LIBRARY_PATH env-var and run the command again. That should make it work.

Im blind, okay that work with that error, now im getting

wl_display#1: error 2: no memory
warning: queue 0x15f89090 destroyed while proxies still attached:
  wl_registry#52 still attached
ERROR: vkGetPhysicalDeviceSurfaceCapabilitiesKHR VK_ERROR_INITIALIZATION_FAILED

I have the last version of vulkan and a ton of memory for the wayland to work, I search info and i dont know what the heck its happening now, normally im very self resolutive, but this is killing me.
![image](https://github.com/user-attachments/assets/a2e435f8-d6c7-4700-9953-13ba1aafb7ad)

**Comment by aforsbom1** [comment]
@jordicunillerarivera Yeah, we're reaching unexplored territory whilst doing this I believe, and I'm not super experienced when it comes to everything around vulkan/sdl/wayland either.

But building SDL, I know you can check the cmake output if SDL has all the capabilities needed. For example if wayland or vulkan is available. I think it looks pretty much for what you have installed and available automatically, but you might need some vars to make sure that's the case.

Here's my cmake output for SDL reference:
```
-- Options:
--   SDL_ALSA                    (Wanted: ON): ON
--   SDL_ALSA_SHARED             (Wanted: ON): ON
--   SDL_ALTIVEC                 (Wanted: OFF): OFF
--   SDL_ARMNEON                 (Wanted: OFF): OFF
--   SDL_ARMSIMD                 (Wanted: OFF): OFF
--   SDL_ASAN                    (Wanted: OFF): OFF
--   SDL_ASSEMBLY                (Wanted: ON): ON
--   SDL_ASSERTIONS              (Wanted: auto): auto
--   SDL_AVX                     (Wanted: ON): ON
--   SDL_AVX2                    (Wanted: ON): ON
--   SDL_AVX512F                 (Wanted: ON): ON
--   SDL_BACKGROUNDING_SIGNAL    (Wanted: OFF): OFF
--   SDL_CCACHE                  (Wanted: OFF): OFF
--   SDL_CLANG_TIDY              (Wanted: OFF): OFF
--   SDL_CLOCK_GETTIME           (Wanted: ON): ON
--   SDL_COCOA                   (Wanted: OFF): OFF
--   SDL_DBUS                    (Wanted: ON): ON
--   SDL_DIRECTX                 (Wanted: OFF): OFF
--   SDL_DISABLE_INSTALL         (Wanted: OFF): OFF
--   SDL_DISABLE_UNINSTALL       (Wanted: OFF): OFF
--   SDL_DISKAUDIO               (Wanted: ON): ON
--   SDL_DUMMYAUDIO              (Wanted: ON): ON
--   SDL_DUMMYCAMERA             (Wanted: ON): ON
--   SDL_DUMMYVIDEO              (Wanted: ON): ON
--   SDL_EXAMPLES                (Wanted: OFF): OFF
--   SDL_EXAMPLES_LINK_SHARED    (Wanted: ON): OFF
--   SDL_FOREGROUNDING_SIGNAL    (Wanted: OFF): OFF
--   SDL_GCC_ATOMICS             (Wanted: ON): ON
--   SDL_GPU_DXVK                (Wanted: OFF): OFF
--   SDL_HIDAPI                  (Wanted: ON): ON
--   SDL_HIDAPI_JOYSTICK         (Wanted: ON): ON
--   SDL_HIDAPI_LIBUSB           (Wanted: ON): OFF
--   SDL_HIDAPI_LIBUSB_SHARED    (Wanted: ON): OFF
--   SDL_IBUS                    (Wanted: ON): OFF
--   SDL_INSTALL_TESTS           (Wanted: OFF): OFF
--   SDL_JACK                    (Wanted: ON): OFF
--   SDL_JACK_SHARED             (Wanted: ON): OFF
--   SDL_KMSDRM                  (Wanted: ON): ON
--   SDL_KMSDRM_SHARED           (Wanted: ON): ON
--   SDL_LASX                    (Wanted: OFF): OFF
--   SDL_LIBC                    (Wanted: ON): ON
--   SDL_LIBICONV                (Wanted: OFF): OFF
--   SDL_LIBUDEV                 (Wanted: ON): ON
--   SDL_LSX                     (Wanted: OFF): OFF
--   SDL_METAL                   (Wanted: OFF): OFF
--   SDL_MMX                     (Wanted: ON): ON
--   SDL_OFFSCREEN               (Wanted: ON): ON
--   SDL_OPENGL                  (Wanted: ON): ON
--   SDL_OPENGLES                (Wanted: ON): ON
--   SDL_OSS                     (Wanted: OFF): OFF
--   SDL_PIPEWIRE                (Wanted: ON): ON
--   SDL_PIPEWIRE_SHARED         (Wanted: ON): ON
--   SDL_PTHREADS                (Wanted: ON): ON
--   SDL_PTHREADS_SEM            (Wanted: ON): ON
--   SDL_PULSEAUDIO              (Wanted: ON): ON
--   SDL_PULSEAUDIO_SHARED       (Wanted: ON): ON
--   SDL_RENDER_D3D              (Wanted: OFF): OFF
--   SDL_RENDER_D3D11            (Wanted: OFF): OFF
--   SDL_RENDER_D3D12            (Wanted: OFF): OFF
--   SDL_RENDER_GPU              (Wanted: ON): ON
--   SDL_RENDER_METAL            (Wanted: ON): OFF
--   SDL_RENDER_VULKAN           (Wanted: ON): ON
--   SDL_ROCKCHIP                (Wanted: OFF): OFF
--   SDL_RPATH                   (Wanted: ON): ON
--   SDL_RPI                     (Wanted: OFF): OFF
--   SDL_SNDIO                   (Wanted: ON): OFF
--   SDL_SNDIO_SHARED            (Wanted: ON): OFF
--   SDL_SSE                     (Wanted: ON): ON
--   SDL_SSE2                    (Wanted: ON): ON
--   SDL_SSE3                    (Wanted: ON): ON
--   SDL_SSE4_1                  (Wanted: ON): ON
--   SDL_SSE4_2                  (Wanted: ON): ON
--   SDL_SYSTEM_ICONV            (Wanted: ON): ON
--   SDL_TESTS                   (Wanted: OFF): OFF
--   SDL_TESTS_LINK_SHARED       (Wanted: ON): OFF
--   SDL_VIRTUAL_JOYSTICK        (Wanted: ON): ON
--   SDL_VIVANTE                 (Wanted: OFF): OFF
--   SDL_VULKAN                  (Wanted: ON): ON
--   SDL_WASAPI                  (Wanted: OFF): OFF
--   SDL_WAYLAND                 (Wanted: ON): ON
--   SDL_WAYLAND_LIBDECOR        (Wanted: ON): ON
--   SDL_WAYLAND_LIBDECOR_SHARED (Wanted: ON): ON
--   SDL_WAYLAND_SHARED          (Wanted: ON): ON
--   SDL_X11                     (Wanted: ON): ON
--   SDL_X11_SHARED              (Wanted: ON): ON
--   SDL_X11_XCURSOR             (Wanted: ON): ON
--   SDL_X11_XDBE                (Wanted: ON): ON
--   SDL_X11_XFIXES              (Wanted: ON): OFF
--   SDL_X11_XINPUT              (Wanted: ON): OFF
--   SDL_X11_XRANDR              (Wanted: ON): ON
--   SDL_X11_XSCRNSAVER          (Wanted: ON): OFF
--   SDL_X11_XSHAPE              (Wanted: ON): ON
--   SDL_XINPUT                  (Wanted: OFF): OFF
```

Some more information:
- Hyprland at https://github.com/hyprwm/Hyprland/commit/1bc05b1f9fd55f2a7371082e6914622e4584ed54
- SDL3 at https://github.com/libsdl-org/SDL/commit/88a01fbc964fbea1203071ea3ca2c6f799d4f571 
- SDL2-compat at https://github.com/libsdl-org/sdl2-compat/commit/c40e5fb3952d8c79e657c09bf55b0e8d06750e18

And a small recording showing it running wayland native in hyprland:
[2024-09-20 23-39-46.webm](https://github.com/user-attachments/assets/490bad80-4ade-4cbc-a8b7-6198e816692d)

**Comment by aforsbom1** [comment]
@jordicunillerarivera You could also try just compiling the latest SDL2 release and using SDL_DYNAMIC_API to link that output in, but when I did so myself, dropdowns were not working except when using the keyboard to navigate them. Might work for you though :shrug:

**Comment by jordicunillerarivera** [comment]
@aforsbom1 okaay this feels so wrong but it works, if I change wayland for x11 on the SDL_VIDEODRIVER parameter, it launches and work well, there is a framedrop when placing an object for the first time to the scene and the search box on blueprint dont capture the keyboard.

for now i can use the normal UE5 the majority of time and when i need to put objects in scene i will use x11 UE5 i supose, better than nothing.

**Comment by aforsbom1** [comment]
@jordicunillerarivera check on startup of UE for the initialize SDL line. Around there you should find more information about which SDL lib you're using.

I think by default it will use x11 so you shouldnt need to explicitly add it as an env, but depending on which SDL youre using you might see different results in the behaviour. (using your own compiled version vs the bundled ue version).

There's also the useful WAYLAND_DEBUG=1 env you can add for more verbosity on whats going on, but you might need to grep because its printing info every frame (and dont forget 2>&1). With that however, you can see exactly how UE interacts with wayland. If its native wayland that is.

**Comment by aforsbom1** [comment]
Some further testing using sdl2-compat is that it gives me some bad window events. Currently investigating that issue and I'll post here if I find a solution to it, otherwise I suggest using XWAYLAND where everything seems to work okay as well, albeit with some quirky mouse pointer movement at times.

**Comment by qmmp123** [comment]
I had the same issue but fixed it with window rules from @TheSunCat
@TheSunCat Thanks for the windowrules. @vaxerski Thanks for hyprland.

**Comment by blurskye** [comment]
@qmmp123 is it really fixed? it might appear fixed for a short while in my exp, until it doesnt, i had tested a long while ago in hyprland, maybe hyprland got another update not sure

**Comment by 3ibod** [comment]
It's strange that no one complains about the panning function. I hold down the button and move the cursor, and after some random time the ue5 cursor appears directly in the place where I initially clicked and panning begins.
I noticed that if there are 2 detached ue5 windows and we focus their view with the cursor, then panning will work instantly, but only once before focusing again on another ue5 window

https://github.com/user-attachments/assets/cc728d70-e357-4808-8fac-54db101022ca

**Comment by WhitleyStriber** [comment]
> Running UE5.4.4 (xwayland) on Hyprland at commit: [1bc05b1](https://github.com/hyprwm/Hyprland/commit/1bc05b1f9fd55f2a7371082e6914622e4584ed54) with only the following windowrule seems to work fine.
> 
> ```
> windowrulev2 = noinitialfocus, class:(UnrealEditor)$
> ```
> 
> Keep in mind this is not in floating mode at all, including BP editor/other subwindows (opening all editor windows in the main window). I've seen some dropdowns behaving weird when parent windows are floating.

Works on 5.1.1. Thank you so much you are the best.

**Comment by 3ibod** [comment]
> It's strange that no one complains about the panning function. I hold down the button and move the cursor, and after some random time the ue5 cursor appears directly in the place where I initially clicked and panning begins. I noticed that if there are 2 detached ue5 windows and we focus their view with the cursor, then panning will work instantly, but only once before focusing again on another ue5 window
> 
>  recording_2025-01-03_07.23.03.mp4

Does anyone have any ideas for workarounds or any temporary solutions other than switching to x11 or using the .exe version?

**Comment by Rabcor** [comment]
> > windowrulev2 = noinitialfocus, class:(UnrealEditor)$


This does fix OP's specific issue so the issue should probably be closed, there are some other problems (like crashes) but they might not be hyprland specific.

**Comment by HenrySmalstig** [comment]
@jordicunillerarivera So, I've had the same issue with Unreal in Hyprland where I can't rotate and scale objects, it also means I can't use the landscape painting mode. I've found that those things work when using KDE, which means the issue definitely stems from Hyprland in some way. I tried the fixes you and @aforsbom1 were working through, and Unreal runs, but I'm unable to click anything when I use it. Going to keep trying things and will add if I find a fix, just wanted to ask if the rotation and scale worked with the fixes?

**Comment by WhitleyStriber** [comment]
Has anyone tested Debug mode? Debug Mode in Rider causes me to lose my mouse on all windows with that rule.

**Comment by HenrySmalstig** [comment]
> [@jordicunillerarivera](https://github.com/jordicunillerarivera) So, I've had the same issue with Unreal in Hyprland where I can't rotate and scale objects, it also means I can't use the landscape painting mode. I've found that those things work when using KDE, which means the issue definitely stems from Hyprland in some way. I tried the fixes you and [@aforsbom1](https://github.com/aforsbom1) were working through, and Unreal runs, but I'm unable to click anything when I use it. Going to keep trying things and will add if I find a fix, just wanted to ask if the rotation and scale worked with the fixes?

Updating this. I've managed to get mouse input working when launching Unreal in wayland, however it crashes when I attempt to use dropdowns. Also, mouse input strangely only works when `SDL_DYNAMIC_API=/path/to/sdl2-compt.so` points to one of the `sdl2-compat.so` versions with numbers after, ie. `sdl2-compat.so.0`.

**Comment by Myphz** [comment]
> The drag & drop works flawlessy with:
> 
> windowrulev2 = noinitialfocus, class:(UnrealEditor)$
> 
> But all the context menus (right click, ...) are not interactable for me. They open, and stay open, but I am not able to focus on them to click on the options. Anyone has a solution for this, or a way to debug this behaviour to figure out how to fix it?

It's fixed with the latest release! Seems like everything works fine

**Comment by vaxerski** [comment]
Hello there!

This issue has been closed, as we are moving from issues to discussions. More about this can be found [here](https://wiki.hyprland.org/Contributing-and-Debugging/Issue-Guidelines/) and in #9854.

Firstly, please make sure this issue is still relevant in latest Hyprland. If so, we ask you to open a [discussion](https://github.com/hyprwm/Hyprland/discussions) (please read the discussion guidelines first, in the pinned post)

Thank you for your understanding!

**Comment by Rabcor** [comment]
> The drag & drop works flawlessy with:
> 
> windowrulev2 = noinitialfocus, class:(UnrealEditor)$
> 
> But all the context menus (right click, ...) are not interactable for me. They open, and stay open, but I am not able to focus on them to click on the options. Anyone has a solution for this, or a way to debug this behaviour to figure out how to fix it?

I worked this out, the trick is to keep to using only one window,  like this:

![Image](https://github.com/user-attachments/assets/8e4d369a-f068-4204-8e17-72f33879c71c)

If it's in the main window right clicking and messing with the blueprint context menus works fine. The reason being that the window needs to be in tiling mode for the context menu stuff to work when this option is on for some raeson, and having multiple tiled windows makes the engine crash happy.

On the wayland (to run on wayland native use `SDL_VIDEODRIVER=wayland`)  side it's more stable than it was but still tends to crash on certain popups;
`libUnrealEditor-ApplicationCore.so!Wayland_ReleasePopup [/SDL-gui-backend/src/video/wayland/SDL_waylandwindow.c:1506]`

It also has a lot of weird probably related lag spikes.

**Comment by tedvas** [comment]
I found this fix that worked for me here:https://github.com/hyprwm/Hyprland/issues/2127/partials/load_more?after_cursor=Y3Vyc29yOnYyOpPPAAABiGnVDDAAqjE1Njc1OTMyOTk%3D&before_cursor=Y3Vyc29yOnYyOpPPAAABjfYz5ogAqjE5NzE3NTU5Njg%3D


You just add this to windowrules.

# Don't focus Unreal Engine's untitled popups
windowrulev2=unset,class:^(UnrealEditor)$,title:^\w*$
windowrulev2=noinitialfocus,class:^(UnrealEditor)$,title:^\w*$
windowrulev2=noanim,class:^(UnrealEditor)$,title:^\w*$

**Comment by Saladin1812** [comment]
> I found this fix that worked for me.
> 
> You just add this to windowrules.
> 
> windowrulev2=unset,class:^(UnrealEditor)$,title:^\w*$ windowrulev2=noinitialfocus,class:^(UnrealEditor)$,title:^\w*$ windowrulev2=noanim,class:^(UnrealEditor)$,title:^\w*$

All this fixes object drags in file explorer.. still unable to drag panes arround.. However changed the setting inside unreal to open asset in Previous Docked + Main Window. In order for it to be less annoying. 
But still can't drag to Scale or Rotate, 

Setting SDL driver to wayland crashes the engine. So still kinda out of luck.

**Comment by Saladin1812** [comment]
Also confirming with Cosmic DE on nix OS.. this seems fine. It is able to handle the Unreal Engine window without any issues. It also has the pane dragging issue but I am simply using the engine setting to get around that.

**Comment by Rabcor** [comment]
Messing with this again now, everything from [before](https://github.com/hyprwm/Hyprland/issues/2127#issuecomment-2849008813) still applies, but it seems to be behaving worse than last time on wayland (maybe because new engine version), better on xwayland though

I figured out the lag spikes issue btw, turns out it had nothing to do with wayland, probably not even anything to do with linux since windows users experience it too, if I go to plugins and **disable the TCP and UDP messaging plugins**, the lag spikes go away and the engine runs smooth as silk.


# On `SDL_VIDEODRIVER=wayland`

When running with `SDL_VIDEODRIVER=wayland` disabling high-dpi support and setting application scale to 1 gives me the best results, when high-dpi support is on the editor seems to crash a lot more for me. Luckily the scale option works regardless of whether it's on or off, just on a different scale.

It still segfaults quite frequently when flipping through dropdown menu items:

<details>

```
Caught signal 11 Segmentation fault

libUnrealEditor-ApplicationCore.so!Wayland_ShowWindow [/SDL-gui-backend/src/video/wayland/SDL_waylandwindow.c:1344]
libUnrealEditor-ApplicationCore.so!SDL_ShowWindow_REAL [/SDL-gui-backend/src/video/SDL_video.c:2530]
libUnrealEditor-ApplicationCore.so!SDL_CreateWindow_REAL [/SDL-gui-backend/src/video/SDL_video.c:1837]
libUnrealEditor-ApplicationCore.so!FLinuxWindow::Initialize(FLinuxApplication*, TSharedRef<FGenericWindowDefinition, (ESPMode)1> const&, TSharedPtr<FLinuxWindow, (ESPMode)1> const&, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/ApplicationCore/Private/Linux/LinuxWindow.cpp:238]
libUnrealEditor-ApplicationCore.so!FLinuxApplication::InitializeWindow(TSharedRef<FGenericWindow, (ESPMode)1> const&, TSharedRef<FGenericWindowDefinition, (ESPMode)1> const&, TSharedPtr<FGenericWindow, (ESPMode)1> const&, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/ApplicationCore/Private/Linux/LinuxApplication.cpp:163]
libUnrealEditor-Slate.so!FSlateApplication::MakeWindow(TSharedRef<SWindow, (ESPMode)1>, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:1948]
libUnrealEditor-Slate.so!FSlateApplication::AddWindowAsNativeChild(TSharedRef<SWindow, (ESPMode)1>, TSharedRef<SWindow, (ESPMode)1>, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:2208]
libUnrealEditor-Slate.so!FMenuStack::PushNewWindow(TSharedPtr<IMenu, (ESPMode)1>, FMenuStack::FPrePushResults const&, bool, int) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/Application/MenuStack.cpp:532]
libUnrealEditor-Slate.so!FMenuStack::PushInternal(TSharedPtr<IMenu, (ESPMode)1> const&, TSharedRef<SWidget, (ESPMode)1> const&, FSlateRect, FPopupTransitionEffect const&, bool, EShouldThrottle, bool, bool, int) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/Application/MenuStack.cpp:350]
libUnrealEditor-Slate.so!FMenuStack::Push(FWidgetPath const&, TSharedRef<SWidget, (ESPMode)1> const&, UE::Slate::FDeprecateVector2DParameter const&, FPopupTransitionEffect const&, bool, UE::Slate::FDeprecateVector2DParameter const&, TOptional<EPopupMethod>, bool, bool, int) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/Application/MenuStack.cpp:272]
libUnrealEditor-Slate.so!FSlateApplication::PushMenu(TSharedRef<SWidget, (ESPMode)1> const&, FWidgetPath const&, TSharedRef<SWidget, (ESPMode)1> const&, UE::Slate::FDeprecateVector2DParameter const&, FPopupTransitionEffect const&, bool, UE::Slate::FDeprecateVector2DParameter const&, TOptional<EPopupMethod>, bool, int) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:2231]
libUnrealEditor-Slate.so!SMenuAnchor::SetIsOpen(bool, bool, int) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Widgets/Input/SMenuAnchor.cpp:375]
libUnrealEditor-Slate.so!SMenuEntryBlock::OnMouseEnter(FGeometry const&, FPointerEvent const&) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/MultiBox/SMenuEntryBlock.cpp:1410]
libUnrealEditor-Slate.so!FSlateApplication::RoutePointerMoveEvent(FWidgetPath const&, FPointerEvent const&, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:5705]
libUnrealEditor-Slate.so!FSlateApplication::ProcessMouseMoveEvent(FPointerEvent const&, bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:6196]
libUnrealEditor-Slate.so!FSlateApplication::OnMouseMove() [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Slate/Private/Framework/Application/SlateApplication.cpp:6117]
libUnrealEditor-ApplicationCore.so!FLinuxApplication::ProcessDeferredMessage(SDL_Event) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/ApplicationCore/Private/Linux/LinuxApplication.cpp:393]
libUnrealEditor-ApplicationCore.so!FLinuxPlatformApplicationMisc::PumpMessages(bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/ApplicationCore/Private/Linux/LinuxApplication.cpp:237]
UnrealEditor!FEngineLoop::Tick() [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Launch/Private/LaunchEngineLoop.cpp:5548]
UnrealEditor!GuardedMain(char16_t const*) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Launch/Private/Launch.cpp:60]
libUnrealEditor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:323]
libc.so.6!UnknownFunction(0x27b8a)
libc.so.6!__libc_start_main(+0x8a)
UnrealEditor!_start [/opt/unreal-engine/Engine/Binaries/Linux/UnrealEditor:-1]
```

</details>

I think it's the tooltip that's causing it, you can disable tooltips by typing `Slate.EnableTooltips 0 `in the console. It seems to make the editor a lot more resilient to crashes but it can still crash if you flip too fast through the menuitems, particularly the ones that have submenus since those will generate new windows like the tooltips do.

Allowing it to render when unfocused (when you're in other workspaces) with `windowrule = renderunfocused, initialTitle:^(UnrealEditor)$` seems to also prevent some crashes.

Also sometimes you cannot click on the yes/no button for popup prompts. Such prompts often open as tiny like 1x10px windows when using the wayland driver so to prevent that I set something like `windowrule = minsize 450 130,initialClass:^(UnrealEditor)$` to ensure they're at least properly visible.

I also sometimes seem to crash when trying to create nodes in blueprints, I have no easy answer for this issue, seems to be an issue with libffi.so

<details>

```
Caught signal 11 Segmentation fault

libUnrealEditor-ApplicationCore.so!pointer_handle_button [/SDL-gui-backend/src/video/wayland/SDL_waylandevents.c:601]
libffi.so.8!UnknownFunction(0x83fd)
libffi.so.8!UnknownFunction(0x4a5c)
libffi.so.8!ffi_call(+0x13d)
libwayland-client.so.0!UnknownFunction(0x49af)
libwayland-client.so.0!UnknownFunction(0x52a8)
libwayland-client.so.0!wl_display_dispatch_queue_pending(+0x6a)
libUnrealEditor-ApplicationCore.so!Wayland_PumpEvents [/SDL-gui-backend/src/video/wayland/SDL_waylandevents.c:380]
libUnrealEditor-ApplicationCore.so!SDL_PumpEventsInternal [/SDL-gui-backend/src/events/SDL_events.c:918]
libUnrealEditor-ApplicationCore.so!SDL_PollEvent_REAL [/SDL-gui-backend/src/events/SDL_events.c:1093]
libUnrealEditor-ApplicationCore.so!FLinuxPlatformApplicationMisc::PumpMessages(bool) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/ApplicationCore/Private/Linux/LinuxPlatformApplicationMisc.cpp:440]
UnrealEditor!FEngineLoop::Tick() [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Launch/Private/LaunchEngineLoop.cpp:5548]
UnrealEditor!GuardedMain(char16_t const*) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Launch/Private/Launch.cpp:60]
libUnrealEditor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [/mnt/horde/++UE5/Sync/Engine/Source/./Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:323]
libc.so.6!UnknownFunction(0x27b8a)
libc.so.6!__libc_start_main(+0x8a)
UnrealEditor!_start [/opt/unreal-engine/Engine/Binaries/Linux/UnrealEditor:-1]
```

</details>


But right now (and this is almost certainly a hyprland bug) the cursor selection when selecting items in a dropdown menu is off again, wasn't so the last time I tested, also this is on git build from yesterday not stable.

<details>
<summary> Screenshot of selection issue</summary>
The mouse is unfortunately not visible, but the top-left corner of the popup tooltip is where the cursor actually is, e.g. it's one menu item dow from the selected item.

![Image](https://github.com/user-attachments/assets/6e2cf0f3-d4f2-43e9-89dd-f1e628d08994)
</details>

# On Xwayland

Things have improved on xwayland with unreal, everything works pretty much fine if it weren't for a few freezes (as in UE just locks up, have to kill it) it'd be solid now.

 `windowrule = renderunfocused, initialTitle:^(UnrealEditor)$` seems to be overall good to have both to prevent crashes and to make sure the engine completes stuff in the background when you're on another workspace.

I also use `windowrule = noinitialfocus,class:^(UnrealEditor)$,title:^\w*$`  for the drag and drop thing.

a lot of things (like visual scripting/blueprints editor) only work from a tiled window since floating window seems to break context menus.

**Comment by Saladin1812** [comment]
> Messing with this again now, everything from [before](https://github.com/hyprwm/Hyprland/issues/2127#issuecomment-2849008813) still applies, but it seems to be behaving worse than last time on wayland (maybe because new engine version), better on xwayland though
> 
> I figured out the lag spikes issue btw, turns out it had nothing to do with wayland, probably not even anything to do with linux since windows users experience it too, if I go to plugins and **disable the TCP and UDP messaging plugins**, the lag spikes go away and the engine runs smooth as silk.
> 
> # On `SDL_VIDEODRIVER=wayland`
> When running with `SDL_VIDEODRIVER=wayland` disabling high-dpi support and setting application scale to 1 gives me the best results, when high-dpi support is on the editor seems to crash a lot more for me. Luckily the scale option works regardless of whether it's on or off, just on a different scale.
> 
> It still segfaults quite frequently when flipping through dropdown menu items:
> 
> I think it's the tooltip that's causing it, you can disable tooltips by typing `Slate.EnableTooltips 0 `in the console. It seems to make the editor a lot more resilient to crashes but it can still crash if you flip too fast through the menuitems, particularly the ones that have submenus since those will generate new windows like the tooltips do.
> 
> Allowing it to render when unfocused (when you're in other workspaces) with `windowrule = renderunfocused, initialTitle:^(UnrealEditor)$` seems to also prevent some crashes.
> 
> Also sometimes you cannot click on the yes/no button for popup prompts. Such prompts often open as tiny like 1x10px windows when using the wayland driver so to prevent that I set something like `windowrule = minsize 450 130,initialClass:^(UnrealEditor)$` to ensure they're at least properly visible.
> 
> I also sometimes seem to crash when trying to create nodes in blueprints, I have no easy answer for this issue, seems to be an issue with libffi.so
> 
> But right now (and this is almost certainly a hyprland bug) the cursor selection when selecting items in a dropdown menu is off again, wasn't so the last time I tested, also this is on git build from yesterday not stable.
> 
> Screenshot of selection issue
> # On Xwayland
> Things have improved on xwayland with unreal, everything works pretty much fine if it weren't for a few freezes (as in UE just locks up, have to kill it) it'd be solid now.
> 
> `windowrule = renderunfocused, initialTitle:^(UnrealEditor)$` seems to be overall good to have both to prevent crashes and to make sure the engine completes stuff in the background when you're on another workspace.
> 
> I also use `windowrule = noinitialfocus,class:^(UnrealEditor)$,title:^\w*$` for the drag and drop thing.
> 
> a lot of things (like visual scripting/blueprints editor) only work from a tiled window since floating window seems to break context menus.

On Xwayland the default way pretty much, I am also unable to rotate something in the viewport using either the handles, or dragging on the values. And this is indeed a Hyprland issue. Doesn't happen on Cosmic for me.

**Comment by drone1** [comment]
I'll put this here in case anyone else finds it useful:

```
# Disable window focus changes during drags
# For me, this fixed dragging connections from sockets in the Blueprint Editor causing the connection to drop
# immediately where the mouse is and add a new node (popping up the new node popup/selector). This made
# it nearly impossible to drag connections to other inputs/outputs.
windowrulev2 = nofocus, class:^(UnrealEditor)$,floating:0
windowrulev2 = noinitialfocus, class:^(UnrealEditor)$
```

**Comment by WhitleyStriber** [comment]
Hyprland git breaks the windowrules. 

invalid field noinitialfocus: missing a value
invalid field noanim: missing a value
invalid field renderunfocused: missing a value

Please don't break this. Hyprland doesn't work well with UE5 as it is.

**Comment by tannerellen** [comment]
> Hyprland git breaks the windowrules.
> 
> invalid field noinitialfocus: missing a value invalid field noanim: missing a value invalid field renderunfocused: missing a value
> 
> Please don't break this. Hyprland doesn't work well with UE5 as it is.

Window rule syntax has changed in git. You should follow the breaking changes tracker:
[#8424](https://github.com/hyprwm/Hyprland/issues/8424)

Specifically you will need to update all your window rules to take advantage of the new syntax:
https://wiki.hypr.land/Configuring/Window-Rules/

A user on discord made a tool for migrating from the old style to the new one:
https://itsohen.github.io/hyprrulefix/

As with anything make sure you have a good backup of your config before making changes. You could always install the release packages instead of git but that is just going to delay the inevitable as the next release will most likely contain the new window rule syntax.

**Comment by Rabcor** [comment]
Here we go again. It's easier to run on hyprland now since it defaults to SDL3 which natively supports wayland, it will run out of the box now, but it's got problems.

Issues:
- [Tooltips and most context menus always open at the center of the screen ](https://github.com/hyprwm/Hyprland/discussions/12729)
- In some context menus (File, Edit, Windows) it reads the cursor as if it's above and to the left of where it really is.
- [Windows/Dialogs within the editor tend to open at the minimum allowed size](https://github.com/hyprwm/Hyprland/discussions/13293) (if unset, 1x1px or so). Context menus and tooltips seem unaffected. (sway does not have this problem)
- The mouse cursor is not detected at all within many context menus. (Keyboard navigation still works in them though) (in sway the problem was even worse)
- [Tooltip rendering issues](https://github.com/hyprwm/Hyprland/discussions/13294) (sway does not have this problem)
- Tooltips can still lead to freezes (if not crashes), they can be disabled with `Slate.EnableTooltips 0 `, possibly related to above.
- This list is not truly exhaustive, I only played around for like an hour

To force usage of Xwayland, set env `SDL_VIDEO_DRIVER=x11`
Issues Xwayland:
- [When trying to click on buttons](https://github.com/hyprwm/Hyprland/discussions/13292), the mouse cursor icon changes to the one used to symbolize resize actions and the buttons don't get pressed. This does not happen if you change workspace, then change back to the workspace of the editor and click the button with your first click, that first click will always reliably work but your next click won't. Thsi doesn't happen 100% of the time, but it does happen about 90% of the time. Content browser is affected. (Sway does not have this problem)
- I couldn't find more because the above issue makes the app practically unusable.
