### ISSUE TITLE
Latest release causes screen flickering on 3840x1600 monitor @ 144hz via usb-c

### ISSUE THREAD

**Issue by fraschm1998** [hyprwm/Hyprland#2698]
https://github.com/hyprwm/Hyprland/assets/54919428/d4ac3df4-f420-4080-a2c8-4d9119e6e80c

**Comment by vaxerski** [comment]
`git bisect` pls, looks like a wlroots issue if anything

**Comment by MonstrousOgre** [comment]
I'm having the same issue over HDMI. I did a git bisect and ended up with

```
b540d28849c1691236ee8b0572f6a694b82dbbbf is the first bad commit
commit b540d28849c1691236ee8b0572f6a694b82dbbbf
Author: vaxerski <vaxry@vaxry.net>
Date:   Wed May 31 16:09:25 2023 +0200

    deps: update wlroots

 subprojects/wlroots | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

Looks like it is a wlroots issue. Considering it was well over a month ago, I'm surprised no one using `hyprland-nvidia-git` reported anything.

**Comment by MonstrousOgre** [comment]
I'm having the same issue over HDMI. I did a git bisect and ended up with

```
b540d28849c1691236ee8b0572f6a694b82dbbbf is the first bad commit
commit b540d28849c1691236ee8b0572f6a694b82dbbbf
Author: vaxerski <vaxry@vaxry.net>
Date:   Wed May 31 16:09:25 2023 +0200

    deps: update wlroots

 subprojects/wlroots | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

Looks like it is a wlroots issue. Considering it was well over a month ago, I'm surprised no one using the git packages reported anything.

**Comment by fraschm1998** [comment]
> I'm having the same issue over HDMI. I did a git bisect and ended up with
> 
> ```
> b540d28849c1691236ee8b0572f6a694b82dbbbf is the first bad commit
> commit b540d28849c1691236ee8b0572f6a694b82dbbbf
> Author: vaxerski <vaxry@vaxry.net>
> Date:   Wed May 31 16:09:25 2023 +0200
> 
>     deps: update wlroots
> 
>  subprojects/wlroots | 2 +-
>  1 file changed, 1 insertion(+), 1 deletion(-)
> ```
> 
> Looks like it is a wlroots issue. Considering it was well over a month ago, I'm surprised no one using the git packages reported anything.

I just reported the issue to wlroots: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3687

**Comment by nadir-yttrium** [comment]
[flickering.webm](https://github.com/hyprwm/Hyprland/assets/23151917/e7731c2a-347a-4b95-a64d-007b570185e7)

I converted the video to webm because it didn't play for me either. Hope that helps.

**Comment by MonstrousOgre** [comment]
So the flickering seems to have decreased for me as of 0.27.2

It's still happening during the animations while switching workspaces but not otherwise. It's also not very noticable now.

**Comment by DasIschBims** [comment]
I just tested installing 0.27.2 (hyprland-nvidia) and it seems like the issue has been resolved, at least on my machine.

**Comment by harshkhandeparkar** [comment]
> I just tested installing 0.27.2 (hyprland-nvidia) and it seems like the issue has been resolved, at least on my machine.

Resolved for me too on `hyprland-nvidia` 0.27.2-1 on Arch. I have a 1650ti and use `nvidia-open` drivers.

**Comment by jchhuang-tech** [comment]
> So the flickering seems to have decreased for me as of 0.27.2
> 
> It's still happening during the animations while switching workspaces and tiling new windows, but not otherwise. It's also not very noticable now.

Same on nvidia proprietary driver. Still some flickering during window/workspace animations but it's usable now.

**Comment by MonstrousOgre** [comment]
> Actually not just during animations. There's flickering in Firefox when scrolling. It happens when it's the only window in the workspace.

I'm experiencing the same. I also see occasional screen tearing while watching videos

**Comment by jchhuang-tech** [comment]
So the current situation for me is, as I have an igpu, this issue doesn't seem to occur if I run Hyprland with `WLR_DRM_DEVICES=/dev/dri/card0 Hyprland` (meaning not using igpu but nvidia only), but the flickering still exists if I just run `Hyprland`

**Comment by MonstrousOgre** [comment]
> So the current situation for me is, as I have an igpu, this issue doesn't seem to occur if I run Hyprland with `WLR_DRM_DEVICES=/dev/dri/card0 Hyprland` (meaning not using igpu but nvidia only), but the flickering still exists if I just run `Hyprland`

Same thing is still happening to me. It doesn't happen when I use only nvidia.

It's not too much of an issue since it only happens during window animations and is not too noticeable, but I'd prefer it didn't happen

**Comment by MonstrousOgre** [comment]
It seems to be fixed as of 0.34.0, even when using both intel + nvidia

**Comment by vaxerski** [comment]
closing then
