### ISSUE TITLE
Floating windows during a slide animation don't have proper damage tracking

### ISSUE THREAD

**Issue by neilking01** [hyprwm/Hyprland#3514]
### Hyprland Version

0.30.0-1

### Bug or Regression?

Bug

### Description

See [video](https://www.reddit.com/r/hyprland/comments/171m6ws/damage_tracking_2_dual_screen_glitch_when). I don't get this glitch with damage_tracking set to 0 or 1. However, 2 is more energy efficient. 0 has my laptop almost burning to the touch when idle with the GPU at 70%+ caused by the Hyprland process. With 2, its down to around 10%. Are there any fixes/workarounds for this? This happens when switching to a workspace that has a window overlapping into the 2nd screen and animations are on.

### How to reproduce

1. set the following animation settings in config file:

bezier = winIn, 0.1, 0.7, 0.1, 1.1
animation = workspaces, 1, 3, winIn, slide

2. set up a second extended display in hyprland.

3. place a window that overlaps onto the second screen so that each half of it is visible on both displays.

4. with focus on the main screen, navigate to another workspace then navigate back.

### Crash reports, logs, images, videos

my config file is here: https://pastebin.com/raw/ygXQifEr
video here: https://www.reddit.com/r/hyprland/comments/171m6ws/damage_tracking_2_dual_screen_glitch_when

am using a Dell XPS 13 Plus with Intel GPU "Intel® Iris® Xe Graphics"

**Comment by MightyPlaza** [comment]
what application is that?
I've only seen this happen with nested hyprland session

**Comment by neilking01** [comment]
qt6ct and cool-retro-term. No nesting going on.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/12836035/patch.txt)

try this

**Comment by neilking01** [comment]
> [patch.txt](https://github.com/hyprwm/Hyprland/files/12836035/patch.txt)
> 
> try this

Thank you kind human.  This has actually done the trick!!!

**Comment by vaxerski** [comment]
this is annoying because I don't honestly know how to fix this. Logically.

If a window is sliding to give way to a new workspace, it will pop in and out in one frame. Is that the way to go?

example:

left monitor, changing workspace, sliding out to the right

floating windows that were on the edge (partially on the left mon partially on the right) will now venture to the right monitor and suddenly disappear in one frame once the animation is finished.

For windows fully on the monitor it's easy, they can be clipped to the monitor edge. But for ones shared... what should we do?

**Comment by neilking01** [comment]
How about windows that overlapp screens become tempararily "pinned"?

**Comment by vaxerski** [comment]
they're gonna still pop out of existence?

**Comment by neilking01** [comment]
for me, if i'm on the monitor that has less than 50% of the overlapping window displayed, the window does not animate while changing workspaces.

**Comment by vaxerski** [comment]
same issue. I think I know what I can do.

**Comment by neilking01** [comment]
> same issue. I think I know what I can do.

whats the idea? :)

**Comment by Roger-Roger-debug** [comment]
I've just stumbled over the bug myself (I think [discord)](https://discord.com/channels/961691461554950145/961694014615208048/1174684618201501737). For me it also happens on head with  the floating window fully on one monitor. 

Sliding away from the workspace with the floating window doesn't cause this issue, only when the floating window is "pulled" from the other workspace.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/Hyprland/files/13378460/patch.txt)

try this

**Comment by neilking01** [comment]
Looks like this problem is solved for me now with this patch.  Thanks.  However, I did get this crash right after I logged in and tried to switch workspaces:

https://pastes.io/gs6kucmgeq

Hyprland restarted and worked fine after that.

**Comment by vaxerski** [comment]
was fixed in git

**Comment by neilking01** [comment]
> was fixed in git

the crash i mentioned or the patch?

**Comment by vaxerski** [comment]
now, both

**Comment by neilking01** [comment]
lovely

**Comment by neilking01** [comment]
ok, so things are much improved but it seems like the issue is still there to some extent:

**Comment by vaxerski** [comment]
odd, was fixed for me.

**Comment by Roger-Roger-debug** [comment]
Bug seems to be fixed for me as well. 

While this is just cosmetic I think it's a bit odd that when moving away from the workspace the windows vanish at the monitor bound (same behavior for floating + tiled) while when moving to the workspace only tiled windows are cut at the monitor (floating window comes flying in from the other monitor).
