### ISSUE TITLE
Blurry text with fractionally scaled clients

### ISSUE THREAD

**Issue by q234rty** [hyprwm/Hyprland#3792]
### Hyprland Version

Hyprland, built from branch main at commit 29e0a7112ef5c412e4af640b9d80f80b81a26c94 dirty (renderer: added new customization options to the blur shaders (3650)). Tag: v0.31.0-105-g29e0a711

### Bug or Regression?

Regression

### Description

Clients that support wp-fractional-scale-v1 are sometimes blurry.

### How to reproduce

1. Set scale factor to e.g. 1.75
2. Use clients that support wp-fractional-scale-v1 e.g. foot or qbittorrent with qt6
3. Move the window around the monitor until you notice text is blurry.

**Comment by vaxerski** [comment]
that was fixed in -git afaik, please test there

**Comment by q234rty** [comment]
I'm already at https://github.com/hyprwm/Hyprland/commit/29e0a7112ef5c412e4af640b9d80f80b81a26c94 , unless you meant https://github.com/hyprwm/Hyprland/commit/47654a84c2dc68d478d044fd0589ec5cc96dbc66 changed something?

**Comment by vaxerski** [comment]
oh woops

**Comment by vaxerski** [comment]
would help if idiotic foot didnt fucking do this when scaled 
![image](https://github.com/hyprwm/Hyprland/assets/43317083/bec77b1e-d81c-4888-b091-1bf7e6e217fa)

**Comment by vaxerski** [comment]
should be fixed

**Comment by q234rty** [comment]
The floating case seems to be fixed, but tiled seems be still sometime blurry. Adjust gaps_out by one if you can't repro.

**Comment by vaxerski** [comment]
I felt like I was able to repro but it was so subtle on my end I was doubting my eyes.

**Comment by q234rty** [comment]
Can we reopen this please as it's not fixed? It's a bit annoying to randomly see blurry text...

**Comment by vaxerski** [comment]
I can't repro, though.

**Comment by q234rty** [comment]
Another way to repro this for me is to choose a torrent in qbittorrent, right click in different positions in the "Content" panel and observe that the popup is sometimes clear and sometimes blurry.

**Comment by papricasix** [comment]
Hitting this issue as well. It started to appear in `hyprland-0.30.0` or earlier. `hyprland-0.27.2` is working fine, without issues.
I can reproduce it just by either resizing a window, or moving it around. When moving, it's like on some coordinates it's a bit blurry, on others quite blurry and on some it's ok.

**Comment by vaxerski** [comment]
well I am resizing kitty very slowly and it doesnt turn blurry at all

**Comment by q234rty** [comment]
AFAIK kitty does not support wp-fractional-scale-v1, you need foot or alacritty.

**Comment by vaxerski** [comment]
tried foot, same deal.

**Comment by q234rty** [comment]
Try opening multiple foot instances side by side in a dwindle layout, running the same command e.g. "ls", plus setting alpha to 1 to avoid the desktop background image changing the appearance. You will notice that the font rendering is different.

**Comment by vaxerski** [comment]
right, it rarely is a tiny bit different, maybe I have too high res of a display to clearly see this.

**Comment by papricasix** [comment]
I have this with a 5k2k display and it's very clearly visible. Would recording it help in any way?

**Comment by vaxerski** [comment]
finding the bug would help more

**Comment by q234rty** [comment]
For the record, changing the scale to 1.6 on my 2560x1440 monitor did not help on 6c8e0f9863d86755d7931a9d6ad920b2049cf6a6

**Comment by q234rty** [comment]
For posterity: There were some talks about the root cause in https://github.com/hyprwm/Hyprland/issues/4225, this bug per-se is resolved by https://github.com/hyprwm/Hyprland/commit/b5b025a1ed6cfa2b94ad0eff38a247223edd95bb since now the affected apps are no longer blurry (but sometimes have duplicated/missing pixels). I will close this for now.
