### ISSUE TITLE
Closing window on rotated monitor results in flickering traces of that window.

### ISSUE THREAD

**Issue by Wumianzhe** [hyprwm/Hyprland#399]
Steps to reproduce:

using config file with lines:
```
monitor=HDMI-A-1,1920x1200@59.95,0x0,1
monitor=HDMI-A-1,transform,1
```
otherwise example config file.

Expected outcome: window closes normally

Noted outcome: weird remnants like on pictures
![20220720_15h12m58s_grim](https://user-images.githubusercontent.com/49762386/179981736-191d1b58-de25-47b9-8311-c9fa5a0323a9.png)
![20220720_15h18m04s_grim](https://user-images.githubusercontent.com/49762386/179981754-3f0094b8-f392-4818-bf05-ae9e653b6002.png)
Does not appear on same monitor in horizontal orientation.

Placing another application/overlay in affected area removes flicker (which makes them impossible to screenshot using slurp), but only in area under window. Moving window away does not result in flickering remnants. Opening new window (to persist workspace) and switching workspaces to another and back removes the effect (regardless if another workspace was on same monitor).

**Comment by vaxerski** [comment]
i hate this

**Comment by vaxerski** [comment]
fixed a bit with 9463e3eb0a3ee0d46ae156144346df38c170c94b

leave this open, I'll rewrite snapshots in a bit cuz this system sucks

**Comment by Wumianzhe** [comment]
Finally got to update, and traces are still there.
I have rechecked a couple times, commit is applied.

Sorry for delayed response.

And notification behave in similar fashion when they expire/are closed (regardless of update being applied).
![20220722_21h16m26s_grim](https://user-images.githubusercontent.com/49762386/180499884-a1fdc778-bb7f-4a19-9089-eb87030bd214.png)

**Comment by vaxerski** [comment]
for now, added `misc:damage_entire_on_snapshot`. If you turn it on, there will be no flickers, but it will use a bit more GPU when rendering the fadeout. (only when rendering the fadeout, rest will be unaffected)

**Comment by Wumianzhe** [comment]
That fixes it

**Comment by Wumianzhe** [comment]
Closed notifications are still shown rotated, but now only for one frame

**Comment by vaxerski** [comment]
fixed windows in eb658dcb612806cd801a438f4ec61701e7f26bc4

> Closed notifications are still shown rotated, but now for limited time instead of until redraw

that was fixed a while ago, forgot to close.
