### ISSUE TITLE
Zoom conferencing software issues on Hyprland

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [hyprwm/Hyprland#4809]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
0.35.0.r42.289d952a
```

</details>

### Bug or Regression?

Bug

### Description

Using the Zoom video conferencing software, I get issues that I only get on Hyprland (i.e. these issues I cannot reproduce on Gnome nor KDE (tested each on X11 and Wayland).

- Issue I: Popup listboxes immediately (1 second or less) disappear after opening them
- Issue II: Screen sharing produces only a black shared screen

### How to reproduce

- Install Zoom
- Click "New Meeting" and "Join with computer Audio"

Issue I:
- On the bottom bar click one of the small arrows to open the popup listboxes
- Notice them disappearing immediately

Issue II:
- Click on "Share Screen" and "Share"
- Notice that only a black screen is shared (e.g. log in via Phone app to confirm)

**Comment by vaxerski** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/178

**Comment by letscho123** [comment]
Issue I still persists for me, but I found a simple workaround:
When clicking on a popup box, don't move your mouse. Instead, use the arrow keys to select the option you want.

**Comment by mridhop** [comment]
> Instead, use the arrow keys to select the option you want.

Doesn't work for menus inside the meeting window, only on the main zoom app

**Comment by m-krebs** [comment]
I found that stayfocused was too aggresive as I coudn't really switch to my Password Manager with mousehover.

`noinitialfocus` as rule works better in my case.

```
windowrule = noinitialfocus, class:zoom, title:Zoom Workplace # fixes audio dropdown
windowrule = noinitialfocus, class:zoom, title:menu window # camera, login, more context menu ...
```

**Comment by Ka1zza** [comment]
Just dropping my 2 cents here. 

`windowrule = move onscreen cursor, ...`

Allows for the expected behaviour.

**Comment by pstuifzand** [comment]
I also found that in the latest versions of Zoom these issues were fixed. The popups now appear as small popups where you would expect them.

**Comment by Ka1zza** [comment]
Interesting! I'll have to remove my window rules and see. Thanks for the info!

**Comment by an4s911** [comment]
The popup list boxes are tiling for me. Is this the normal behavior?

**Comment by Ka1zza** [comment]
Try creating a window rule for all zoom windows to float.
I can't remember it atm but you'll find it in the hyprland wiki. 

Should be along the lines of `windowrule = float, class:zoom`

Tip: use `hyprctl clients` to view the class and title of open windows.

**Comment by an4s911** [comment]
Yeah, but that doesn’t solve the issue because floating windows open in the middle of the screen, but the button to click to open the popup listboxes are somewhere else. I think there is some way to make it open at the cursor. 

But anyways, I just forced Zoom to use Xwayland, and it looks like it works perfectly. I need to use it for a while to see if it has any other issues.

**Comment by Ka1zza** [comment]
Previous comments adress that too. Use
`windowrule = move onscreen cursor, class:zoom, title:menu window `

Works for me running zoom as wayland. 
Some of the pop-ups have different titles. It think there were about 3 different ones. Sorry, don't have access to my laptop.
