### ISSUE TITLE
Cursor lagging in games

### ISSUE THREAD

**Issue by LachlanS7** [hyprwm/Hyprland#5611]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit ccbdce7c8528781020b39ddf4498277df5e5e78d  (input: send an empty relative event after constraint motion events).
Date: Tue Apr 16 01:52:25 2024
Tag: v0.39.0-9-gccbdce7c, commits: 4453

flags: (if any)


System Information:
System name: Linux
Node name: topos
Release: 6.8.6-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Mon, 15 Apr 2024 14:05:39 +0000


GPU information: 
2d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c5) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Bug or Regression?

Bug

### Description

Hi there!

I have an issue where my cursor lags in games (really only DX11 Baldur's Gate 3, but I believe I have seen it in other games before, but can't find direct evidence from a short search). I have confirmed that this issue is not present in KDE Plasma (Wayland) and Sway, and persists after playing around with the variables
- `WLR_DRM_NO_ATOMIC`
- `no_direct_scanout`
- `WLR_NO_HARDWARE_CURSORS`
- `vrr`
- `vfr`
- `tearing`

This issue is also not solved by gamescope (still not present when running with gamescope on other WMs/DEs). I have also tried patching my kernel using the patches [here](https://gitlab.freedesktop.org/drm/amd/-/issues/2186), and this didn't make a difference. Capping my framerate does understandably help (as the GPU isn't as stressed), but the issue is still prevalent unless I cap the FPS significantly, and I don't believe I should need to cap my framerate for my cursor to be smooth. I have also tried a "minimal" Hyprland config, and this didn't change anything (view the config below).

<details><summary>Minimal config tried</summary>

```
monitor=DP-1,2560x1440@165,0x0,1
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

general {
    border_size = 0
    no_border_on_floating = true
    gaps_in = 0
    gaps_out = 0
    layout = dwindle
    extend_border_grab_area = 0
    hover_icon_on_border = false

    no_cursor_warps = false
    apply_sens_to_raw = false
}

decoration {
    rounding = 0
    drop_shadow = false
    shadow_range = 0
    shadow_scale = 0

    blur {
        enabled = false
        passes = 0
    }
}

animations {
    enabled = false
    first_launch_animation = false
}

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0

    force_no_accel = false
}

xwayland {
  force_zero_scaling = true
  use_nearest_neighbor = false
}


misc {
    vrr = 2
}


dwindle {
    pseudotile = yes
    preserve_split = yes
}

$mainMod = SUPER
bind = $mainMod, RETURN, exec, foot
bind = $mainMod, D, exec, wofi --show drun
bind = $mainMod, C, killactive
bind = $mainMod, F, fullscreen

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
```
</details>

This issue is further complicated by enabling `debug:overlay`, which was reporting the fps to be ~25 when the game was claiming ~70fps.

### How to reproduce

Run Baldur's Gate 3 on Hyprland with DX11, and set the settings to stress your GPU. The cursor should feel jittery with both `vrr` on and off. 

### Crash reports, logs, images, videos

I recorded two videos using the same settings, one on KDE Plasma (Wayland), and the other on Hyprland. 

https://github.com/hyprwm/Hyprland/assets/57027406/0a26adae-1171-4561-bdb5-74234997a785

https://github.com/hyprwm/Hyprland/assets/57027406/ef50aec5-457f-43c0-96fc-78613a4a3b2f

As you can tell, the cursor on the Hyprland one is noticeably jittery, meanwhile, the animations and the KDE Plasma one is smooth. (please ignore the frametimes. This is an artifact of recording it. The frametime graphs looks similar when not recording).

_p.s. special thank you to unknown6195 on Discord, for their help trying to debug this issue._

**Comment by donovanglover** [comment]
FWIW I can reproduce huge fps drops when moving the cursor around in wine applications like osu! (e.g. 60 to 1-20).

The faster the mouse moves the more lag there is. Doesn't happen when moving the mouse slowly. Lags less (60 to 30 instead of 1) when holding down the right mouse button.

For me I think this started sometime after 0.34.0. No lag with the trackpad

**Comment by EvilBoi123** [comment]
wait, wtf? i just realize this. I thought it is my driver or dxvk side of fault. 

> Minimal config tried
> This issue is further complicated by enabling `debug:overlay`, which was reporting the fps to be ~25 when the game was claiming ~70fps.

yeah thats, the problem, even with dxvk overlay, the framerate told a false fps, it reported higher than it actually render on screen somehow.

**Comment by LachlanS7** [comment]
> wait, wtf? i just realize this. I thought it is my driver or dxvk side of fault. 
> 
> > Minimal config tried
> > This issue is further complicated by enabling `debug:overlay`, which was reporting the fps to be ~25 when the game was claiming ~70fps.
> 
> yeah thats, the problem, even with dxvk overlay, the framerate told a false fps, it reported higher than it actually render on screen somehow. 
> 

Ohh, you've seen this issue too. Do you recall what you were doing when you noticed it?

**Comment by EvilBoi123** [comment]
> Ohh, you've seen this issue too. Do you recall what you were doing when you noticed it?

Nothing really, one day i just want to try KDE but somehow it is much smoother there. So you could say i played my game lagging all this time without noticing. 

> For me I think this started sometime after 0.34.0. No lag with the trackpad

but since @donovanglover says it's starts from 0.34.0 i'd say maybe its started from there is the  good bisect, i'll have to try out this later, once i return to my library.

**Comment by EvilBoi123** [comment]
yeah, i've recompiled v0.34, the cursor and framerate was smoother there. v0.35 onwards have this issue introduced. compiling with legacyrenderer also wouldn't help.

**Comment by fufexan** [comment]
> v0.35 onwards

*what*

**Comment by LachlanS7** [comment]
> yeah, i've recompiled v0.34, the cursor and framerate was smoother there. v0.35 onwards have this issue introduced. compiling with legacyrenderer also wouldn't help.

Oh wow! Thank you for trying this. I'll give this a shot and report back as soon as my exams are over in a few days.

**Comment by EvilBoi123** [comment]
okay, i have some findings to share. It turns out after testing with wayfire, it seems somehow the wayfire were also affected by this. Same goes to sway, but sway somehow is less laggy than other wlroots based compositor out there. 

KDE desktop were not affected by this maybe because they were not wlroots? My guess would be it maybe the wlroots side of fault. 

I also realized when i launch one of my game, all the wlroots compositor will open it in tiling mode insted of fullscreen, which is weird, all this time it should work and it launches normally in KDE.

**Comment by izmyname** [comment]
> okay, i have some findings to share. It turns out after testing with wayfire, it seems somehow the wayfire were also affected by this. Same goes to sway, but sway somehow is less laggy than other wlroots based compositor out there.
> 
> KDE desktop were not affected by this maybe because they were not wlroots? My guess would be it maybe the wlroots side of fault.
> 
> I also realized when i launch one of my game, all the wlroots compositor will open it in tiling mode insted of fullscreen, which is weird, all this time it should work and it launches normally in KDE.

I suggest you test it on the latest hyprland-git, since the compositor is no longer wlroots based.

**Comment by LachlanS7** [comment]
Sorry for the wait. I've tried aquamarine, and I've found that despite trying it before, `no_hardware_cursors = true` has substantially improved my cursor issues on Baldur's Gate 3.

Having said this, either `no_hardware_cursors = true` or `no_direct_scanout = true` has caused visual stuttering in games. From limited testing, this doesn't happen with those using vulkan (definitely those using DXVK  not sure about DX12). The stuttering looks like that in #6359, so I suspect they might be related.

**Comment by LachlanS7** [comment]
I noticed that #7110 was merged, and decided to try it out. I believe my build before was just before this MR was accepted (built <24 hours ago), hence I believe my following observations are as a result of this MR. It seems like my stuttering issues have been resolved, however, I need `no_hardware_cursors = true` or else games will permanently freeze. Furthermore, the cursor stutter I had in BG3 has returned.

**Comment by EvilBoi123** [comment]
> Sorry for the wait. I've tried aquamarine, and I've found that despite trying it before, `no_hardware_cursors = true` has substantially improved my cursor issues on Baldur's Gate 3.
> 
> Having said this, either `no_hardware_cursors = true` or `no_direct_scanout = true` has caused visual stuttering in games. From limited testing, this doesn't happen with those using vulkan (definitely those using DXVK not sure about DX12). The stuttering looks like that in #6359, so I suspect they might be related.

hmm i don't know, the issue still persist even after i'm experiment around with `no_hardware_cursors` but the good thing is, my game now fullscreen on default, not like the previous version. So it is still improvements.

**Comment by LachlanS7** [comment]
> hmm i don't know, the issue still persist even after i'm experiment around with `no_hardware_cursors` but the good thing is, my game now fullscreen on default, not like the previous version. So it is still improvements.

Huh. I suspect our issues might be unrelated then. I thought I noticed general mouse stutter on all games in the past, but I'm not sure if I can still notice it (it was always subtle). I will try test for your specific issue more in a lil while.

**Comment by EvilBoi123** [comment]
> > hmm i don't know, the issue still persist even after i'm experiment around with `no_hardware_cursors` but the good thing is, my game now fullscreen on default, not like the previous version. So it is still improvements.
> 
> Huh. I suspect our issues might be unrelated then. I thought I noticed general mouse stutter on all games in the past, but I'm not sure if I can still notice it (it was always subtle). I will try test for your specific issue more in a lil while.

my games runs fine and all but the thing is when my game renders 30 fps, my cursor would also renders at those fps. Other compositor would always render at refresh rate of monitor regardless of what fps their games renders at.

**Comment by adamnejm** [comment]
> my games runs fine and all but the thing is when my game renders 30 fps, my cursor would also renders at those fps. Other compositor would always render at refresh rate of monitor regardless of what fps their games renders at.

This happens to me as well when tearing is enabled for the client. For some reason tearing causes cursor to be locked to game's FPS, neither VRR/VFR nor hardware cursors fix this.

**Comment by JJK-IO** [comment]
For me this doesn't happen consistently. I can be in a game for a while before this issue shows up for me. I believe the trigger relates to either focusing a different window or potentially some more cpu intensive actions in the game generally causes the fps to drop in relation to my mouse movement.

I do have `cursor::use_cpu_buffer = true`

```sh
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.5.1
 hyprlang 0.6.0
 hyprutils 0.3.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1
```

**Comment by LachlanS7** [comment]
Okay, I have tested the latest release and found some interesting things. I have confirmed that my friend can reproduce these issues using an Intel CPU and the same GPU as me (6700 XT).

So, I have recently been playing _Hunt Showdown 1896_. While the frame time consistency isn't the best on both KDE and Hyprland, it plays mostly smoothly on KDE whereas it stutters badly on Hyprland. I have managed to capture this issue in the following (slowed down) videos below. 

##### KDE Plasma (Wayland)
https://github.com/user-attachments/assets/577bfb57-7baf-4d2a-bb1b-d16c8b82ea3e

##### Hyprland (mostly present in 2nd half)
https://github.com/user-attachments/assets/469002b0-6b43-4f63-a90a-f2083f872a45

Strangely, enabling direct scanout with VRR on Hyprland drastically smoothens out the frame times (and thus VRR), to the point where the frame times are better than those in KDE plasma! However, it still stutters like above (I could've sworn it recently felt good with VRR on, but I've since updated and that's no longer the case, and hence take this with a grain of salt). If I now disable VRR but leave direct scanout on, the frame times are not as smooth but the game feels as good as KDE (minus the benefits of VRR ofc).

The issue with direct scanout is that with my 6700 XT I get some bad artifacting (using Mesa 24.3.3). The interesting thing with this is that artifacting seems to mostly (maybe exclusively) occur when my monitor is running at max refresh, and so VRR greatly reduces the artifacting (sometimes removes it entirely). But enabling VRR causes the issues described above. Furthermore, setting my refresh rate to something below my maximum in my Hyprland config (monitor section) doesn't improve the issue either, it just lowers the fps required to cause artifacts. To clarify, I do sometimes get artifacts when my fps is less than my monitor's refresh rate, but they are less frequent and it depends on the game (might be a game frame time thing). Furthermore, setting `amdgpu.dcdebugmask=0x10` to disable PSR as suggested by other people didn't help either. (The artifacting issue used to be worse as, until recently, moving my cursor would cause VRR to break and jump to my max refresh rate. I think updating Mesa or Hyprland has fixed this issue. Perhaps this is why I thought Hunt Showdown felt smoother with direct scanout and VRR on before, whereas now it feels stuttery again unless VRR is off)

Now how does all of this relate back to my cursor lagging in Baldur's Gate 3? Well, while my cursor in BG3 does seem better than when I first made this issue, it seems having direct scanout enabled also helps with cursor smoothness in BG3, but this also comes with the same caveats as in Hunt Showdown.  As these issues are not present in other WMs or DEs, I believe there is a bigger, more pervasive, issue with Hyprland that is making some games feel awful to play, and it seems a few others in this issue have mentioned this too.

### Additional notes
- I have tested arch, bazzite, and nixOS with no difference observed
- Using software cursors does not help fix stuttering issues

**Comment by EvilBoi123** [comment]
so i did some diggings. since i found out that this affected most of other wlroots based compositor. This issue maybe is not hyprland's fault but rather upstream wlroots. 

this might be open ticket [https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3721](url)

**Comment by EvilBoi123** [comment]
so i did some digging. since i conclude that this mostly affected by other wlroots based compositor, it might be not hyprland's fault but rather upstream wlroots. miracle-wm does not affected by this btw. 

here is might be the opening ticket. https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3721

**Comment by vaxerski** [comment]
Hello there!

This issue has been closed, as we are moving from issues to discussions. More about this can be found [here](https://wiki.hyprland.org/Contributing-and-Debugging/Issue-Guidelines/) and in #9854.

Firstly, please make sure this issue is still relevant in latest Hyprland. If so, we ask you to open a [discussion](https://github.com/hyprwm/Hyprland/discussions) (please read the discussion guidelines first, in the pinned post)

Thank you for your understanding!
