### ISSUE TITLE
Tool tips are cropped

### ISSUE THREAD

**Issue by re-ynd** [hyprwm/Hyprland#566]
**Steps to reproduce**
1. Launch chrome and open any webpage that displays tool tips when hovering over a link like github
2. Hover over a link

**Expected outcome**
The tool tip should be visible clearly

**Noted outcome**
Tool tip is cropped and artifacts from previous tool tip are left over. If I change the `damage_tracking` to `none` or `monitor` then I don't see this issue.

Following image shows a zoomed up piece of tool tip that has been cropped from top and left
![damage2](https://user-images.githubusercontent.com/10625895/186172551-0a95a409-3e23-456c-a72f-3161bfc2d5fd.png)

In the below image, a previous tool tip is left over along with a new cropped tool tip
![damage1](https://user-images.githubusercontent.com/10625895/186172541-a479216d-60e5-4009-a11c-846d8e06ccb7.png)

Started noticing this issue in v0.11.0beta. Previously I was on v0.10.1beta and did not have this issue

**Comment by vaxerski** [comment]
they arent cropped, they are rounded.

For the second issue - can't reproduce. Can you do a `git bisect`?

**Comment by vaxerski** [comment]
wait nvm got it

**Comment by vaxerski** [comment]
original issue fixed in 451659ec3487c5cd09f465327675ccfe463856c3

**Comment by vaxerski** [comment]
removed popup rounding in f9b2aa5468a7598547b4a1d70ffd5495f1448a3b

**Comment by vaxerski** [comment]
ye cuz they are less cringe and not oversized

**Comment by re-ynd** [comment]
Still seeing this issue in v0.11.1beta. The tool tips in chrome are not rounded anymore but the ones in VS code are still rounded.

![2022-08-24_06:24:44 262459477](https://user-images.githubusercontent.com/10625895/186292729-409a9ee3-84a3-4cb1-a0c0-95c94327f69a.png)


And the tool tip in chrome are still not fully displayed when `damage_tracking=full`

![2022-08-24_06:24:54 910739483](https://user-images.githubusercontent.com/10625895/186293109-2df17f54-0c49-4efb-a70f-845bfaad3f0e.png)

**Comment by vaxerski** [comment]
that's because VS code is most likely running in XWayland.

In chrome - for me they are fixed, so can't repro.

**Comment by re-ynd** [comment]
Which version of chrome? I am using Version 104.0.5112.101

**Comment by vaxerski** [comment]
latest chromium

**Comment by vaxerski** [comment]
check with new viewporter commits

**Comment by re-ynd** [comment]
Perfect! Got fixed in v0.12.0beta
