### ISSUE TITLE
No keyboard focus on newly launched terminal emulator, etc. with Fcitx

### ISSUE THREAD

**Issue by glyh** [hyprwm/Hyprland#5763]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

flags: (if any)


System Information:
System name: Linux
Node name: mechrevo
Release: 6.8.7-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT1 [UHD Graphics] [8086:46a3] (rev 0c) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4060 Max-Q / Mobile] [10de:28a0] (rev a1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

When creating a new terminal emulator in an empty workspace, I can't type into it(even if it's focused). But after switching to another workspace and switch back to it, I can. 

### How to reproduce

As above. 

### Crash reports, logs, images, videos

https://pastebin.ubuntu.com/p/Jf7j772Jc3/

**Comment by vaxerski** [comment]
doesn't happen on my end. Config?

**Comment by glyh** [comment]
https://pastebin.ubuntu.com/p/G6GjYRyrtN/

**Comment by vaxerski** [comment]
if it's a regression can you `git bisect` it?

**Comment by hftsai256** [comment]
Is the issue I'm encountering (#5764) the same as yours? I don't use `tofi,` but I observe similar behavior with Kitty and Foot. This can happen very often (50/50), but sometimes, everything is fine.

**Comment by glyh** [comment]
@hftsai256 I think it's probably the same, except I can reproduce 100% of the time. 

I also realize that on electron apps I have to focus twice to allow keyboard input.

**Comment by glyh** [comment]
@vaxerski I didn't build hyprland on my end, but rather I use a prebuilt binary. I would take a look if I have time.

**Comment by glyh** [comment]
@vaxerski I didn't build hyprland on my end, but rather I use a prebuilt binary. I would take a look if I have time.

**Comment by glyh** [comment]
Look like this is exactly https://github.com/fcitx/fcitx5/issues/1031 and a duplicate of #5764.

**Comment by clsty** [comment]
I've met similar problem, but mine is:

When keep pressing `Super` key, the focus switching will fail.
Its window border indicates that it is focused, but the keyboard actually still focus on the previous one.

E.g. Press `Super+Up` , keep pressing `Super` but release `Up`, and then press `Down` so that is a `Super+Down`. This results in a focus failure.

However, press `Super+Up` , release both `Super` and `Up`, and then press `Super+Down`, it works normally.

This is 100% reproducible on my PC.

btw I'm using AUR package `hyprland-git`. Distro is Arch Linux.

**Comment by vaxerski** [comment]
I tried with fcitx, but still can't repro. Can you check if 1d40af64d352bd5a87c7d53a52707fc5cfc6940e is a regressor? if the commit before that has the same issue, I don't think anything else has changed in hyprland's IME/TI in a while

**Comment by clsty** [comment]
> I tried with fcitx, but still can't repro. Can you check if [1d40af6](https://github.com/hyprwm/Hyprland/commit/1d40af64d352bd5a87c7d53a52707fc5cfc6940e) is a regressor? if the commit before that has the same issue, I don't think anything else has changed in hyprland's IME/TI in a while

Yes, I can confirm that 1d40af6 works normally without focus failure on my PC.

**Comment by Nannk** [comment]
It happens to me as well, except sometimes keyboard input does not follow windows selection at all. I have to move the window(with a mouse) that i want to input to first. Killing fcitx5 fixed it.

**Comment by sungyoonc** [comment]
Can anyone try the latest git? 31d055f6d487bd72fca5b10822e3f3bd95e94cc9 fixed the issue for me.

**Comment by vnwnv** [comment]
I have been tried the current latest git version in archlinux `0.39.1.r91.2e763764-1`. the issue was fixed.

**Comment by clsty** [comment]
Yeah `yay -S hyprland-git` and clean build, reboot, it works.

**Comment by cyrus-xc** [comment]
> Can anyone try the latest git? [31d055f](https://github.com/hyprwm/Hyprland/commit/31d055f6d487bd72fca5b10822e3f3bd95e94cc9) fixed the issue for me.
> 
> The repro steps for me was
> 
> 1. Open 2 apps(terminal, firefox)
> 2. Unselect the text input in firefox(click on the empty space to lose TI focus)
> 3. Go back to terminal and the keyboard focus is still at firefox

latest git version fixed the issue, thanks

**Comment by glyh** [comment]
Will this be released soon? For now the Arch Linux git package is also broken and I can't figure out a way to fix it. No working hyprland for me unless I downgrade fcitx5, which seems to be bringing some other issues.

**Comment by glyh** [comment]
Hmm, weird...

With Arch's prebuilt hyprland 40.0 the issue persists for me, but when using `hyprland-git` the issue is gone.

**Comment by glyh** [comment]
NVM I can't repro this all of a sudden.
