### ISSUE TITLE
Hyprland crashes when kando invoked from edge of the screen.

### ISSUE THREAD

**Issue by KAGEYAM4** [hyprwm/Hyprland#6018]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)


System Information:
System name: Linux
Node name: ArchLinux
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630] [8086:3e9b] (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:


```

</details>

### Bug or Regression?

Regression

### Description

When Kando tries to warp the mouse pointer (which happens when you open Kando close to a screen's edge), the session crashes completely.

### How to reproduce

Note ->
- Use `export ELECTRON_OZONE_PLATFORM_HINT=wayland` for running kando under wayland.
- Do not use any window rules on kando

-----
Under Xwayland ->
1. export -n ELECTRON_OZONE_PLATFORM_HINT
2. run `kando`
3. invoke kando from screen edges ( Ctrl+space ), hyprland.conf - `bind = CTRL, Space, global, kando:main_menu`
4. try to do it from each edge multiple time if hyprland dosen't crash
5. Hyprland will crash.
------
Under wayland ( i am not able to find concrete method to reproduce it here, very rando )
1. `export ELECTRON_OZONE_PLATFORM_HINT=wayland`
2. run `sleep 5 ; kando`
3. go to edge of screen and spam Ctrl+Space
4. When kando intializes at one point Hyprland will crash
5. If hyprland dosnt crash, send SIGTERM from btop or some other top
6. Go to step 2
7. Hyprland will crash

### Crash reports, logs, images, videos

[hyprlandCrashReport8576.txt](https://github.com/hyprwm/Hyprland/files/15282475/hyprlandCrashReport8576.txt)
[hyprland_log.log](https://github.com/hyprwm/Hyprland/files/15282476/hyprland_log.log)

Hyprland log and crash_log are from different session, was trying to reproduce it correctly. Crashed hyprland 30 times.

**Comment by KAGEYAM4** [comment]
https://github.com/kando-menu/kando/issues/417, kando was creating segfault which was fixed yesterday. But this bug happened next.

**Comment by Schneegans** [comment]
Just some additional information:
* Kando uses wlroot's [virtual pointer protocol](https://wayland.app/protocols/wlr-virtual-pointer-unstable-v1) to move the mouse pointer.
* Before 0.40.0, the code for moving the mouse pointer did not result in a crash.
* The relevant code is here: https://github.com/kando-menu/kando/blob/main/src/main/backends/linux/wlroots/native/Native.cpp#L220

My guess it that something in the implementation of the protocol changed which is now causing the crash. This could either require a fix in Kando (am I using the protocol in wrong way?) or in Hyprland (or maybe in wlroots?) :thinking:

**Comment by vaxerski** [comment]
can someone https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace ?

This is a hyprland bug, even if kando does something wrong, it should not kill hyprland

**Comment by KAGEYAM4** [comment]
> can someone https://wiki.hyprland.org/Crashes-and-Bugs/#obtaining-a-debug-stacktrace ?

Build it from release commit/tag or latest git?

**Comment by vaxerski** [comment]
git

**Comment by KAGEYAM4** [comment]
@vaxerski  

Here what i did, verify ->
1. make debug
2. From tty -> `~src/Hyprland/build/Hyprland`
3. Crashed hyprland
4. Followed wiki
5. after doing `bt -full`, there was no mention of how to get that output in file.
6. After running `set logging on`, then i re-ran `bt -full`, output was created in `gdb.txt`

Is the 6th step missing from wiki? I will add it if you say so.

[gdb.txt](https://github.com/hyprwm/Hyprland/files/15283696/gdb.txt)

**Comment by KAGEYAM4** [comment]
```
windowrule = center, Kando
windowrule = size 100% 100%, Kando
```
Without these Hyprland crashes at non-edges too.

**Comment by vaxerski** [comment]
aw fuck uhh can you also run hyprland with `HYPRLAND_NO_CRASHREPORTER=1`? Seems like it got in the way of the backtrace :/

`HYPRLAND_NO_CRASHREPORTER=1 Hyprland`

**Comment by KAGEYAM4** [comment]
[gdb.txt](https://github.com/hyprwm/Hyprland/files/15284302/gdb.txt)

**Comment by vaxerski** [comment]
this looks... odd?
[patch.txt](https://github.com/hyprwm/Hyprland/files/15284348/patch.txt) this will likely work as a band-aid, but #5999 should solve this completely

**Comment by KAGEYAM4** [comment]
do i need to test the patch? if i need to let me know. Because currently i can live without it by avoiding triggering kando at edge.

**Comment by vaxerski** [comment]
uhh testing that it works would be nice

**Comment by KAGEYAM4** [comment]
> uhh testing that it works would be nice

ok will do it.

**Comment by KAGEYAM4** [comment]
@vaxerski  its still happening -> 
1. `patch src/managers/input/InputManager.cpp < ~/Downloads/patch.txt`
2. rm -rf build
3. make debug
4. ......

[gdb.txt](https://github.com/hyprwm/Hyprland/files/15284385/gdb.txt)

**Comment by vaxerski** [comment]
:/ will take a look again after #5999 is merged if it's still a thing then

**Comment by KAGEYAM4** [comment]
i am not able to reproduce this bug on lates git - https://github.com/hyprwm/Hyprland/commit/3ac0e7ead1434c172f276a12f81da1eeb0dc4491.  i will close  this issue.

I  can't daily drive this as 'primary selection' is borked on this commit. I will test it further when stable release is made.
