### ISSUE TITLE
Click and drag cursor cannot release on Chromium(Wayland mode)

### ISSUE THREAD

**Issue by hdm9527** [hyprwm/Hyprland#6509]
### Bug or Regression?

Bug

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 4842eb83b444418ad3fe1901d645dd02224989e5  (helpers: make shm_open() portable after 8bcccf9f0f0f (6471)).
Date: Thu Jun 13 20:20:14 2024
Tag: v0.41.1-2-g4842eb83, commits: 4820

flags: (if any)


System Information:
System name: Linux
Node name: Arch
Release: 6.9.3-2-cachyos-echo-lto
Version: #1 SMP PREEMPT_DYNAMIC Thu, 06 Jun 2024 06:05:56 +0000


GPU information: 
64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Clicking on a tab or button and dragging it under chromium does not release the cursor.

### How to reproduce

1. start chromium with `chromium --ozone-platform=wayland`.
2. clicking on a tab or button on a web page and dragging it.

### Crash reports, logs, images, videos

https://github.com/hyprwm/Hyprland/assets/39702328/4e721ae1-c02e-4402-a4d5-334b0971dc6a

**Comment by vaxerski** [comment]
this is a broken chromium impl it seems, at least for the home screen icon drag, as that is broken on sway too. The getting stuck is a hyprland bug.

**Comment by hdm9527** [comment]
Thanks.

**Comment by hdm9527** [comment]
Just tested it and the cursor is still not released.

**Comment by vaxerski** [comment]
it surely was released on my end. Make sure you're on the right version with `hyprctl version`

**Comment by hdm9527** [comment]
> it surely was released on my end. Make sure you're on the right version with `hyprctl version`

```
Hyprland, built from branch main at commit 91fe58f8f278d126852877eadc87c50ca7b9b78d  (window: improve swallowing functionality).
Date: Sun Jun 16 00:20:41 2024
Tag: v0.41.1-18-g91fe58f8, commits: 4836

flags: (if any)
```

**Comment by vaxerski** [comment]
hm, odd. it surely works for me. Anything else you can find to trigger this? Some config opt?

**Comment by hdm9527** [comment]
> hm, odd. it surely works for me. Anything else you can find to trigger this? Some config opt?

I commented out the chromium-flags.conf configuration and just started chromium with the chromium --ozone-platform=wayland command and it still doesn't release the cursor

**Comment by hdm9527** [comment]
The cursor is not released even if the text is selected and dragged.

**Comment by andrewathalye** [comment]
Same issue in Helvum, including with latest commit.

**Comment by vaxerski** [comment]
it... works on my end but is really wonky, I'll try to look at it tomorrow

**Comment by vaxerski** [comment]
jfc wtf is gtk's problem????????????

**Comment by vaxerski** [comment]
no shit

**Comment by vaxerski** [comment]
also no it doesnt

**Comment by vaxerski** [comment]
should be fixed, please verify

**Comment by hdm9527** [comment]
> should be fixed, please verify

It seems to be worse, before it was the current tab not releasing the cursor.

https://github.com/hyprwm/Hyprland/assets/39702328/3ca9a49a-58a6-4fc4-b266-3493a0c1507c

**Comment by vaxerski** [comment]
well helvum was fixed...

**Comment by vaxerski** [comment]
should be fixed

**Comment by andrewathalye** [comment]
Helvum didn’t get fixed for me with the previous patch. Trying your latest one now that I’ve got a good dev env set up.

**Comment by hdm9527** [comment]
> should be fixed

Thanks. It's works.

**Comment by andrewathalye** [comment]
@vaxerski It still does not work in Helvum for me so I’ll open a new issue

**Comment by khaneliman** [comment]
Seems to have broken Firefox drag and drop of tabs..

**Comment by aryklein** [comment]
For the people that are not using the `-git` package version, when are you going to release a new version? :)

**Comment by vnva** [comment]
The problem continues to reproduce even in the git version

**Comment by aryklein** [comment]
Yes, it seems it's happening again for me as well
```
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)
```

**Comment by sleklere** [comment]
Happening to me as well. When setting the ozone platform to X11 it goes away but you get those big gaps around the modal windows.

```
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)
```

**Comment by vaxerski** [comment]
it's fixed on git how many times

**Comment by adityavishwakarma69** [comment]
Yea, seems like this is happening to me too
```
$hyprctl version
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)
```

Uploading 2024-09-04 19-17-10.mp4…

**Comment by vaxerski** [comment]
IT IS FIXED IN GIT PLEASE STOP POSTING THAT IT HAPPENS IN 0.42

**Comment by adityavishwakarma69** [comment]
> IT IS FIXED IN GIT PLEASE STOP POSTING THAT IT HAPPENS IN 0.42

oh sorry
