### ISSUE TITLE
Apex Legends season 22 update breaks cursor capture/lock with Hyprland

### ISSUE THREAD

**Issue by Cloudperry** [hyprwm/Hyprland#7213]
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 2cfc6722fdbc93fd0c5987eeac0d4b96cd0128a7  (guard rb?).
Date: Tue Aug 6 14:57:43 2024
Tag: v0.41.2-191-g2cfc6722, commits: 5077

flags: (if any)


System Information:
System name: Linux
Node name: roni-desktop
Release: 6.10.3-2-cachyos-lto
Version: #1 SMP PREEMPT_DYNAMIC Sat, 03 Aug 2024 11:44:48 +0000


GPU information:
0d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6950 XT] [1002:73a5] (rev c0) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/roni/.config/hypr/hyprland.conf: Read Succeeded
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/settings.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/rules.conf


Config File: /home/roni/.config/hypr/startup.conf: Read Succeeded
#################
### AUTOSTART ###
#################

# Hyprlock
# exec-once = hyprlock
# Hypridle
exec-once = hypridle
# Notification service
exec-once = systemctl --user start swaync-without-graphical-target
# Status bar
exec-once = systemctl --user start ironbar
# Wallpaper service
exec-once = systemctl --user start hyprpaper
# Polkit service
exec-once = systemctl --user start lxqt-policykit-agent
# Clipboard history daemon
exec-once = systemctl --user start cliphist-text
exec-once = systemctl --user start cliphist-image

# Startup apps
exec-once = discord & corectrl & blueman-applet

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
#env = AQ_ATOMIC,0
#env = AQ_NO_ATOMIC,1

# Toolkit options
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# KDE apps fixes
env = XDG_MENU_PREFIX,arch-


Config File: /home/roni/.config/hypr/settings.conf: Read Succeeded
################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-3, 2560x1440@144, 1920x0, 1
monitor = HDMI-A-1, 1920x1080@60, 0x700, 1

###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = dolphin
$browser = firefox
$textEditor = neovide
$menu = wofi --show drun
$menuExec = wofi --show run

#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 4
    gaps_out = 8

    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = true

    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 6

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    preserve_split = false
    no_gaps_when_only = 1
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    enable_swallow = true
    swallow_regex = .*
    initial_workspace_tracking = 0 # Special workspaces bug workaround
    force_default_wallpaper = 1
    disable_hyprland_logo = true
    vrr = 2
    #no_direct_scanout = false
}

cursor {
    no_hardware_cursors = true
    no_break_fs_vrr = true
    min_refresh_rate = 48
}

experimental {
    #explicit_sync = true
}

render {
    explicit_sync = 1
    explicit_sync_kms = 0
    direct_scanout = true
}


Config File: /home/roni/.config/hypr/input.conf: Read Succeeded
input {
    # Keyboard
    kb_layout = fi
    kb_variant = nodeadkeys
    repeat_rate = 20
    repeat_delay = 200

    # Mouse
    follow_mouse = 1
    sensitivity = -0.75 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat

    touchpad {
        natural_scroll = false
    }
}

gestures {
    workspace_swipe = false
}

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# Binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Q, killactive,
bind = $mainMod, Z, exec, loginctl terminate-session $XDG_SESSION_ID
bind = $mainMod Control_L, F, togglefloating,
bind = $mainMod, space, exec, $menu
bind = $mainMod SHIFT, space, exec, $menuExec
bind = $mainMod Control_L, T, togglesplit, # dwindle

# Important apps
bind = $mainMod, C, exec, $terminal
bind = $mainMod, B, exec, start-in-workspaces -a=$browser
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, E, exec, $textEditor

# Move focus with mainMod + arrow keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, S, movefocus, r
bind = $mainMod, N, movefocus, u
bind = $mainMod, T, movefocus, d

# Move window with mainMod + arrow keys
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, S, movewindow, r
bind = $mainMod SHIFT, N, movewindow, u
bind = $mainMod SHIFT, T, movewindow, d

# Move window with mainMod + arrow keys
#bind = $mainMod, Left, swapwindow, l
#bind = $mainMod, Right, swapwindow, r
#bind = $mainMod, Up, swapwindow, u
#bind = $mainMod, Down, swapwindow, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, Down, workspace, r+1
bind = $mainMod, Up, workspace, r-1
bind = $mainMod, Left, focusmonitor, l
bind = $mainMod, Right, focusmonitor, r

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, Down, movetoworkspace, r+1
bind = $mainMod SHIFT, Up, movetoworkspace, r-1

# Special workspaces
bind = $mainMod, M, togglespecialworkspace, music
bind = $mainMod SHIFT, C, togglespecialworkspace, terminal
bind = $mainMod, G, togglespecialworkspace, fullscreenGame

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Clipboard history
bind = $mainMod, V, exec, cliphist list | wofi --show dmenu | cliphist decode | wl-copy

# Screenshotting
bind = $mainMod, Print, exec, grim -o DP-3
bind = $mainMod SHIFT, Print, exec, grim -g "$(slurp)"
bind = $mainMod CTRL, Print, exec, grim

# Media keys
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioStop, exec, playerctl stop
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = Control_L, XF86AudioNext, exec, playerctl position 5+
bindl = Control_L, XF86AudioPrev, exec, playerctl position 5-
bindel = Control_L, XF86AudioRaiseVolume, exec, playerctl volume 0.05+
bindel = Control_L, XF86AudioLowerVolume, exec, playerctl volume 0.05-

# Wallpaper switching
bind = $mainMod, W, exec, hyprctl hyprpaper preload /home/roni/Pictures/Wallpapers/hyprland-current-background.png
bind = $mainMod, W, exec, hyprctl hyprpaper wallpaper /home/roni/Pictures/Wallpapers/hyprland-current-background.png
bind = $mainMod, W, exec, hyprctl hyprpaper unload unused


Config File: /home/roni/.config/hypr/rules.conf: Read Succeeded
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

$high = 0.88 0.88
$medium = 0.91 0.91
$subtle = 0.94 0.94
$minimal = 0.97 0.97

windowrulev2 = suppressevent maximize,class:.*
windowrulev2 = workspace special:fullscreenGame, class:steam_app_[0-9]+, fullscreen:1
windowrulev2 = immediate, class:.*
windowrulev2 = opacity $minimal, class:^(neovide)$
windowrulev2 = opacity $subtle, class:^(Alacritty)$
windowrulev2 = opacity $subtle, class:^(org.kde.dolphin)$
windowrulev2 = opacity $minimal, class:^(discord)$
windowrulev2 = opacity 1.0 1.0, fullscreen:1

workspace = r[1-6], persistent:true
workspace = 1, monitor:DP-3, default:true
workspace = r[1-3], monitor:DP-3
workspace = 4, monitor:HDMI-A-1, default:true
workspace = r[4-6], monitor:HDMI-A-1
workspace = special:music, on-created-empty:deadbeef
workspace = special:terminal, on-created-empty:$terminal
workspace = special:fullscreenGame
animation = workspaces,1,4,default,slidefadevert
windowrulev2 = workspace 4 silent, class:^(discord)$

======Config-End========
```

</details>

### Description

The first person camera doesn't move in Apex Legends, because cursor capture/lock doesn't work on Hyprland. The cursor is hidden, but freely moves to the second monitor for example. It works on Plasma 6.1.3. Only way to make it work on Hyprland is to change to windowed mode and then change back to borderless fullscreen mode. For some reason this leaves my bar visible and the mouse capture works. If I set fullscreen or borderless mode again after this, the bar is not visible anymore and mouse capture is broken. The reason I set this bug report as a regression is that it works on Hyprland 0.40, if I reapply the fullscreen mode in settings. On that version, it also works in windowed mode. 

### How to reproduce

1. Go to Firing range (or in game)
2. First person camera doesn't move

**Comment by vaxerski** [comment]
can you try fake fullscreening it then?

Sounds like an apex bug...

`fullscreenstate, 2 0`

**Comment by Cloudperry** [comment]
I can get it working with setting the game to windowed mode and then setting fake fullscreen, but its not consistent at all. First time I tried it, mouse capture was still broken after fakefullscreening Apex, but it suddenly worked after switching focus to second monitor and back. Now I can't get it to work reliably.

Apex might be doing something weird, but there is clearly a Hyprland bug, because Plasma has no problems and this has never happened on Windows. I could try different Proton versions, but I don't think that would change anything.

**Comment by MightyPlaza** [comment]
if it's a regression bisect

**Comment by Cloudperry** [comment]
Not really worth bisecting as Hyprland 0.40 is quite old by now and the problem is only slightly less jank on that version. I shouldn't have to do any manual reapplying of game settings to get it to work, because it works on Plasma without reapplying fullscreen.

**Comment by MightyPlaza** [comment]
does it work on sway?

**Comment by vikingnope** [comment]
Same issue here

**Comment by vikingnope** [comment]
There is a bug in the game where you have to stay alt tabbing for it to recognize the mouse input at times, so maybe that is attributing to this issue?

**Comment by Cloudperry** [comment]
Newest version of what fixed it? I still have it with latest git Hyprland and latest Proton experimental bleeding edge. Fakefullscreen workaround still works ofc.

**Comment by einCyberSimon** [comment]
For me it works with the latest `-git` Hyprland Version and Proton Experimental. My start options only contain `-dx12`

**Comment by MrSn0wy** [comment]
I have the same issue here, game doesn't capture my mouse at all when in-game (it does work in menus). i'm using the latest hyprland git and proton experimental. Also setting it to windowed and enabling fake fullscreen doesn't work for me, it still refuses to lock my cursor.

**Comment by vikingnope** [comment]
> I have the same issue here, game doesn't capture my mouse at all when in-game (it does work in menus). i'm using the latest hyprland git and proton experimental. Also setting it to windowed and enabling fake fullscreen doesn't work for me, it still refuses to lock my cursor.

aur/hyprland-git package is still on version 0.41.2, so we wait for an update then we check again, same with extra/hyprland package

**Comment by vaxerski** [comment]
> aur/hyprland-git package is still on version 0.41.2, so we wait for an update then we check again, same with extra/hyprland package

hyprland-git always pulls the source, it's not outdated. The version is irrelevant. Please read the arch wiki next time.

**Comment by EnderSpy29** [comment]
> For me it works with the latest `-git` Hyprland Version and Proton Experimental. My start options only contain `-dx12`

why dx12? does it perform better?

Unrelated to your comment i am having the same issues and have found that unplugging my mouse and then changing workspaces a tonne works sometimes?

**Comment by bodby** [comment]
I fixed this by resizing the window while in borderless (not using the in-game settings menu, I mean drag clicking a corner) while paused and then it would capture my mouse again. The game would also fix the resolution after entering a match, but I usually just resize the window by a pixel so it isn't noticeable. Haven't updated to 0.42.0 yet though.

**Comment by einCyberSimon** [comment]
> > For me it works with the latest `-git` Hyprland Version and Proton Experimental. My start options only contain `-dx12`
> 
> why dx12? does it perform better?
> 
> Unrelated to your comment i am having the same issues and have found that unplugging my mouse and then changing workspaces a tonne works sometimes?

So it is quite unreliable for me. I cannot get it to work with dx12 anymore. For dx11 the above described fixes work sometimes :upside_down_face:

I tried using dx12 as it was mentioned that it by now should perform better for most users in some Apex patchnotes.

**Comment by MrSn0wy** [comment]
It appears that iI'm also having this issue in other games, one i just had it with was death stranding: directors cut. Cursor just refuses to lock. Also for some reason it seems to capture the mouse input properly if i put it on my first monitor instead of on my second, however the mouse locking still doesn't work.

**Comment by stojanov** [comment]
what worked for me is to change the workspace that the game is running on

**Comment by vikingnope** [comment]
Issue seems to be fixed now with today's game update for me.

**Comment by Cloudperry** [comment]
Yeah its fixed by a game update. Also Apex is now fullscreening properly. Previous versions left my bar on top of Apex when it fullscreened.

Closing this bug, but idk why it never happened on KDE.
