### ISSUE TITLE
SteamVR fails to DRM lease display

### ISSUE THREAD

**Issue by darkwater** [hyprwm/Hyprland#7776]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 118be4dea048df88fd21b84580fe62950c868c8f  (+++ b/src/managers/input/TextInput.cpp).
Date: Thu Sep 12 18:41:24 2024
Tag: v0.43.0-19-g118be4de, commits: 5215

flags: (if any)


System Information:
System name: Linux
Node name: tetsuya
Release: 6.10.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 10 Sep 2024 15:17:22 +0000


GPU information: 
0b:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev c4) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

======Config-Start======


Config File: /home/dark/.config/hypr/hyprland.conf: Read Succeeded
# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/plugins.conf

#debug:disable_logs = false
#debug:enable_stdout_logs = true
#debug:overlay = true


# MONITORS
# https://wiki.hyprland.org/Configuring/Monitors/

# nagumo
monitor = eDP-1, 2560x1600@165, 0x0, 1.6
monitor = desc:Iiyama North America PL3466WQ 0000000000000, 3440x1440@60, -640x-1440, 1.0
input:touchdevice:output = eDP-1
input:tablet:output = eDP-1

# tetsuya
monitor = DP-1, 2560x1440@144, 0x0, 1.0
monitor = DP-3, 2560x1440@144, 2560x0, 1.0
monitor = HDMI-A-1, disable
#monitor = HDMI-A-1, 2560x1440@60, 0x0, 1.0, mirror, DP-1
monitor = DP-2, disable # hmd

xwayland:force_zero_scaling = true
# env = GDK_SCALE,1.6
env = XCURSOR_SIZE,24


# AUTOSTART
exec-once = hypridle
exec-once = hyprpaper
exec-once = hyprpm reload
exec-once = autorestart fdls
exec-once = autorestart fprint-prompt
exec-once = autorestart wvkbd-mobintl --hidden
exec-once = sleep 5s; openrgb -p pride

# exec = gsettings set org.gnome.desktop.interface gtk-theme "Breeze-Dark"    # GTK3
# exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" # GTK4
# env = QT_QPA_PLATFORMTHEME,qt6ct                                            # Qt
env = GTK_THEME,Adwaita:dark
env = GTK2_RC_FILES,/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc
env = QT_STYLE_OVERRIDE,Adwaita-Dark


# ENVIRONMENT VARIABLES
# https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket
env = HYPRCURSOR_THEME,rose-pine-hyprcursor


# LOOK AND FEEL
# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 5
    gaps_out = 20

    border_size = 1

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(33eeffee) rgba(33ccffee) 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true 

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 6

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 6
        passes = 2
        vibrancy = 0.1696
        special = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.00

    animation = windows, 1, 2, default
    animation = windowsOut, 1, 2, default, popin 80%
    animation = border, 1, 2, default
    animation = borderangle, 1, 2, default
    animation = fade, 1, 2, default
    animation = workspaces, 1, 2, default
    animation = specialWorkspace, 1, 2, default, slidefadevert
}

# https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true
    preserve_split = true
}

# https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    new_status = slave
    mfact = 0.6
    always_center_master = true
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    #force_default_wallpaper = 0
    #disable_hyprland_logo = false
    #disable_splash_rendering = true

    vfr = true
    vrr = 1
}


Config File: /home/dark/.config/hypr/keybinds.conf: Read Succeeded
bind = SUPER, Return, exec, kitty
bind = SUPER SHIFT, XF86TouchpadOff, exec, kitty

bind = SUPER, M, exec, gtk-launch firefox
bind = SUPER, N, exec, gtk-launch neovide
bind = SUPER, R, exec, wofi --show drun
bind = SUPER, T, exec, gtk-launch org.telegram.desktop.desktop
bind = SUPER SHIFT, T, exec, gtk-launch discord
bind = , Print, exec, sh -c 'grim -g "$(slurp)" - | wl-copy'

bind = SUPER CTRL, Q, exec, hyprlock
bind = , XF86PowerOff, exec, hyprlock

bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.2 @DEFAULT_AUDIO_SINK@ 10%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume -l 1.2 @DEFAULT_AUDIO_SINK@ 10%-


bind = SUPER, Q, killactive,
bind = SUPER SHIFT, X, exit, # quit hyprland
bind = SUPER, G, togglefloating,
bind = SUPER, F, fullscreen,

# dwindle
bind = SUPER, P, pseudo,
bind = SUPER, V, togglesplit,

# master
bind = SUPER, V, layoutmsg, orientationcycle left top center

# Move focus with mainMod + arrow keys
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Move windows with mainMod + SHIFT + arrow keys
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

bind = SUPER SHIFT, M, movecurrentworkspacetomonitor, +1

# Resize windows with mainMod + ALT + arrow keys
binde = SUPER ALT, H, resizeactive, -64 0
binde = SUPER ALT, L, resizeactive, 64 0
binde = SUPER ALT, K, resizeactive, 0 -64
binde = SUPER ALT, J, resizeactive, 0 64

# Switch workspaces with mainMod + [0-9]
bind = SUPER, grave, workspace, previous
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = SUPER SHIFT, grave, movetoworkspace, previous
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = SUPER, S, togglespecialworkspace, magic
bind = SUPER SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow



Config File: /home/dark/.config/hypr/input.conf: Read Succeeded
#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = ctrl:nocaps
    kb_rules =

    repeat_rate = 25
    repeat_delay = 200

    follow_mouse = 1

    sensitivity = -0.15 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        scroll_factor = 0.3
    }

    tablet {
        active_area_position = 0.0, 1.2
        active_area_size = 303.3889, 189.3
    }
}

device {
    name = steelseries-steelseries-sensei-ten
    sensitivity = -0.4
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = true
    workspace_swipe_distance = 400
    workspace_swipe_cancel_ratio = 0.10
    workspace_swipe_min_speed_to_force = 5
    workspace_swipe_touch = false
    workspace_swipe_direction_lock = false
    workspace_swipe_forever = false
}

cursor {
    hide_on_key_press = true
    hide_on_touch = true
}


Config File: /home/dark/.config/hypr/rules.conf: Read Succeeded
# https://wiki.hyprland.org/Configuring/Window-Rules/
# https://wiki.hyprland.org/Configuring/Workspace-Rules/

layerrule = blur, waybar
layerrule = blur, fdls
layerrule = blur, swaync
layerrule = blur, hoshi-launcher
layerrule = ignorealpha 0, fdls
layerrule = ignorealpha 0, swaync
layerrule = noanim, fprint-prompt
layerrule = noanim, swaync
layerrule = order -50, fdls
layerrule = order 100, wvkbd

windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = focusonactivate, title:Firefox

# workspace = m[DP-1], gapsout:20 20 0 20
# workspace = m[eDP-1], gapsout:20 20 0 20

workspace = 1, monitor:DP-1
workspace = 3, monitor:DP-3
workspace = 3, layoutopt:orientation:right


Config File: /home/dark/.config/hypr/plugins.conf: Read Succeeded
plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(000000)
        workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1

        enable_gesture = true # laptop touchpad
        gesture_fingers = 3  # 3 or 4
        gesture_distance = 120 # how far is the "max"
        gesture_positive = false # positive = swipe down. Negative = swipe up.
    }

    touch_gestures {
        # The default sensitivity is probably too low on tablet screens,
        # I recommend turning it up to 4.0
        sensitivity = 4.0

        # must be >= 3
        workspace_swipe_fingers = 4

        # switching workspaces by swiping from an edge, this is separate from workspace_swipe_fingers
        # and can be used at the same time
        # possible values: l, r, u, or d
        # to disable it set it to anything else
        workspace_swipe_edge = d

        # in milliseconds
        long_press_delay = 400

        hyprgrass-bind = , swipe:3:r, sendshortcut, ALT,Left,class:firefox
        hyprgrass-bind = , swipe:3:l, sendshortcut, ALT,Right,class:firefox
        hyprgrass-bind = , swipe:3:d, sendshortcut, CTRL,Page_Up,class:firefox
        hyprgrass-bind = , swipe:3:u, sendshortcut, CTRL,Page_Down,class:firefox
        hyprgrass-bind = , swipe:4:d, killactive
        hyprgrass-bind = , swipe:4:u, fullscreen
        hyprgrass-bindm = , longpress:2, movewindow
        hyprgrass-bindm = , longpress:3, resizewindow
        hyprgrass-bind = , edge:d:u, exec, pkill -USR2 wvkbd-mobintl

        experimental {
            # send proper cancel events to windows instead of hacky touch_up events,
            # NOT recommended as it crashed a few times, once it's stabilized I'll make it the default
            send_cancel = 0
        }
    }
}

======Config-End========
```

</details>

### Description

Upon starting SteamVR, it complains that it fails to connect to the headset display:

![image](https://github.com/user-attachments/assets/2ac79a83-a0f8-4237-9437-608caa734ddf)

Looking at the logs, it seems that it fails at DRM leasing the display:

```
Fri Sep 13 2024 16:38:58.920031 [Info] - HMD deviceUUID is b00000000
Fri Sep 13 2024 16:38:58.920056 [Info] - Tried to find direct display through Wayland: (nil)
Fri Sep 13 2024 16:38:58.920085 [Error] - CHmdWindowSDL: Failed to create direct mode surface
Fri Sep 13 2024 16:38:58.920145 [Error] - CHmdWindowSDL: VR requires direct mode.
Fri Sep 13 2024 16:38:58.920228 [Error] - Error making window!
Fri Sep 13 2024 16:38:58.945028 [Info] - Failed to kill gpu-trace
Fri Sep 13 2024 16:38:58.945125 [Info] - Failed to initialize compositor
Fri Sep 13 2024 16:38:58.945151 [Info] - Failed to start compositor: VRInitError_Compositor_CannotDRMLeaseDisplay
```

The same thing does work on Sway:

```
Fri Sep 13 2024 16:42:17.676063 [Info] - HMD deviceUUID is b00000000
Fri Sep 13 2024 16:42:17.676308 [Info] - Tried to find direct display through Wayland: 0x62ad3c4a9170
Fri Sep 13 2024 16:42:17.676327 [Info] - Trying to match desired rate of 90.000000Hz.
Fri Sep 13 2024 16:42:17.676340 [Info] - 15 modes on display:
Fri Sep 13 2024 16:42:17.676353 [Info] -  - 0: 2880x1600@90.003006Hz
Fri Sep 13 2024 16:42:17.676365 [Info] -  - ...
Fri Sep 13 2024 16:42:17.676539 [Info] - Selected mode 0.
Fri Sep 13 2024 16:42:17.697140 [Info] - Acquired drm display!
```

### How to reproduce

1. Connect a Valve Index or probably any other compatible HMD
2. Start Steam
3. Start SteamVR

### Crash reports, logs, images, videos

<details> <summary>logs/vrcompositor.txt on Hyprland</summary>

```
Fri Sep 13 2024 16:38:58.855611 [Info] - //==============================================================================================
Fri Sep 13 2024 16:38:58.855638 [Info] - ================================================================================================
Fri Sep 13 2024 16:38:58.855651 [Info] - ================================================================================================
Fri Sep 13 2024 16:38:58.855667 [Info] - vrcompositor 2.8.4 startup with PID=99685, config=/home/dark/.local/share/Steam/config, runtime=/home/dark/.local/share/Steam/steamapps/common/SteamVR, arch=linux64
Fri Sep 13 2024 16:38:58.855679 [Info] - VR compositor 2.8.4 (v1724204978) Mixed starting up
Fri Sep 13 2024 16:38:58.868426 [Info] - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to /steamvr/SteamVR_Namespace
Fri Sep 13 2024 16:38:58.868465 [Info] - CSharedResourceNamespaceClient::Init(): received namespace data 99070
Fri Sep 13 2024 16:38:58.868489 [Info] - CIPCPipe::CreatePipe(VR_CompositorPipe_99070) bound to /steamvr/VR_CompositorPipe_99070
Fri Sep 13 2024 16:38:58.869573 [Info] - Set fd limit to: 524288
Fri Sep 13 2024 16:38:58.870396 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/drivers/htc/resources/settings/default.vrsettings
Fri Sep 13 2024 16:38:58.870436 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/drivers/lighthouse/resources/settings/default.vrsettings
Fri Sep 13 2024 16:38:58.870470 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/drivers/null/resources/settings/default.vrsettings
Fri Sep 13 2024 16:38:58.870514 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/drivers/vrlink/resources/settings/default.vrsettings
Fri Sep 13 2024 16:38:58.870648 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/resources/settings/default.vrsettings
Fri Sep 13 2024 16:38:58.870934 [Info] - [Settings] Load Json Settings from /home/dark/.local/share/Steam/config/steamvr.vrsettings
Fri Sep 13 2024 16:38:58.872084 [Info] - Events created
Fri Sep 13 2024 16:38:58.872529 [Info] - Found bad mirror window settings: 
Fri Sep 13 2024 16:38:58.872547 [Info] - Creating CHmdWindowSDL!
Fri Sep 13 2024 16:38:58.872584 [Info] - CHmdWindowSDL: Using Wayland
Fri Sep 13 2024 16:38:58.891696 [Info] - WaylandHMDState: Got interface: wp_drm_lease_device_v1
Fri Sep 13 2024 16:38:58.892212 [Info] - WaylandHMDLeaseDevice::LeaseDevice_DrmFD: /dev/dri/card1
Fri Sep 13 2024 16:38:58.913132 [Info] - WaylandHMDLeaseDevice::LeaseDevice_Done
Fri Sep 13 2024 16:38:58.913861 [Info] - Instance layers available:
Fri Sep 13 2024 16:38:58.913880 [Info] -  - VK_LAYER_VALVE_steam_overlay_32, version 4206799
Fri Sep 13 2024 16:38:58.913893 [Info] -  - VK_LAYER_VALVE_steam_overlay_64, version 4206799
Fri Sep 13 2024 16:38:58.913912 [Info] -  - VK_LAYER_VALVE_steam_fossilize_32, version 4206799
Fri Sep 13 2024 16:38:58.913923 [Info] -  - VK_LAYER_VALVE_steam_fossilize_64, version 4206799
Fri Sep 13 2024 16:38:58.913934 [Info] -  - VK_LAYER_MANGOHUD_overlay_x86, version 4206592
Fri Sep 13 2024 16:38:58.913945 [Info] -  - VK_LAYER_MANGOAPP_overlay, version 4206592
Fri Sep 13 2024 16:38:58.913956 [Info] -  - VK_LAYER_MESA_device_select, version 4206803
Fri Sep 13 2024 16:38:58.913966 [Info] -  - VK_LAYER_FROG_gamescope_wsi_x86_64, version 4206813
Fri Sep 13 2024 16:38:58.913977 [Info] -  - VK_LAYER_MANGOHUD_overlay_x86_64, version 4206592
Fri Sep 13 2024 16:38:58.913988 [Info] -  - VK_LAYER_MANGOAPP_overlay, version 4206592
Fri Sep 13 2024 16:38:58.913999 [Info] -  - VK_LAYER_INTEL_nullhw, version 4198473
Fri Sep 13 2024 16:38:58.914010 [Info] -  - VK_LAYER_MESA_overlay, version 4206803
Fri Sep 13 2024 16:38:58.914720 [Info] - Instance extensions available:
Fri Sep 13 2024 16:38:58.914739 [Info] -  - VK_KHR_device_group_creation, version 1
Fri Sep 13 2024 16:38:58.914752 [Info] -  - VK_KHR_display, version 23
Fri Sep 13 2024 16:38:58.914763 [Info] -  - VK_KHR_external_fence_capabilities, version 1
Fri Sep 13 2024 16:38:58.914774 [Info] -  - VK_KHR_external_memory_capabilities, version 1
Fri Sep 13 2024 16:38:58.914785 [Info] -  - VK_KHR_external_semaphore_capabilities, version 1
Fri Sep 13 2024 16:38:58.914796 [Info] -  - VK_KHR_get_display_properties2, version 1
Fri Sep 13 2024 16:38:58.914807 [Info] -  - VK_KHR_get_physical_device_properties2, version 2
Fri Sep 13 2024 16:38:58.914818 [Info] -  - VK_KHR_get_surface_capabilities2, version 1
Fri Sep 13 2024 16:38:58.914829 [Info] -  - VK_KHR_surface, version 25
Fri Sep 13 2024 16:38:58.914840 [Info] -  - VK_KHR_surface_protected_capabilities, version 1
Fri Sep 13 2024 16:38:58.914851 [Info] -  - VK_KHR_wayland_surface, version 6
Fri Sep 13 2024 16:38:58.914862 [Info] -  - VK_KHR_xcb_surface, version 6
Fri Sep 13 2024 16:38:58.914873 [Info] -  - VK_KHR_xlib_surface, version 6
Fri Sep 13 2024 16:38:58.914883 [Info] -  - VK_EXT_acquire_drm_display, version 1
Fri Sep 13 2024 16:38:58.914894 [Info] -  - VK_EXT_acquire_xlib_display, version 1
Fri Sep 13 2024 16:38:58.914905 [Info] -  - VK_EXT_debug_report, version 10
Fri Sep 13 2024 16:38:58.914917 [Info] -  - VK_EXT_debug_utils, version 2
Fri Sep 13 2024 16:38:58.914928 [Info] -  - VK_EXT_direct_mode_display, version 1
Fri Sep 13 2024 16:38:58.914939 [Info] -  - VK_EXT_display_surface_counter, version 1
Fri Sep 13 2024 16:38:58.914950 [Info] -  - VK_EXT_headless_surface, version 1
Fri Sep 13 2024 16:38:58.914961 [Info] -  - VK_EXT_surface_maintenance1, version 1
Fri Sep 13 2024 16:38:58.914972 [Info] -  - VK_EXT_swapchain_colorspace, version 4
Fri Sep 13 2024 16:38:58.914983 [Info] -  - VK_KHR_portability_enumeration, version 1
Fri Sep 13 2024 16:38:58.914994 [Info] -  - VK_LUNARG_direct_driver_loading, version 1
Fri Sep 13 2024 16:38:58.915008 [Info] - SDL version: 2.30.7
Fri Sep 13 2024 16:38:58.915021 [Info] - Direct mode features: present
Fri Sep 13 2024 16:38:58.915033 [Info] - Requesting 10 instance extensions:
Fri Sep 13 2024 16:38:58.915044 [Info] -  - VK_KHR_surface
Fri Sep 13 2024 16:38:58.915055 [Info] -  - VK_KHR_xlib_surface
Fri Sep 13 2024 16:38:58.915066 [Info] -  - VK_KHR_display
Fri Sep 13 2024 16:38:58.915077 [Info] -  - VK_EXT_direct_mode_display
Fri Sep 13 2024 16:38:58.915088 [Info] -  - VK_EXT_display_surface_counter
Fri Sep 13 2024 16:38:58.915099 [Info] -  - VK_KHR_external_memory_capabilities
Fri Sep 13 2024 16:38:58.915111 [Info] -  - VK_KHR_external_semaphore_capabilities
Fri Sep 13 2024 16:38:58.915129 [Info] -  - VK_KHR_get_physical_device_properties2
Fri Sep 13 2024 16:38:58.915142 [Info] -  - VK_EXT_debug_utils
Fri Sep 13 2024 16:38:58.915153 [Info] -  - VK_EXT_acquire_drm_display
Fri Sep 13 2024 16:38:58.920031 [Info] - HMD deviceUUID is b00000000
Fri Sep 13 2024 16:38:58.920056 [Info] - Tried to find direct display through Wayland: (nil)
Fri Sep 13 2024 16:38:58.920085 [Error] - CHmdWindowSDL: Failed to create direct mode surface
Fri Sep 13 2024 16:38:58.920145 [Error] - CHmdWindowSDL: VR requires direct mode.
Fri Sep 13 2024 16:38:58.920228 [Error] - Error making window!
Fri Sep 13 2024 16:38:58.945028 [Info] - Failed to kill gpu-trace
Fri Sep 13 2024 16:38:58.945125 [Info] - Failed to initialize compositor
Fri Sep 13 2024 16:38:58.945151 [Info] - Failed to start compositor: VRInitError_Compositor_CannotDRMLeaseDisplay
```
</details>

<details> <summary>logs/vrcompositor.txt on Sway</summary>

```
Fri Sep 13 2024 16:42:17.623896 [Info] - //==============================================================================================
Fri Sep 13 2024 16:42:17.623923 [Info] - ================================================================================================
Fri Sep 13 2024 16:42:17.623938 [Info] - ================================================================================================
Fri Sep 13 2024 16:42:17.623954 [Info] - vrcompositor 2.8.4 startup with PID=101676, config=/home/dark/.local/share/Steam/config, runtime=/home/dark/.local/share/Steam/steamapps/common/SteamVR, arch=linux64
Fri Sep 13 2024 16:42:17.623967 [Info] - VR compositor 2.8.4 (v1724204978) Mixed starting up
Fri Sep 13 2024 16:42:17.634105 [Info] - CIPCPipe::ConnectPipe(SteamVR_Namespace) attempting connect to /steamvr/SteamVR_Namespace
Fri Sep 13 2024 16:42:17.634151 [Info] - CSharedResourceNamespaceClient::Init(): received namespace data 101638
Fri Sep 13 2024 16:42:17.634175 [Info] - CIPCPipe::CreatePipe(VR_CompositorPipe_101638) bound to /steamvr/VR_CompositorPipe_101638
Fri Sep 13 2024 16:42:17.634960 [Info] - Set fd limit to: 524288
Fri Sep 13 2024 16:42:17.635696 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/drivers/htc/resources/settings/default.vrsettings
Fri Sep 13 2024 16:42:17.635738 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/drivers/lighthouse/resources/settings/default.vrsettings
Fri Sep 13 2024 16:42:17.635773 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/drivers/null/resources/settings/default.vrsettings
Fri Sep 13 2024 16:42:17.635817 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/drivers/vrlink/resources/settings/default.vrsettings
Fri Sep 13 2024 16:42:17.635951 [Info] - [Settings] Load Default Json Settings from /home/dark/.local/share/Steam/steamapps/common/SteamVR/resources/settings/default.vrsettings
Fri Sep 13 2024 16:42:17.636221 [Info] - [Settings] Load Json Settings from /home/dark/.local/share/Steam/config/steamvr.vrsettings
Fri Sep 13 2024 16:42:17.637070 [Info] - Events created
Fri Sep 13 2024 16:42:17.637504 [Info] - Found bad mirror window settings: 
Fri Sep 13 2024 16:42:17.637523 [Info] - Creating CHmdWindowSDL!
Fri Sep 13 2024 16:42:17.637563 [Info] - CHmdWindowSDL: Using Wayland
Fri Sep 13 2024 16:42:17.655994 [Info] - WaylandHMDState: Got interface: wp_drm_lease_device_v1
Fri Sep 13 2024 16:42:17.656500 [Info] - WaylandHMDLeaseDevice::LeaseDevice_DrmFD: /dev/dri/card1
Fri Sep 13 2024 16:42:17.669135 [Info] - WaylandHMDLeaseConnector::LeaseConnector_Done
Fri Sep 13 2024 16:42:17.669170 [Info] - WaylandHMDLeaseDevice::LeaseDevice_Done
Fri Sep 13 2024 16:42:17.670079 [Info] - Instance layers available:
Fri Sep 13 2024 16:42:17.670097 [Info] -  - VK_LAYER_VALVE_steam_overlay_32, version 4206799
Fri Sep 13 2024 16:42:17.670109 [Info] -  - VK_LAYER_VALVE_steam_overlay_64, version 4206799
Fri Sep 13 2024 16:42:17.670126 [Info] -  - VK_LAYER_VALVE_steam_fossilize_32, version 4206799
Fri Sep 13 2024 16:42:17.670138 [Info] -  - VK_LAYER_VALVE_steam_fossilize_64, version 4206799
Fri Sep 13 2024 16:42:17.670149 [Info] -  - VK_LAYER_MANGOHUD_overlay_x86, version 4206592
Fri Sep 13 2024 16:42:17.670160 [Info] -  - VK_LAYER_MANGOAPP_overlay, version 4206592
Fri Sep 13 2024 16:42:17.670171 [Info] -  - VK_LAYER_MESA_device_select, version 4206803
Fri Sep 13 2024 16:42:17.670182 [Info] -  - VK_LAYER_FROG_gamescope_wsi_x86_64, version 4206813
Fri Sep 13 2024 16:42:17.670202 [Info] -  - VK_LAYER_MANGOHUD_overlay_x86_64, version 4206592
Fri Sep 13 2024 16:42:17.670214 [Info] -  - VK_LAYER_MANGOAPP_overlay, version 4206592
Fri Sep 13 2024 16:42:17.670226 [Info] -  - VK_LAYER_INTEL_nullhw, version 4198473
Fri Sep 13 2024 16:42:17.670237 [Info] -  - VK_LAYER_MESA_overlay, version 4206803
Fri Sep 13 2024 16:42:17.670965 [Info] - Instance extensions available:
Fri Sep 13 2024 16:42:17.670982 [Info] -  - VK_KHR_device_group_creation, version 1
Fri Sep 13 2024 16:42:17.670994 [Info] -  - VK_KHR_display, version 23
Fri Sep 13 2024 16:42:17.671006 [Info] -  - VK_KHR_external_fence_capabilities, version 1
Fri Sep 13 2024 16:42:17.671017 [Info] -  - VK_KHR_external_memory_capabilities, version 1
Fri Sep 13 2024 16:42:17.671028 [Info] -  - VK_KHR_external_semaphore_capabilities, version 1
Fri Sep 13 2024 16:42:17.671039 [Info] -  - VK_KHR_get_display_properties2, version 1
Fri Sep 13 2024 16:42:17.671051 [Info] -  - VK_KHR_get_physical_device_properties2, version 2
Fri Sep 13 2024 16:42:17.671062 [Info] -  - VK_KHR_get_surface_capabilities2, version 1
Fri Sep 13 2024 16:42:17.671073 [Info] -  - VK_KHR_surface, version 25
Fri Sep 13 2024 16:42:17.671084 [Info] -  - VK_KHR_surface_protected_capabilities, version 1
Fri Sep 13 2024 16:42:17.671095 [Info] -  - VK_KHR_wayland_surface, version 6
Fri Sep 13 2024 16:42:17.671107 [Info] -  - VK_KHR_xcb_surface, version 6
Fri Sep 13 2024 16:42:17.671123 [Info] -  - VK_KHR_xlib_surface, version 6
Fri Sep 13 2024 16:42:17.671134 [Info] -  - VK_EXT_acquire_drm_display, version 1
Fri Sep 13 2024 16:42:17.671146 [Info] -  - VK_EXT_acquire_xlib_display, version 1
Fri Sep 13 2024 16:42:17.671157 [Info] -  - VK_EXT_debug_report, version 10
Fri Sep 13 2024 16:42:17.671168 [Info] -  - VK_EXT_debug_utils, version 2
Fri Sep 13 2024 16:42:17.671180 [Info] -  - VK_EXT_direct_mode_display, version 1
Fri Sep 13 2024 16:42:17.671191 [Info] -  - VK_EXT_display_surface_counter, version 1
Fri Sep 13 2024 16:42:17.671202 [Info] -  - VK_EXT_headless_surface, version 1
Fri Sep 13 2024 16:42:17.671213 [Info] -  - VK_EXT_surface_maintenance1, version 1
Fri Sep 13 2024 16:42:17.671224 [Info] -  - VK_EXT_swapchain_colorspace, version 4
Fri Sep 13 2024 16:42:17.671236 [Info] -  - VK_KHR_portability_enumeration, version 1
Fri Sep 13 2024 16:42:17.671247 [Info] -  - VK_LUNARG_direct_driver_loading, version 1
Fri Sep 13 2024 16:42:17.671260 [Info] - SDL version: 2.30.7
Fri Sep 13 2024 16:42:17.671274 [Info] - Direct mode features: present
Fri Sep 13 2024 16:42:17.671286 [Info] - Requesting 10 instance extensions:
Fri Sep 13 2024 16:42:17.671297 [Info] -  - VK_KHR_surface
Fri Sep 13 2024 16:42:17.671308 [Info] -  - VK_KHR_xlib_surface
Fri Sep 13 2024 16:42:17.671320 [Info] -  - VK_KHR_display
Fri Sep 13 2024 16:42:17.671331 [Info] -  - VK_EXT_direct_mode_display
Fri Sep 13 2024 16:42:17.671342 [Info] -  - VK_EXT_display_surface_counter
Fri Sep 13 2024 16:42:17.671354 [Info] -  - VK_KHR_external_memory_capabilities
Fri Sep 13 2024 16:42:17.671365 [Info] -  - VK_KHR_external_semaphore_capabilities
Fri Sep 13 2024 16:42:17.671376 [Info] -  - VK_KHR_get_physical_device_properties2
Fri Sep 13 2024 16:42:17.671387 [Info] -  - VK_EXT_debug_utils
Fri Sep 13 2024 16:42:17.671398 [Info] -  - VK_EXT_acquire_drm_display
Fri Sep 13 2024 16:42:17.676063 [Info] - HMD deviceUUID is b00000000
Fri Sep 13 2024 16:42:17.676308 [Info] - Tried to find direct display through Wayland: 0x62ad3c4a9170
Fri Sep 13 2024 16:42:17.676327 [Info] - Trying to match desired rate of 90.000000Hz.
Fri Sep 13 2024 16:42:17.676340 [Info] - 15 modes on display:
Fri Sep 13 2024 16:42:17.676353 [Info] -  - 0: 2880x1600@90.003006Hz
Fri Sep 13 2024 16:42:17.676365 [Info] -  - 1: 2880x1600@144.000000Hz
Fri Sep 13 2024 16:42:17.676377 [Info] -  - 2: 2880x1600@120.019005Hz
Fri Sep 13 2024 16:42:17.676389 [Info] -  - 3: 2880x1600@79.999001Hz
Fri Sep 13 2024 16:42:17.676400 [Info] -  - 4: 1920x1200@90.003006Hz
Fri Sep 13 2024 16:42:17.676412 [Info] -  - 5: 1920x1080@90.003006Hz
Fri Sep 13 2024 16:42:17.676433 [Info] -  - 6: 1600x1200@90.003006Hz
Fri Sep 13 2024 16:42:17.676446 [Info] -  - 7: 1680x1050@90.003006Hz
Fri Sep 13 2024 16:42:17.676458 [Info] -  - 8: 1280x1024@90.003006Hz
Fri Sep 13 2024 16:42:17.676470 [Info] -  - 9: 1440x900@90.003006Hz
Fri Sep 13 2024 16:42:17.676481 [Info] -  - 10: 1280x800@90.003006Hz
Fri Sep 13 2024 16:42:17.676493 [Info] -  - 11: 1280x720@90.003006Hz
Fri Sep 13 2024 16:42:17.676505 [Info] -  - 12: 1024x768@90.003006Hz
Fri Sep 13 2024 16:42:17.676516 [Info] -  - 13: 800x600@90.003006Hz
Fri Sep 13 2024 16:42:17.676528 [Info] -  - 14: 640x480@90.003006Hz
Fri Sep 13 2024 16:42:17.676539 [Info] - Selected mode 0.
Fri Sep 13 2024 16:42:17.697140 [Info] - Acquired drm display!
Fri Sep 13 2024 16:42:17.697170 [Info] - Direct mode surface: 0x62ad3c43e6a0
Fri Sep 13 2024 16:42:17.697202 [Info] - Requesting 19 device extensions:
Fri Sep 13 2024 16:42:17.697218 [Info] -  - VK_EXT_custom_border_color
Fri Sep 13 2024 16:42:17.697233 [Info] -  - VK_EXT_extended_dynamic_state
Fri Sep 13 2024 16:42:17.697247 [Info] -  - VK_EXT_host_query_reset
Fri Sep 13 2024 16:42:17.697261 [Info] -  - VK_KHR_create_renderpass2
Fri Sep 13 2024 16:42:17.697276 [Info] -  - VK_KHR_dedicated_allocation
Fri Sep 13 2024 16:42:17.697290 [Info] -  - VK_KHR_external_memory
Fri Sep 13 2024 16:42:17.697304 [Info] -  - VK_KHR_external_memory_fd
Fri Sep 13 2024 16:42:17.697318 [Info] -  - VK_KHR_external_semaphore
Fri Sep 13 2024 16:42:17.697332 [Info] -  - VK_KHR_external_semaphore_fd
Fri Sep 13 2024 16:42:17.697346 [Info] -  - VK_KHR_get_memory_requirements2
Fri Sep 13 2024 16:42:17.697360 [Info] -  - VK_KHR_image_format_list
Fri Sep 13 2024 16:42:17.697375 [Info] -  - VK_KHR_maintenance1
Fri Sep 13 2024 16:42:17.697389 [Info] -  - VK_KHR_sampler_ycbcr_conversion
Fri Sep 13 2024 16:42:17.697403 [Info] -  - VK_KHR_swapchain
Fri Sep 13 2024 16:42:17.697417 [Info] -  - VK_KHR_swapchain_mutable_format
Fri Sep 13 2024 16:42:17.697431 [Info] -  - VK_KHR_timeline_semaphore
Fri Sep 13 2024 16:42:17.697445 [Info] -  - VK_EXT_display_control
Fri Sep 13 2024 16:42:17.697459 [Info] -  - VK_KHR_external_memory_fd
Fri Sep 13 2024 16:42:17.697473 [Info] -  - VK_KHR_external_semaphore_fd
Fri Sep 13 2024 16:42:17.697488 [Info] - Global priority query enabled: 1
Fri Sep 13 2024 16:42:17.697503 [Info] - Async support disabled by user setting
Fri Sep 13 2024 16:42:17.703300 [Info] - m_pVkInstance : 0x62ad3c4b5460
Fri Sep 13 2024 16:42:17.703324 [Info] - m_pVkPhysicalDevice : 0x62ad3c4c2eb0
Fri Sep 13 2024 16:42:17.703339 [Info] - m_pVkDevice : 0x62ad3c5d9380
Fri Sep 13 2024 16:42:17.703351 [Info] - m_pVkGraphicsQueue : 0x62ad3c41e2c0
Fri Sep 13 2024 16:42:17.703363 [Info] - m_pVkComputeQueue : 0x62ad3c5eb220
Fri Sep 13 2024 16:42:17.703377 [Info] - HMD swapchain mode:2 count:3
Fri Sep 13 2024 16:42:17.703713 [Info] - Direct mode: enabled
Fri Sep 13 2024 16:42:17.704205 [Info] - Mirror swapchain mode:0 count:4
Fri Sep 13 2024 16:42:17.706240 [Info] - CGraphicsDevice Init...
Fri Sep 13 2024 16:42:17.706514 [Info] - Headset is using direct mode
Fri Sep 13 2024 16:42:17.706532 [Info] - Initializing timing resources
Fri Sep 13 2024 16:42:17.706596 [Info] - Using Vulkan Renderer
Fri Sep 13 2024 16:42:17.706620 [Info] - Initializing CVulkanVRRenderer
Fri Sep 13 2024 16:42:17.706642 [Info] - Debug markers: disabled, missing extension support. Is the Renderdoc layer enabled?
Fri Sep 13 2024 16:42:17.721952 [Info] - Initialized Vulkan transfer ring buffer, mapped at offset 0x0x7cc4bfe1f000.
Fri Sep 13 2024 16:42:17.722396 [Info] - Supports dmabuf formats + modifiers? - Yes!
Fri Sep 13 2024 16:42:17.722449 [Info] - Updated HMD Prop_DisplayFrequency_Float to 90.000000
Fri Sep 13 2024 16:42:17.722632 [Info] - ****************************************** Begin GPU speed ******************************************
Fri Sep 13 2024 16:42:17.722648 [Info] - GPU Vendor: "AMD Radeon RX 5700 (RADV NAVI10)" GPU Driver: "100671490"
Fri Sep 13 2024 16:42:17.722774 [Info] - Initializing CVulkanVRRenderer
Fri Sep 13 2024 16:42:17.722814 [Info] - Debug markers: disabled, missing extension support. Is the Renderdoc layer enabled?
Fri Sep 13 2024 16:42:17.738432 [Info] - Initialized Vulkan transfer ring buffer, mapped at offset 0x0x7cc4afe1f000.
Fri Sep 13 2024 16:42:17.738953 [Info] - Supports dmabuf formats + modifiers? - Yes!
Fri Sep 13 2024 16:42:17.789494 [Info] - MeasureGpuMegaPixelsPerSecond(0): Returning 680 MP/sec. Total CPU time 0.07 seconds.
Fri Sep 13 2024 16:42:17.790301 [Info] - GPU speed from average of 2 median samples: 697
Fri Sep 13 2024 16:42:17.790569 [Info] - ******************************************* End GPU speed *******************************************
Fri Sep 13 2024 16:42:17.790624 [Info] - HMD driver recommended: 2016x2240 90.0Hz HiddenArea(24.88%) = 610 MP/sec
Fri Sep 13 2024 16:42:17.790641 [Info] - Raw ideal render target scale = 1.14
Fri Sep 13 2024 16:42:17.790734 [Info] - New result of GetRecommendedRenderTargetSize for current app: 2152x2392
Fri Sep 13 2024 16:42:17.790752 [Info] - Creating samplers
Fri Sep 13 2024 16:42:17.790767 [Info] - Creating util resources
Fri Sep 13 2024 16:42:17.790978 [Info] - Creating constant buffers
Fri Sep 13 2024 16:42:17.791843 [Info] - Creating systemlayer textures (w=2152,h=2392)
Fri Sep 13 2024 16:42:17.793277 [Info] - Creating/Updating distortion surfaces (mesh resolution 49)
Fri Sep 13 2024 16:42:17.828411 [Info] - Warp mesh (left eye) covers 82.03% of its viewport (shrink wrap saved 1.87%)
Fri Sep 13 2024 16:42:17.863514 [Info] - Warp mesh (right eye) covers 82.03% of its viewport (shrink wrap saved 1.96%)
Fri Sep 13 2024 16:42:17.914721 [Info] - Initializing camera
Fri Sep 13 2024 16:42:17.914750 [Info] - Tracked Camera: Unexpected or not-specified number of cameras (propertyError=0, 0).
Fri Sep 13 2024 16:42:17.914764 [Info] - D3D11 Camera Initialization failure.
Fri Sep 13 2024 16:42:17.914797 [Info] - Done initializing CGraphicsDevice resources
Fri Sep 13 2024 16:42:17.914813 [Info] - Loading MC resources
Fri Sep 13 2024 16:42:17.914958 [Info] - Distort initialized
Fri Sep 13 2024 16:42:17.916147 [Info] - Loading background skybox texture async '/home/dark/.local/share/Steam/steamapps/common/SteamVR/resources/backgrounds/aurorasky.png'
Fri Sep 13 2024 16:42:17.916166 [Info] - Loading reflection skybox texture async '/home/dark/.local/share/Steam/steamapps/common/SteamVR/resources/reflections/dashboard_lights.png'
Fri Sep 13 2024 16:42:17.918471 [Info] - Set thread 0x7cc4ea2006c0 priority to: -15
Fri Sep 13 2024 16:42:17.918569 [Info] - External connection from /home/dark/.local/share/Steam/ubuntu12_32/steam 100878
Fri Sep 13 2024 16:42:17.918618 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrstartup 101566
Fri Sep 13 2024 16:42:17.918990 [Info] - Set thread 0x7cc4e97fd6c0 priority to: 15
Fri Sep 13 2024 16:42:17.919095 [Info] - Compositor render thread started
Fri Sep 13 2024 16:42:17.919122 [Info] - Set thread 0x7cc4ea3fd6c0 priority to: 15
Fri Sep 13 2024 16:42:17.919156 [Info] - Startup Complete (0.284175 seconds)
Fri Sep 13 2024 16:42:17.987958 [Info] - External connection from /home/dark/.local/share/Steam/ubuntu12_64/steamwebhelper 101118
Fri Sep 13 2024 16:42:18.034101 [Error] - Unflushed events requested in CGpuTiming::GetDeltas!
Fri Sep 13 2024 16:42:18.358483 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrdashboard 101735
Fri Sep 13 2024 16:42:20.403232 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrmonitor 101751
Fri Sep 13 2024 16:42:21.249307 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/steamtours 101802
Fri Sep 13 2024 16:42:21.462822 [Info] - Socket closed
Fri Sep 13 2024 16:42:21.462870 [Info] - Unable to read message from socket: 0
Fri Sep 13 2024 16:42:21.462903 [Info] - Process vrstartup (101566) disconnected (Thread(0x0x7cc4b0001d50/0x0x7c)
Fri Sep 13 2024 16:42:21.462924 [Info] - Lost pipe connection from vrstartup (101566)
Fri Sep 13 2024 16:42:22.575353 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper 101883
Fri Sep 13 2024 16:42:22.935837 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper 102091
Fri Sep 13 2024 16:42:22.942387 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper 102101
Fri Sep 13 2024 16:42:22.945831 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper 102085
Fri Sep 13 2024 16:42:25.035192 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper 102099
Fri Sep 13 2024 16:42:25.431674 [Info] - Clearing dashboard transform because ChaperoneUniverseHasChanged (old 0 new 1726237893)
Fri Sep 13 2024 16:42:25.462465 [Info] - OnMbox_SetDashboardVisibility {
   "reason" : "transition_app_quitting",
   "type" : "set_dashboard_visibility",
   "visible" : false
}
Fri Sep 13 2024 16:42:26.567195 [Info] - Socket closed
Fri Sep 13 2024 16:42:26.567229 [Info] - Unable to read message from socket: 0
Fri Sep 13 2024 16:42:26.567256 [Info] - Process steamtours (101802) disconnected (Thread(0x0x7cc4b0005770/0x0x7c)
Fri Sep 13 2024 16:42:26.567274 [Info] - Lost pipe connection from steamtours (101802)
Fri Sep 13 2024 16:42:26.567299 [Info] - Clearing forced interleaved reprojection on (pid=101802)
Fri Sep 13 2024 16:42:26.567317 [Info] - ######################################################################
Fri Sep 13 2024 16:42:26.567332 [Info] - Cumulative stats for pid: 101802
Fri Sep 13 2024 16:42:26.567346 [Info] - Total..................   469 presents.    0 dropped.    0 reprojected
Fri Sep 13 2024 16:42:26.567361 [Info] - Startup................   469 presents.    0 dropped.    0 reprojected
Fri Sep 13 2024 16:42:26.567375 [Info] - Loading...  0 total....     0 presents.    0 dropped.    0 reprojected
Fri Sep 13 2024 16:42:26.567389 [Info] - Timed out.  0 total....     0 presents.    0 dropped.    0 reprojected
Fri Sep 13 2024 16:42:26.567403 [Info] - Compositor Time........CPU: 3.969ms / GPU: 2.029ms
Fri Sep 13 2024 16:42:26.567419 [Info] - Game Info..............FPS Average Target 90  ApplicationTime CPU: 0.000ms / GPU: 2.229ms
Fri Sep 13 2024 16:42:26.567433 [Info] - ######################################################################
Fri Sep 13 2024 16:42:26.567447 [Info] - Total dropped frames: 686
Fri Sep 13 2024 16:42:27.024421 [Info] - External connection from /home/dark/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup 102533
Fri Sep 13 2024 16:42:27.207043 [Info] - Screenshot: HookScreenshot, 1 types
Fri Sep 13 2024 16:42:27.324502 [Info] - Processing message VRMsg_CompositorNewSharedSemaphore from steamvr_room_setup (102533) took 0.0102 seconds
Fri Sep 13 2024 16:42:28.354938 [Info] - Clearing dashboard transform because timed out
Fri Sep 13 2024 16:42:32.504727 [Info] - Socket closed
Fri Sep 13 2024 16:42:32.504771 [Info] - Unable to read message from socket: 0
Fri Sep 13 2024 16:42:32.504803 [Info] - Process vrdashboard (101735) disconnected (Thread(0x0x7cc4b0003a60/0x0x7c)
Fri Sep 13 2024 16:42:32.504824 [Info] - Lost pipe connection from vrdashboard (101735)
Fri Sep 13 2024 16:42:32.572489 [Info] - Socket closed
Fri Sep 13 2024 16:42:32.572542 [Info] - Unable to read message from socket: 3
Fri Sep 13 2024 16:42:32.572583 [Info] - Process steamvr_room_setup (102533) disconnected (Thread(0x0x7cc4b000a0e0/0x0x7c)
Fri Sep 13 2024 16:42:32.572609 [Info] - Lost pipe connection from steamvr_room_setup (102533)
...
```
</details>

**Comment by darkwater** [comment]
Looks like #6949 is related, although xwayland only crashes for me with HMD connected in debug builds, not in release builds.

**Comment by podiki** [comment]
My guess is because you disable the HMD in the config, so it is not available to XWayland either? Though with it enabled XWayland doesn't start or crashes as per #6949. Did it work like this before (with HMD disabled in Hyprland config)?

**Comment by darkwater** [comment]
I put “yes” for regression because I’ve heard SteamVR has worked on Hyprland (it’s even listed on a Steam support page as supported), but I haven’t tried it before myself

**Comment by vaxerski** [comment]
I can't debug this as I don't own any VR stuff. If someone else can and has the know-how, feel free. The regressor is the aq merge

**Comment by podiki** [comment]
@vaxerski any pointers or tips to get started? Unfortunately I'm not familiar with the internals of wayland/xwayland and hyprland, but willing to try to investigate. Is there some output or things we can do on hyprland's end to give us more useful information? Or in something else? Probably looking into the DRM leasing and what's different from pre-aquamarine and after?

**Comment by vaxerski** [comment]
> Probably looking into the DRM leasing and what's different from pre-aquamarine and after?

that's what I would do, knowing me I just made a typo somewhere

**Comment by podiki** [comment]
Just to link here, with the patch from https://github.com/hyprwm/Hyprland/issues/6949#issuecomment-2408644324 I can keep the HMD enabled in the config and XWayland runs. However, now trying SteamVR hard crashes back to the login manager. I'm not sure how to get logs as the file disappears after the crash. I guess need to pipe that to somewhere stable for when the Hyprland process dies unexpectedly.

**Comment by podiki** [comment]
Patch at https://github.com/hyprwm/Hyprland/issues/6949#issuecomment-2409556165 has fixed this issue for me in my quick testing.

**Comment by podiki** [comment]
Should be fixed with #8116

**Comment by Atemu** [comment]
Finally got to try this out and it's indeed fixed, thanks a bunch @ikalco!

**Comment by Atemu** [comment]
It was still working for me a week ago on NixOS. I think you should open a new issue and inform us of your hardware circumstances aswell as logs from SteamVR.

**Comment by sophronesis** [comment]
> It was still working for me a week ago on NixOS.

i tried running steam from your config and still getting same error
