### ISSUE TITLE
Xwayland seems broken since 0.41.0

### ISSUE THREAD

**Issue by Meridolian** [hyprwm/Hyprland#8258]
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit  dirty ().
Date:
Tag: , commits:

flags: (if any)


System Information:
System name: Linux
Node name: meridolian-desktop
Release: 6.6.58
Version: #1-NixOS SMP PREEMPT_DYNAMIC Tue Oct 22 13:46:36 UTC 2024


GPU information:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA102 [GeForce RTX 3080] [10de:2206] (rev a1) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.05.5919.32e940c7c420"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.05 (Uakari)"
SUPPORT_END="2024-12-31"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.05 (Uakari)"
VERSION_CODENAME=uakari
VERSION_ID="24.05"


plugins:
```

Pretty weird that hyprctl version returns nothing on 0.40.0 ? but not the main problem here

</details>

### Description

Hello there,

I'm on Nixos 24.05, few days ago I nixos-rebuild switch --upgrade to upgrade all my packages and since then all my apps using xwayland don't work anymore.
If a run steam or xeyes for example I get a "Error: unable to open connection to display :0" or "could not connect to display :0".
The problem happened when I was on Hyprland 0.41.2.

I have a Nvidia gpu with driver 555.58, I tried to upgrade and downgrade it but nothing changed.
I have 6.6 kernel but it did not change since 24.05 has been released so I'm pretty sure it's not kernel related.

I tried to upgrade and downgrade xwayland version by overriding it in my nixos config but nothing changed.

So I tried to upgrade Hyprland to 0.42.0, 0.43.0, 0.44.0 and 0.44.1 but the problem was still there.
I tried to downgrade to 0.41.1 and 0.41.0, nothing changed.
Then I tried to downgrade to my previous Hyprland version, 0.40.0 and everything works like before, so this is probably a bug related to 0.41.0.

Do you have any idea what could cause this problem ?

### How to reproduce

Try to run steam on Hyprland > 0.40.0 with a nvidia gpu

**Comment by vaxerski** [comment]
do you have a VR headset plugged in? Those were causing crashes, which are fixed in -git.

**Comment by Meridolian** [comment]
@vaxerski Hi, no VR headset plugged in at all :/

**Comment by vaxerski** [comment]
you could still try git

**Comment by Meridolian** [comment]
Tried this : 
```
{ context, config, lib, ... }:
let
nixpkgs_master = import
    (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/0b2e723efac0720376031252fc500065121945d9.tar.gz")
    { config = config.nixpkgs.config; };
in
{
    wayland.windowManager.hyprland = {
        enable = true;
        package = nixpkgs_master.hyprland.overrideAttrs {
            src = nixpkgs_master.fetchFromGitHub {
                owner = "hyprwm";
                repo = "hyprland";
                rev = "4758a749e933b3eaa91a9eae96ab1d7d2d83e818"; # PR 8116
                sha256 = "1FaxcYkzHaZvRjT3kCDA0nS22bsmCgXDxO0gEF+XOec=";
            };
        };
```

I built hyprland with patches you mentionned but it did not solve my problem.

**Comment by sifmelcara** [comment]
> I'm on Nixos 24.05, few days ago I nixos-rebuild switch --upgrade to upgrade all my packages and since then all my apps using xwayland don't work anymore.

Could you bisect the nixos-24.05 channel? Or maybe consider using nixos-unstable instead

**Comment by theotherjimmy** [comment]
I've also ran into this, and it might be an infinite loop in shader compilation (from the backtrace that I can't paste due to not having a terminal emulator in this environment right now). I'm using an AMD RX 5700XT with amdgpu, so it's probably not related to the GPU itself.

**Comment by theotherjimmy** [comment]
Supposing that you're not using a vulkan app, you can run Hyprland, and therefore Xwayland, with XWAYLAND_NO_GLAMOR=1 to workaround this issue.

**Comment by Meridolian** [comment]
> > I'm on Nixos 24.05, few days ago I nixos-rebuild switch --upgrade to upgrade all my packages and since then all my apps using xwayland don't work anymore.
> 
> Could you bisect the nixos-24.05 channel? Or maybe consider using nixos-unstable instead

What do you mean by "bisect the nixos-24.05 channel" ?
Already tried nixos-unstable but nothing changed :/

**Comment by Meridolian** [comment]
> Supposing that you're not using a vulkan app, you can run Hyprland, and therefore Xwayland, with XWAYLAND_NO_GLAMOR=1 to workaround this issue.

Oh thanks !
Will try this asap !

**Comment by theotherjimmy** [comment]
Forcing my way past the shader compilation in gdb did not cause XWayland to start; instead, it gets hung elsewhere, amusingly consuming 400% CPU instead of the 100% it was consuming before. I'm running with no glamor ATM, and sadly Vulkan and some OpenGL apps fail.

**Comment by sifmelcara** [comment]
> What do you mean by "bisect the nixos-24.05 channel" ?

Use `nixos-rebuild list-generations` to find out what's the `nixpkgs` commit that used to work for you, clone `nixpkgs`, build your system from there, bisect and find out which exact commit breaks you https://wiki.nixos.org/wiki/Bisecting

**Comment by theotherjimmy** [comment]
After updating Hyprland & system mesa to 24.2.5, everything seems to be working again without the workarounds.

**Comment by Meridolian** [comment]
Seems fixed in 0.45.2 !
