### ISSUE TITLE
regression 0.46.2 => 0.47.0 - Broken cursor rendering for selected Wayland clients

### ISSUE THREAD

**Issue by mzonski** [hyprwm/Hyprland#9289]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Definitely a regression - something broke after update (requires bisect)

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  ().
Date: 2024-12-19
Tag: @TAG@, commits: 
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


flags set:
debug


System Information:
System name: Linux
Node name: corn
Release: 6.12.11
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu Jan 23 16:23:05 UTC 2025


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Lite Hash Rate] [10de:2488] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  565.77  Wed Nov 27 23:33:08 UTC 2024


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20250130.666e1b3"
CPE_NAME="cpe:/o:nixos:nixos:24.11"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_END="2025-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:




Hyprland 0.47.0 built from branch  at commit 64fefa3749868e6170b6275963c6528456a7d9f2  ().
Date: 2025-02-01
Tag: v0.47.0, commits: 
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


no flags were set


System Information:
System name: Linux
Node name: corn
Release: 6.12.11
Version: #1-NixOS SMP PREEMPT_DYNAMIC Thu Jan 23 16:23:05 UTC 2025


GPU information: 
00:02.0 Display controller [0380]: Intel Corporation HD Graphics 630 [8086:5912] (rev 04)
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [GeForce RTX 3070 Lite Hash Rate] [10de:2488] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  565.77  Wed Nov 27 23:33:08 UTC 2024


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20250130.666e1b3"
CPE_NAME="cpe:/o:nixos:nixos:24.11"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_END="2025-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
```

</details>

### Description

The mouse cursor disappears in IntelliJ-based IDEs with Wayland support on Hyprland 0.47.0+. The cursor only becomes visible after actions triggering redraw, remaining visible only within the redrawn surface. Issue confirmed absent on v0.46.2.

#### Version Information
- **Working**: Hyprland 0.46.2
- **Broken**: Hyprland 0.47.0, 0.47.1, and master branch
- **Affected**: IntelliJ with Wayland support

### Timeline
- Early January 2025: Working normally
- Mid-January 2025: Issue discovered during configuration changes
- Late January 2025: Confirmed as Hyprland regression after testing v0.46.2
- Current: Issue persists in 0.47.0+ and master branch

#### Prerequisites
- Hyprland 0.47.0+
- Any IntelliJ-based IDE (WebStorm, IntelliJ IDEA etc.)

#### Reproduction Steps
1. Install and configure Hyprland 0.47.0 or newer
2. Install an IntelliJ-based IDE  
3. Launch the IDE
4. Enable Wayland support:
  - Navigate to Help > Edit Custom VM Options
  - Add `-Dawt.toolkit.name=WLToolkit`
  - Restart IDE
5. Observe cursor visibility issues within IDE window

#### Behavior
**Expected**: Cursor visible at all times within IDE window  
**Actual**: Cursor disappears when it needs to redraw
**Workaround**: OBS running in background  

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [x] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

[hyprland_config_dump.txt](https://github.com/user-attachments/files/18631777/hyprland_config_dump.txt)

[0.47.0+ recording](https://www.youtube.com/watch?v=qsK9lm3Fo-Y)

**Comment by Estebiu** [comment]
Same thing happening in Blender.

**Comment by UjinT34** [comment]
Try `render:allow_early_buffer_release = 0`.
Might not be the best fix. Looks like `setCursorBuffer` and `setCursorSurface` shouldn't return early with `use_cpu_buffer` because some apps update and submit the same buffer again but copy is handled only for the first submission which sometimes doesn't even have any data. For some reason this is not the case with `render:allow_early_buffer_release = 0`. Maybe it forces those apps to use double-buffering.

Note that this setting might cause stutters or missed frames (presumably on weaker machines)

**Comment by myfess** [comment]
Same problem in VSCode

**Comment by bububirb** [comment]
> Try `render:allow_early_buffer_release = 0`. Might not be the best fix. Looks like `setCursorBuffer` and `setCursorSurface` shouldn't return early with `use_cpu_buffer` because some apps update and submit the same buffer again but copy is handled only for the first submission which sometimes doesn't even have any data. For some reason this is not the case with `render:allow_early_buffer_release = 0`. Maybe it forces those apps to use double-buffering.

For me this fixes the issue in Blender

**Comment by vaxerski** [comment]
@UjinT34 

> Might not be the best fix. Looks like setCursorBuffer and setCursorSurface shouldn't return early with use_cpu_buffer

source? I don't see any early returns

**Comment by UjinT34** [comment]
Should be copied again even when surface/buffer, hotspot and scale don't change.
https://github.com/hyprwm/Hyprland/blob/8a6778f0a087cdfc4bc1d3751b0be2c2bf3322aa/src/managers/PointerManager.cpp#L100-L101
https://github.com/hyprwm/Hyprland/blob/8a6778f0a087cdfc4bc1d3751b0be2c2bf3322aa/src/managers/PointerManager.cpp#L128-L129

**Comment by vaxerski** [comment]
right, and that isn't limited to cpu buffer

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/18689146/patch.txt)

this should help then

**Comment by Skidamek** [comment]
> [patch.txt](https://github.com/user-attachments/files/18689146/patch.txt)
> 
> this should help then

That patch doesn't seem to fix the issue, cursor is still hidden at least in blender with `allow_early_buffer_release`.

But why does having obs running in background fixes this issue? There are at least 3 issues on Hyprland i have right now which fixes themselves by having some screen capture running in background.

**Comment by UjinT34** [comment]
> But why does having obs running in background fixes this issue? There are at least 3 issues on Hyprland i have right now which fixes themselves by having some screen capture running in background.

Screen recording forces sw cursors. The issue is with hw cursors and cpu buffer copy.
Some features don't work with sw cursors and are disabled automatically. `no_hardware_cursors = 1` should help with issues that are fixed by obs running.

**Comment by littleblack111** [comment]
was fixed, regression again :/

**Comment by UjinT34** [comment]
@gulafaran @PlasmaPower `CPointerManager::setCursorBuffer` and `CPointerManager::setCursorSurface` return early if the same buffer/surfaces is submitted twice in a row. It's ok with normal rendering but fails with cpu buffer copy. `render:allow_buffer_release = 0` forced the buffers to be different. Might be a bug in the current buffer handling or in those functions when `cursor:use_cpu_buffer = 1`.

**Comment by PlasmaPower** [comment]
At first I thought this was an explicit sync issue because Blender isn't using explicit sync for its cursor surface:

```
[1899101.208] {Default Queue}  -> wl_shm_pool#73.create_buffer(new id wl_buffer#71, 170496, 24, 24, 96, 0)
[1899101.210] {Default Queue}  -> wl_surface#23.set_buffer_scale(1)
[1899101.211] {Default Queue}  -> wl_surface#23.attach(wl_buffer#71, 0, 0)
[1899101.212] {Default Queue}  -> wl_surface#23.damage(0, 0, 24, 24)
[1899101.213] {Default Queue}  -> wl_surface#23.commit()
[1899101.214] {Default Queue}  -> wl_pointer#22.set_cursor(1603, wl_surface#23, 3, 1)
```

But I tried delaying commits 10ms which fixes other explicit sync flickering, and it didn't fix this. It might just be copying over the cursor pixel data from a static CPU buffer. At any rate the problem doesn't seem to be a client lack of explicit sync support.

**Comment by PlasmaPower** [comment]
I think the issue is this actually: Blender commits the surface before assigning it the cursor role. That means that the commit never sets the `cursorPixelData` needed for cpu buffer cursor rendering. `updateCursorShm` is called when the client calls set_cursor, but by that point, the buffer has already been dropped and only the texture remains.

I think the two options here are:
- If the surface doesn't have a role, don't dropCurrentBuffer even if it's shm (this is the simplest and probably the best solution)
- In updateCursorShm, read in the pixel data from the GPU texture if the CPU buffer is missing (more complicated)

**Comment by PlasmaPower** [comment]
I implemented the first solution in https://github.com/hyprwm/Hyprland/pull/9700
