### ISSUE TITLE
Crash on getMonitorFromCursor()

### ISSUE THREAD

**Issue by acktax** [hyprwm/Hyprland#9552]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Probably not a regression / I don't remember it happening before

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.2 built from branch  at commit 882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff  (version: bump to 0.47.2).
Date: Sun Feb 2 00:47:17 2025
Tag: v0.47.2, commits: 5767
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.2


no flags were set


System Information:
System name: Linux
Node name: archstation
Release: 6.13.5-arch1-1.1
Version: #1 SMP PREEMPT_DYNAMIC Fri, 28 Feb 2025 23:48:01 +0000


GPU information:
08:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER] [10de:1e84] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  570.124.04  Release Build  (archlinux-builder@archstation)

                                                                                                                                             os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Youtube way playing in the background, and clicked on another tab in Zen browser, then Hyprland crashed.
May be related to #9222 

### How to reproduce

Unsure, but I did click near the edge of my monitor.
Possible that I could have clicked outside(?) the monitor due to some bug.

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [x] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

[hyprland_config_dump.txt](https://github.com/user-attachments/files/19103164/hyprland_config_dump.txt)

[hyprlandCrashReport96.txt](https://github.com/user-attachments/files/19103166/hyprlandCrashReport96.txt)

**Comment by nnyyxxxx** [comment]
try -git

**Comment by nnyyxxxx** [comment]
> I am getting the exact same problem on the `-git`

weird

**Comment by acktax** [comment]
I did not switch to -git because it only ever crashed once, but now it crashed again with the same function in the backtrace:

[hyprlandCrashReport823.txt](https://github.com/user-attachments/files/19142740/hyprlandCrashReport823.txt)

I'm going to turn on logging for Hyprland in case it happens again. If it does I'll post the logs as well.

**Comment by nnyyxxxx** [comment]
check git please, this should already be fixed with d01f9943e1d401b09fc53be3c161279ab4f2c5ba

> I did not switch to -git because it only ever crashed once, but now it crashed again with the same function in the backtrace:

**Comment by ninetailedtori** [comment]
CR on d30cc19d253a3db784ad10c3084f58cbb52d325a

**Comment by nnyyxxxx** [comment]
> Can still repro on [d30cc19](https://github.com/hyprwm/Hyprland/commit/d30cc19d253a3db784ad10c3084f58cbb52d325a)

send the crash log

**Comment by ninetailedtori** [comment]
...I really need a backup WM. Give me one sec to send it :)

**Comment by nnyyxxxx** [comment]
fixed with f15b49e0fd54d2cecc77f7eedbf7cd8f22215707 then

**Comment by nnyyxxxx** [comment]
#9552 is unrelated to thowse crash logs, similar though

f15b49e0fd54d2cecc77f7eedbf7cd8f22215707 fixed https://github.com/hyprwm/Hyprland/issues/9552#issuecomment-2709066369

d01f9943e1d401b09fc53be3c161279ab4f2c5ba fixed #9552

the call stack is just different

**Comment by ninetailedtori** [comment]
Double kill 💯

**Comment by JohnValanidas** [comment]
I was still experiencing this issue on the latest build even with clearing the build cache. That being said I was able to resolve it by removing my exec-once commands that involve Visual Studio Code. No idea why but I figured it would be best to share.

[hyprlandCrashReport66067.txt](https://github.com/user-attachments/files/19170537/hyprlandCrashReport66067.txt)
