### ISSUE TITLE
absurd amount of memory usage

### ISSUE THREAD

**Issue by Mecso2** [hyprwm/Hyprland#9611]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Probably not a regression / I don't remember it happening before

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.47.2 built from branch  at commit 882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff  (version: bump to 0.47.2).
Date: Sun Feb 2 00:47:17 2025
Tag: v0.47.2, commits: 5767
built against:
 aquamarine 0.7.2
 hyprlang 0.6.0
 hyprutils 0.5.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.2


no flags were set


System Information:
System name: Linux
Node name: Altitude
Release: 6.13.6-273-tkg-bore
Version: #1 SMP PREEMPT_DYNAMIC TKG Tue, 11 Mar 2025 11:57:39 +0000


GPU information:
0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD107M [GeForce RTX 4050 Max-Q / Mobile] [10de:28e1] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  570.124.04  Tue Feb 25 04:12:12 UTC 2025


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

</details>

### Description

Hyprland's memory usage grows trough out time.

![Image](https://github.com/user-attachments/assets/d758d281-9446-42af-b1ef-607686f59ee4)

 

### How to reproduce

As far as I can tell it happens whatever I do, but moving the position of a monitor with `hyprctl keyword monitor` seems to be causing a quite a large bump

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [x] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

### Additional info & File uploads

[hyprland.conf.txt](https://github.com/user-attachments/files/19233586/hyprland.conf.txt)

**Comment by vaxerski** [comment]
can't repro. Moved my monitor 4 times and mem actually dropped 6 megs

**Comment by ChacaS0** [comment]
I have the same issue, to me the RAM usage seem to increase whenever I move the cursor (mouse) on only 1 of my monitors. It increases indefinitely until reboot or re-log-in.

I tried to disable software cursors, same issue; tried hardware cursor, same issue. And only on that single monitor.

**Comment by Mecso2** [comment]
After hooking every variant of malloc (why are there so many), I ran Hyprland for a few hours. And when I decided to turn off my system there was 3GB unfreed memory allocated by librsvg (and that's only what was requested, with over allocation and accounting costs it's probably at least 4-5). Considering that that's an indirect dependency trough hyprcursor it seemed like @ChacaS0 is onto something. After looking at the hyprlang source code it seems like there [was a memory leak](https://github.com/hyprwm/hyprcursor/commit/dcadd3398abe146d60c67e0d9ee6e27b301cae82)  fixed in January but since the latest release was in December our systems still run the leaky version. I'll switch to the -git version (or maybe patch the last release version) and if that fixes it then I'll close the issue.

**Comment by Mecso2** [comment]
Yeah that was it

**Comment by vaxerski** [comment]
I'll make a hc release.

**Comment by ChacaS0** [comment]
> Yeah that was it

Did you only switch to `hyprcursor-git`? 

I tried switching and it didn't change anything for me, the exact same problem persists

![Image](https://github.com/user-attachments/assets/4440332e-7571-4982-9ffd-035ee849a9c1)

**Comment by vaxerski** [comment]
maybe your issue is different
