### ISSUE TITLE
Screen goes black when entering and exiting fullscreen in mpv

### ISSUE THREAD

**Issue by Daru-san** [hyprwm/Hyprland#9786]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Definitely a regression - something broke after update (requires bisect)

### System Info and Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland 0.48.0 built from branch main at commit 5ee35f914f921e5696030698e74fb5566a804768  (version: bump to 0.48.0).
Date: 2025-03-23
Tag: v0.48.0, commits: 5ee35f914f921e5696030698e74fb5566a804768
built against:
 aquamarine 0.8.0
 hyprlang 0.6.0
 hyprutils 0.5.2
 hyprcursor 0.1.12
 hyprgraphics 0.1.2


no flags were set


System Information:
System name: Linux
Node name: Aria
Release: 6.14.0
Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Mar 24 14:02:41 UTC 2025


GPU information: 


os-release: ANSI_COLOR="0;38;2;126;186;228"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="25.05.20250325.698214a"
CPE_NAME="cpe:/o:nixos:nixos:25.05"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 25.05 (Warbler)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="25.05 (Warbler)"
VERSION_CODENAME=warbler
VERSION_ID="25.05"


plugins:
```

</details>

### Description

Toggling fullsceen mode for mpv windows causes a temporary darkening of the screen.
This applies when changing from and to a workspace where mpv is fullscreen and toggling fullscreen using a keybind.

This behavior is not caught in videos, so my assumption is that the display temporarily cycles between off and on.

### How to reproduce

1. Toggle fullscreen mode on mpv
2. Switch between a workspace with a fullscreen instance of mpv and another

### Attach not paste

- [x] I understand that all text files must be *attached*, and not pasted directly. If not respected, this issue will likely get closed as spam

### Checklist of files to include below

- [ ] Hyprland config - `hyprctl systeminfo -c` (always include)
- [ ] Crash report (always include in case of crash)
- [ ] Video (always include in case of a visual bug)
- [ ] Logs (might contain useful info such as errors)

**Comment by zjeffer** [comment]
I had similar issues with my new 180hz monitor when fullscreening applications/videos, this got fixed when I set `vrr = 0` in the hyprland config, like so:
```
misc {
  vrr = 0
}
```
Can you try this?

**Comment by UjinT34** [comment]
Try `render:cm_fs_passthrough = 0`. mpv probably sets some image description that requires hdr or wide color gamut. HL by default will switch to an appropriate mode in fullscreen. Screen usually goes black during the switch.
`vrr = 2` might also cause this behaviour. Though it usually happens only while exiting fullscreen.

**Comment by Daru-san** [comment]
Thanks for the suggestions.
I tried both `misc:vrr = 0` and `render:cm_fs_passthrough = 0` but to no avail. The issue still persists.

**Comment by FelipeFMA** [comment]
I have the same issue, started happening after 0.48

**Comment by enderprism** [comment]
can confirm issue on my setup.
external screen and laptop screen are both 1920x1080@60fps, no hdr. only the external screen turns off when fullscreening mpv.
note that the issue didn't occur with the mpv flatpak when i tried it a few days ago.
in the meantime, i rolled back to 0.47.2

**Comment by UjinT34** [comment]
Looks like mpv supports content-type proto. Try `windowrule = content none, class:mpv`. If this helps than it means that your monitor supports switching profiles depending on the content type.
Probably need some option to disable https://github.com/hyprwm/Hyprland/blob/8ba20fcae124591718bddadd94c5e8c381d02097/src/render/Renderer.cpp#L1532

**Comment by Tony15246** [comment]
> Looks like mpv supports content-type proto. Try `windowrule = content none, class:mpv`. If this helps than it means that your monitor supports switching profiles depending on the content type. Probably need some option to disable

Tried `windowrule = content none, class:mpv`. It works like a charm. Thank you for the help.

**Comment by vaxerski** [comment]
Hello there!

This issue has been closed, as we are moving from issues to discussions. More about this can be found [here](https://wiki.hyprland.org/Contributing-and-Debugging/Issue-Guidelines/) and in #9854.

Firstly, please make sure this issue is still relevant in latest Hyprland. If so, we ask you to open a [discussion](https://github.com/hyprwm/Hyprland/discussions) (please read the discussion guidelines first, in the pinned post)

Thank you for your understanding!

**Comment by unifreak** [comment]
Still happening in v0.53.1, none of the above three fixes works.

**Comment by KevynValladares21** [comment]
This issue was present in the latest Hyprland 0.53, but I fixed it through the mpv config by adding the line

`target-colorspace-hint=no`

**Comment by unifreak** [comment]
> This issue was present in the latest Hyprland 0.53, but I fixed it through the mpv config by adding the line
> 
> `target-colorspace-hint=no`

Thank you for sharing this. But I tried it and still black out when toggle fullscreen. I remember this bug happens in older hyprland then fixed and reappeared, I guess this is a Hyprland issue.

**Comment by unifreak** [comment]
> > This issue was present in the latest Hyprland 0.53, but I fixed it through the mpv config by adding the line
> > `target-colorspace-hint=no`
> 
> Thank you for sharing this. But I tried it and still black out when toggle fullscreen. I remember this bug happens in older hyprland then fixed and reappeared, I guess this is a Hyprland issue.

Also I should mention that, this black out things doesn't happen when the mpv window is in a special workspace.

**Comment by UjinT34** [comment]
> Thank you for sharing this. But I tried it and still black out when toggle fullscreen. I remember this bug happens in older hyprland then fixed and reappeared, I guess this is a Hyprland issue.

That's not a bug. That's your hw feature. You can disable DS, VRR and CM to avoid it. Finding hw that doesn't do this with those features will be tricky. Usually only laptop screens can handle them without a black screen. Nothing can be done about this from HL side besides completely disabling the good stuff.

**Comment by unifreak** [comment]
> > Thank you for sharing this. But I tried it and still black out when toggle fullscreen. I remember this bug happens in older hyprland then fixed and reappeared, I guess this is a Hyprland issue.
> 
> That's not a bug. That's your hw feature. You can disable DS, VRR and CM to avoid it. Finding hw that doesn't do this with those features will be tricky. Usually only laptop screens can handle them without a black screen. Nothing can be done about this from HL side besides completely disabling the good stuff.

People keep saying "it's not hyprland thing", but here is one thing, I just installed niri and the same thing won't happen in siri session. Also, I tried setting various options (although not knowing exactly what they do, like vrr, cm, ....), but this thing still happen in hyprland. I'll leave this topic here, because that's just a minor anonying thing for me.

**Comment by UjinT34** [comment]
Niri has those features disabled by default or permanently disabled as in "not supported".
```
render {
  direct_scanout = 0
  cm_fs_passthrough = 0
  cm_enabled = 0
  send_content_type = 0
  cm_auto_hdr = 0
  non_shader_cm = 0
}

misc {
  vrr = 0
}
```
or some subset of those settings will fix your issue depending on which feature(s) is actually triggering a modeset with black screen.

**Comment by vaxerski** [comment]
It won't happen in niri because niri doesn't have color management or HDR at all. It's like saying that your allergic reaction to lactose is the ice cream stand's fault.

**Comment by kaiserkueche** [comment]
Hello there, same problem. I have the autoload.lua script with mpv, that loads all the following files in the folder into mpv, and the fix with `windowrule = match:class mpv, content none` works only for the first file I play. When the second (and further) file starts playing, I get the usual scanout problem. Would there be a fix that works in this case too?

**Comment by shohan11d** [comment]
Flatpak variant mpv doesnt suffer from this problem. also thanks to the person who mentioned this doesnt happen in special workspaces.

**Comment by user451421541757324** [comment]
With version 0.55, I encountered the bug too. I fixed it by disabling direct_scanout.

**Comment by Panelgamer** [comment]
> Niri has those features disabled by default or permanently disabled as in "not supported".
> 
> ```
> render {
>   direct_scanout = 0
>   cm_fs_passthrough = 0
>   cm_enabled = 0
>   send_content_type = 0
>   cm_auto_hdr = 0
>   non_shader_cm = 0
> }
> 
> misc {
>   vrr = 0
> }
> ```
> 
> or some subset of those settings will fix your issue depending on which feature(s) is actually triggering a modeset with black screen.

It works! But the flag `cm_fs_passthrough = 0` now is useless. What worked for me was this:
```
render {
  direct_scanout = 0
  cm_enabled = 0
  send_content_type = 0
  cm_auto_hdr = 0
  non_shader_cm = 0
}

misc {
  vrr = 0
}
```

Remember to put it on your hyprland.conf. And if you don't have your own dots (like you're using another Hyprland Configuration) then put it on your custom directory that's inside your hypr/config directory.

Edit: Now the previous fix does not work on hyprland due to the changes to .lua language. Here's the new version

```
hl.config ({
	render = {
  		direct_scanout = 0,
  		cm_enabled = 0,
  		send_content_type = 0,
  		cm_auto_hdr = 0,
 		non_shader_cm = 0,
	},
	misc = {
  		vrr = 0
	},
})
```

**Comment by ann9cht** [comment]
> > Niri has those features disabled by default or permanently disabled as in "not supported".
> > ```
> > render {
> >   direct_scanout = 0
> >   cm_fs_passthrough = 0
> >   cm_enabled = 0
> >   send_content_type = 0
> >   cm_auto_hdr = 0
> >   non_shader_cm = 0
> > }
> > 
> > misc {
> >   vrr = 0
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or some subset of those settings will fix your issue depending on which feature(s) is actually triggering a modeset with black screen.
> 
> It works! But the flag `cm_fs_passthrough = 0` now is useless. What worked for me was this:
> 
> ```
> render {
>   direct_scanout = 0
>   cm_enabled = 0
>   send_content_type = 0
>   cm_auto_hdr = 0
>   non_shader_cm = 0
> }
> 
> misc {
>   vrr = 0
> }
> ```
> 
> Remember to put it on your hyprland.conf. And if you don't have your own dots (like you're using another Hyprland Configuration) then put it on your custom directory that's inside your hypr/config directory.
> 
> Edit: Now the previous fix does not work on hyprland due to the changes to .lua language. Here's the new version
> 
> ```
> hl.config ({
> 	render = {
>   		direct_scanout = 0,
>   		cm_enabled = 0,
>   		send_content_type = 0,
>   		cm_auto_hdr = 0,
>  		non_shader_cm = 0,
> 	},
> 	misc = {
>   		vrr = 0
> 	},
> })
> ```

Disabling `send_content_type` did the trick for me. Huge thanks!
